/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.members;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_member")
public class Member {

    @Column(name = "c_member_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_member_firstname", table = "arts_t_member", nullable = false, length = 100)
    @Basic
    private String cMemberFirstname;

    @Column(name = "c_member_phonenum", table = "arts_t_member", nullable = false, length = 50)
    @Basic
    private String cMemberPhonenum;

    @Column(name = "c_member_email", table = "arts_t_member", length = 100)
    @Basic
    private String cMemberEmail;

    @Column(name = "c_member_status", table = "arts_t_member", nullable = false)
    @Basic
    private Character cMemberStatus;

    @Column(name = "c_member_domain", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cMemberDomain;

    @Column(name = "c_member_modifiedby", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cMemberModifiedby;

    @Column(name = "c_member_modifiedon", table = "arts_t_member", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemberModifiedon;

    @Column(name = "c_member_lastname", table = "arts_t_member", length = 100)
    @Basic
    private String cMemberLastname;

    @Column(name = "c_member_dateofbirth", table = "arts_t_member", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemberDateofbirth;

    @Column(name = "c_member_address1", table = "arts_t_member", nullable = false)
    @Basic
    private String cMemberAddress1;

    @Column(name = "c_member_address2", table = "arts_t_member")
    @Basic
    private String cMemberAddress2;

    @Column(name = "c_occupationtype_id", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cOccupationtypeId;

    @Column(name = "c_city_id1", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cCityId1;

    @Column(name = "c_city_id2", table = "arts_t_member", length = 36)
    @Basic
    private String cCityId2;

    @Column(name = "c_member_postalcode1", table = "arts_t_member", nullable = false, length = 10)
    @Basic
    private String cMemberPostalcode1;

    @Column(name = "c_member_postalcode2", table = "arts_t_member", length = 10)
    @Basic
    private String cMemberPostalcode2;

    @Column(name = "c_unit_id", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_user_id", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_member_phonenum2", table = "arts_t_member", length = 50)
    @Basic
    private String cMemberPhonenum2;

    @Column(name = "c_title_id", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cTitleId;

    @Column(name = "c_member_createdby", table = "arts_t_member", nullable = false, length = 36)
    @Basic
    private String cMemberCreatedby;

    @Column(name = "c_member_createdon", table = "arts_t_member", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemberCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcMemberFirstname() {
        return cMemberFirstname;
    }

    public void setcMemberFirstname(String cMemberFirstname) {
        this.cMemberFirstname = cMemberFirstname;
    }

    public String getcMemberPhonenum() {
        return cMemberPhonenum;
    }

    public void setcMemberPhonenum(String cMemberPhonenum) {
        this.cMemberPhonenum = cMemberPhonenum;
    }

    public String getcMemberEmail() {
        return cMemberEmail;
    }

    public void setcMemberEmail(String cMemberEmail) {
        this.cMemberEmail = cMemberEmail;
    }

    public Character getcMemberStatus() {
        return cMemberStatus;
    }

    public void setcMemberStatus(Character cMemberStatus) {
        this.cMemberStatus = cMemberStatus;
    }

    public String getcMemberDomain() {
        return cMemberDomain;
    }

    public void setcMemberDomain(String cMemberDomain) {
        this.cMemberDomain = cMemberDomain;
    }

    public String getcMemberModifiedby() {
        return cMemberModifiedby;
    }

    public void setcMemberModifiedby(String cMemberModifiedby) {
        this.cMemberModifiedby = cMemberModifiedby;
    }

    public Date getcMemberModifiedon() {
        return cMemberModifiedon;
    }

    public void setcMemberModifiedon(Date cMemberModifiedon) {
        this.cMemberModifiedon = cMemberModifiedon;
    }

    public String getcMemberLastname() {
        return cMemberLastname;
    }

    public void setcMemberLastname(String cMemberLastname) {
        this.cMemberLastname = cMemberLastname;
    }

    public Date getcMemberDateofbirth() {
        return cMemberDateofbirth;
    }

    public void setcMemberDateofbirth(Date cMemberDateofbirth) {
        this.cMemberDateofbirth = cMemberDateofbirth;
    }

    public String getcMemberAddress1() {
        return cMemberAddress1;
    }

    public void setcMemberAddress1(String cMemberAddress1) {
        this.cMemberAddress1 = cMemberAddress1;
    }

    public String getcMemberAddress2() {
        return cMemberAddress2;
    }

    public void setcMemberAddress2(String cMemberAddress2) {
        this.cMemberAddress2 = cMemberAddress2;
    }

    public String getcOccupationtypeId() {
        return cOccupationtypeId;
    }

    public void setcOccupationtypeId(String cOccupationtypeId) {
        this.cOccupationtypeId = cOccupationtypeId;
    }

    public String getcCityId1() {
        return cCityId1;
    }

    public void setcCityId1(String cCityId1) {
        this.cCityId1 = cCityId1;
    }

    public String getcCityId2() {
        return cCityId2;
    }

    public void setcCityId2(String cCityId2) {
        this.cCityId2 = cCityId2;
    }

    public String getcMemberPostalcode1() {
        return cMemberPostalcode1;
    }

    public void setcMemberPostalcode1(String cMemberPostalcode1) {
        this.cMemberPostalcode1 = cMemberPostalcode1;
    }

    public String getcMemberPostalcode2() {
        return cMemberPostalcode2;
    }

    public void setcMemberPostalcode2(String cMemberPostalcode2) {
        this.cMemberPostalcode2 = cMemberPostalcode2;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcMemberPhonenum2() {
        return cMemberPhonenum2;
    }

    public void setcMemberPhonenum2(String cMemberPhonenum2) {
        this.cMemberPhonenum2 = cMemberPhonenum2;
    }

    public String getcTitleId() {
        return cTitleId;
    }

    public void setcTitleId(String cTitleId) {
        this.cTitleId = cTitleId;
    }

    public String getcMemberCreatedby() {
        return cMemberCreatedby;
    }

    public void setcMemberCreatedby(String cMemberCreatedby) {
        this.cMemberCreatedby = cMemberCreatedby;
    }

    public Date getcMemberCreatedon() {
        return cMemberCreatedon;
    }

    public void setcMemberCreatedon(Date cMemberCreatedon) {
        this.cMemberCreatedon = cMemberCreatedon;
    }

   
}
