/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.members;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_membertype", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_membertype_code"})})
public class Membertype implements Serializable {

    @Column(name = "c_membertype_id", table = "arts_t_membertype", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_membertype_code", table = "arts_t_membertype", nullable = false, length = 36)
    @Basic
    private String cMembertypeCode;

    @Column(name = "c_membertype_name", table = "arts_t_membertype", nullable = false, length = 100)
    @Basic
    private String cMembertypeName;

    @Column(name = "c_membertype_status", table = "arts_t_membertype", nullable = false)
    @Basic
    private Character cMembertypeStatus;

    @Column(name = "c_membertype_domain", table = "arts_t_membertype", nullable = false, length = 36)
    @Basic
    private String cMembertypeDomain;

    @Column(name = "c_membertype_modifiedby", table = "arts_t_membertype", nullable = false, length = 36)
    @Basic
    private String cMembertypeModifiedby;

    @Column(name = "c_membertype_modifiedon", table = "arts_t_membertype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembertypeModifiedon;

    @Column(name = "c_membertype_validdays", table = "arts_t_membertype", nullable = false)
    @Basic
    private int cMembertypeValiddays;

    @Column(name = "c_membertype_type", table = "arts_t_membertype", nullable = false)
    @Basic
    private Character cMembertypeType;

    @Column(name = "c_membertype_createdby", table = "arts_t_membertype", nullable = false, length = 36)
    @Basic
    private String cMembertypeCreatedby;

    @Column(name = "c_membertype_createdon", table = "arts_t_membertype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembertypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcMembertypeCode() {
        return cMembertypeCode;
    }

    public void setcMembertypeCode(String cMembertypeCode) {
        this.cMembertypeCode = cMembertypeCode;
    }

    public String getcMembertypeName() {
        return cMembertypeName;
    }

    public void setcMembertypeName(String cMembertypeName) {
        this.cMembertypeName = cMembertypeName;
    }

    public Character getcMembertypeStatus() {
        return cMembertypeStatus;
    }

    public void setcMembertypeStatus(Character cMembertypeStatus) {
        this.cMembertypeStatus = cMembertypeStatus;
    }

    public String getcMembertypeDomain() {
        return cMembertypeDomain;
    }

    public void setcMembertypeDomain(String cMembertypeDomain) {
        this.cMembertypeDomain = cMembertypeDomain;
    }

    public String getcMembertypeModifiedby() {
        return cMembertypeModifiedby;
    }

    public void setcMembertypeModifiedby(String cMembertypeModifiedby) {
        this.cMembertypeModifiedby = cMembertypeModifiedby;
    }

    public Date getcMembertypeModifiedon() {
        return cMembertypeModifiedon;
    }

    public void setcMembertypeModifiedon(Date cMembertypeModifiedon) {
        this.cMembertypeModifiedon = cMembertypeModifiedon;
    }

    public int getcMembertypeValiddays() {
        return cMembertypeValiddays;
    }

    public void setcMembertypeValiddays(int cMembertypeValiddays) {
        this.cMembertypeValiddays = cMembertypeValiddays;
    }

    public Character getcMembertypeType() {
        return cMembertypeType;
    }

    public void setcMembertypeType(Character cMembertypeType) {
        this.cMembertypeType = cMembertypeType;
    }

    public String getcMembertypeCreatedby() {
        return cMembertypeCreatedby;
    }

    public void setcMembertypeCreatedby(String cMembertypeCreatedby) {
        this.cMembertypeCreatedby = cMembertypeCreatedby;
    }

    public Date getcMembertypeCreatedon() {
        return cMembertypeCreatedon;
    }

    public void setcMembertypeCreatedon(Date cMembertypeCreatedon) {
        this.cMembertypeCreatedon = cMembertypeCreatedon;
    }
    
    
}
