/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.members;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_membership")
public class Membership implements Serializable {

    @Column(name = "c_membership_id", table = "arts_t_membership", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_membership_idnum", table = "arts_t_membership", nullable = false, length = 36)
    @Basic
    private String cMembershipIdnum;

    @Column(name = "c_membership_startdate", table = "arts_t_membership", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembershipStartdate;

    @Column(name = "c_membership_enddate", table = "arts_t_membership", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembershipEnddate;

    @Column(name = "c_membership_status", table = "arts_t_membership", nullable = false)
    @Basic
    private Character cMembershipStatus;

    @Column(name = "c_membership_domain", table = "arts_t_membership", nullable = false, length = 36)
    @Basic
    private String cMembershipDomain;

    @Column(name = "c_membership_modifiedby", table = "arts_t_membership", nullable = false, length = 36)
    @Basic
    private String cMembershipModifiedby;

    @Column(name = "c_membership_modifiedon", table = "arts_t_membership", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembershipModifiedon;

    @Column(name = "c_member_id", table = "arts_t_membership", nullable = false, length = 36)
    @Basic
    private String cMemberId;

    @Column(name = "c_membership_beginningbal", table = "arts_t_membership", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cMembershipBeginningbal;

    @Column(name = "c_membership_earnpoint", table = "arts_t_membership", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cMembershipEarnpoint;

    @Column(name = "c_membership_redeempoint", table = "arts_t_membership", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cMembershipRedeempoint;

    @Column(name = "c_membership_endingbal", table = "arts_t_membership", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cMembershipEndingbal;

    @Column(name = "c_membership_createdby", table = "arts_t_membership", nullable = false, length = 36)
    @Basic
    private String cMembershipCreatedby;

    @Column(name = "c_membership_createdon", table = "arts_t_membership", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMembershipCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcMembershipIdnum() {
        return cMembershipIdnum;
    }

    public void setcMembershipIdnum(String cMembershipIdnum) {
        this.cMembershipIdnum = cMembershipIdnum;
    }

    public Date getcMembershipStartdate() {
        return cMembershipStartdate;
    }

    public void setcMembershipStartdate(Date cMembershipStartdate) {
        this.cMembershipStartdate = cMembershipStartdate;
    }

    public Date getcMembershipEnddate() {
        return cMembershipEnddate;
    }

    public void setcMembershipEnddate(Date cMembershipEnddate) {
        this.cMembershipEnddate = cMembershipEnddate;
    }

    public Character getcMembershipStatus() {
        return cMembershipStatus;
    }

    public void setcMembershipStatus(Character cMembershipStatus) {
        this.cMembershipStatus = cMembershipStatus;
    }

    public String getcMembershipDomain() {
        return cMembershipDomain;
    }

    public void setcMembershipDomain(String cMembershipDomain) {
        this.cMembershipDomain = cMembershipDomain;
    }

    public String getcMembershipModifiedby() {
        return cMembershipModifiedby;
    }

    public void setcMembershipModifiedby(String cMembershipModifiedby) {
        this.cMembershipModifiedby = cMembershipModifiedby;
    }

    public Date getcMembershipModifiedon() {
        return cMembershipModifiedon;
    }

    public void setcMembershipModifiedon(Date cMembershipModifiedon) {
        this.cMembershipModifiedon = cMembershipModifiedon;
    }

    public String getcMemberId() {
        return cMemberId;
    }

    public void setcMemberId(String cMemberId) {
        this.cMemberId = cMemberId;
    }

    public BigDecimal getcMembershipBeginningbal() {
        return cMembershipBeginningbal;
    }

    public void setcMembershipBeginningbal(BigDecimal cMembershipBeginningbal) {
        this.cMembershipBeginningbal = cMembershipBeginningbal;
    }

    public BigDecimal getcMembershipEarnpoint() {
        return cMembershipEarnpoint;
    }

    public void setcMembershipEarnpoint(BigDecimal cMembershipEarnpoint) {
        this.cMembershipEarnpoint = cMembershipEarnpoint;
    }

    public BigDecimal getcMembershipRedeempoint() {
        return cMembershipRedeempoint;
    }

    public void setcMembershipRedeempoint(BigDecimal cMembershipRedeempoint) {
        this.cMembershipRedeempoint = cMembershipRedeempoint;
    }

    public BigDecimal getcMembershipEndingbal() {
        return cMembershipEndingbal;
    }

    public void setcMembershipEndingbal(BigDecimal cMembershipEndingbal) {
        this.cMembershipEndingbal = cMembershipEndingbal;
    }

    public String getcMembershipCreatedby() {
        return cMembershipCreatedby;
    }

    public void setcMembershipCreatedby(String cMembershipCreatedby) {
        this.cMembershipCreatedby = cMembershipCreatedby;
    }

    public Date getcMembershipCreatedon() {
        return cMembershipCreatedon;
    }

    public void setcMembershipCreatedon(Date cMembershipCreatedon) {
        this.cMembershipCreatedon = cMembershipCreatedon;
    }

    

}
