/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.members;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_memmemtype", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_memmemtype_idnum"})})
public class Memmemtype implements Serializable {

    @Column(name = "c_memmemtype_id", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_membertype_id", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Basic
    private String cMembertypeId;

    @Column(name = "c_member_id", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Basic
    private String cMemberId;

    @Column(name = "c_memmemtype_idnum", table = "arts_t_memmemtype", nullable = false, length = 50)
    @Basic
    private String cMemmemtypeIdnum;

    @Column(name = "c_memmemtype_status", table = "arts_t_memmemtype", nullable = false)
    @Basic
    private Character cMemmemtypeStatus;

    @Column(name = "c_memmemtype_domain", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Basic
    private String cMemmemtypeDomain;

    @Column(name = "c_memmemtype_modifiedby", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Basic
    private String cMemmemtypeModifiedby;

    @Column(name = "c_memmemtype_modifiedon", table = "arts_t_memmemtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemmemtypeModifiedon;

    @Column(name = "c_memmemtype_startdate", table = "arts_t_memmemtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemmemtypeStartdate;

    @Column(name = "c_memmemtype_enddate", table = "arts_t_memmemtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemmemtypeEnddate;

    @Column(name = "c_user_idapp1", table = "arts_t_memmemtype", length = 36)
    @Basic
    private String cUserIdapp1;

    @Column(name = "c_memmemtype_appdate1", table = "arts_t_memmemtype")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemmemtypeAppdate1;

    @Column(name = "c_memmemtype_memcode", table = "arts_t_memmemtype", length = 50)
    @Basic
    private String cMemmemtypeMemcode;

    @Column(name = "c_memmemtype_createdby", table = "arts_t_memmemtype", nullable = false, length = 36)
    @Basic
    private String cMemmemtypeCreatedby;

    @Column(name = "c_memmemtype_createdon", table = "arts_t_memmemtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemmemtypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcMembertypeId() {
        return cMembertypeId;
    }

    public void setcMembertypeId(String cMembertypeId) {
        this.cMembertypeId = cMembertypeId;
    }

    public String getcMemberId() {
        return cMemberId;
    }

    public void setcMemberId(String cMemberId) {
        this.cMemberId = cMemberId;
    }

    public String getcMemmemtypeIdnum() {
        return cMemmemtypeIdnum;
    }

    public void setcMemmemtypeIdnum(String cMemmemtypeIdnum) {
        this.cMemmemtypeIdnum = cMemmemtypeIdnum;
    }

    public Character getcMemmemtypeStatus() {
        return cMemmemtypeStatus;
    }

    public void setcMemmemtypeStatus(Character cMemmemtypeStatus) {
        this.cMemmemtypeStatus = cMemmemtypeStatus;
    }

    public String getcMemmemtypeDomain() {
        return cMemmemtypeDomain;
    }

    public void setcMemmemtypeDomain(String cMemmemtypeDomain) {
        this.cMemmemtypeDomain = cMemmemtypeDomain;
    }

    public String getcMemmemtypeModifiedby() {
        return cMemmemtypeModifiedby;
    }

    public void setcMemmemtypeModifiedby(String cMemmemtypeModifiedby) {
        this.cMemmemtypeModifiedby = cMemmemtypeModifiedby;
    }

    public Date getcMemmemtypeModifiedon() {
        return cMemmemtypeModifiedon;
    }

    public void setcMemmemtypeModifiedon(Date cMemmemtypeModifiedon) {
        this.cMemmemtypeModifiedon = cMemmemtypeModifiedon;
    }

    public Date getcMemmemtypeStartdate() {
        return cMemmemtypeStartdate;
    }

    public void setcMemmemtypeStartdate(Date cMemmemtypeStartdate) {
        this.cMemmemtypeStartdate = cMemmemtypeStartdate;
    }

    public Date getcMemmemtypeEnddate() {
        return cMemmemtypeEnddate;
    }

    public void setcMemmemtypeEnddate(Date cMemmemtypeEnddate) {
        this.cMemmemtypeEnddate = cMemmemtypeEnddate;
    }

    public String getcUserIdapp1() {
        return cUserIdapp1;
    }

    public void setcUserIdapp1(String cUserIdapp1) {
        this.cUserIdapp1 = cUserIdapp1;
    }

    public Date getcMemmemtypeAppdate1() {
        return cMemmemtypeAppdate1;
    }

    public void setcMemmemtypeAppdate1(Date cMemmemtypeAppdate1) {
        this.cMemmemtypeAppdate1 = cMemmemtypeAppdate1;
    }

    public String getcMemmemtypeMemcode() {
        return cMemmemtypeMemcode;
    }

    public void setcMemmemtypeMemcode(String cMemmemtypeMemcode) {
        this.cMemmemtypeMemcode = cMemmemtypeMemcode;
    }

    public String getcMemmemtypeCreatedby() {
        return cMemmemtypeCreatedby;
    }

    public void setcMemmemtypeCreatedby(String cMemmemtypeCreatedby) {
        this.cMemmemtypeCreatedby = cMemmemtypeCreatedby;
    }

    public Date getcMemmemtypeCreatedon() {
        return cMemmemtypeCreatedon;
    }

    public void setcMemmemtypeCreatedon(Date cMemmemtypeCreatedon) {
        this.cMemmemtypeCreatedon = cMemmemtypeCreatedon;
    }
    
    

}
