/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.modules;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_moduletype")
public class Moduletype {

    @Column(name = "c_moduletype_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_moduletype_code", table = "arts_t_moduletype", nullable = false, length = 36)
    @Basic
    private String cModuletypeCode;

    @Column(name = "c_moduletype_name", table = "arts_t_moduletype", nullable = false, length = 50)
    @Basic
    private String cModuletypeName;

    @Column(name = "c_moduletype_status", table = "arts_t_moduletype", nullable = false)
    @Basic
    private Character cModuletypeStatus;

    @Column(name = "c_moduletype_domain", table = "arts_t_moduletype", nullable = false, length = 36)
    @Basic
    private String cModuletypeDomain;

    @Column(name = "c_moduletype_modifiedby", table = "arts_t_moduletype", nullable = false, length = 36)
    @Basic
    private String cModuletypeModifiedby;

    @Column(name = "c_moduletype_modifiedon", table = "arts_t_moduletype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cModuletypeModifiedon;

    @Column(name = "c_moduletype_createdby", table = "arts_t_moduletype", nullable = false, length = 36)
    @Basic
    private String cModuletypeCreatedby;

    @Column(name = "c_moduletype_createdon", table = "arts_t_moduletype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cModuletypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcModuletypeCode() {
        return cModuletypeCode;
    }

    public void setcModuletypeCode(String cModuletypeCode) {
        this.cModuletypeCode = cModuletypeCode;
    }

    public String getcModuletypeName() {
        return cModuletypeName;
    }

    public void setcModuletypeName(String cModuletypeName) {
        this.cModuletypeName = cModuletypeName;
    }

    public Character getcModuletypeStatus() {
        return cModuletypeStatus;
    }

    public void setcModuletypeStatus(Character cModuletypeStatus) {
        this.cModuletypeStatus = cModuletypeStatus;
    }

    public String getcModuletypeDomain() {
        return cModuletypeDomain;
    }

    public void setcModuletypeDomain(String cModuletypeDomain) {
        this.cModuletypeDomain = cModuletypeDomain;
    }

    public String getcModuletypeModifiedby() {
        return cModuletypeModifiedby;
    }

    public void setcModuletypeModifiedby(String cModuletypeModifiedby) {
        this.cModuletypeModifiedby = cModuletypeModifiedby;
    }

    public Date getcModuletypeModifiedon() {
        return cModuletypeModifiedon;
    }

    public void setcModuletypeModifiedon(Date cModuletypeModifiedon) {
        this.cModuletypeModifiedon = cModuletypeModifiedon;
    }

    public String getcModuletypeCreatedby() {
        return cModuletypeCreatedby;
    }

    public void setcModuletypeCreatedby(String cModuletypeCreatedby) {
        this.cModuletypeCreatedby = cModuletypeCreatedby;
    }

    public Date getcModuletypeCreatedon() {
        return cModuletypeCreatedon;
    }

    public void setcModuletypeCreatedon(Date cModuletypeCreatedon) {
        this.cModuletypeCreatedon = cModuletypeCreatedon;
    }
    
    
}
