/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.modules;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_objactivity", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_objactivity_code"})})
public class Objactivity implements Serializable {

    @Column(name = "c_objactivity_id", table = "arts_t_objactivity", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_objactivity_name", table = "arts_t_objactivity", nullable = false)
    @Basic
    private String cObjactivityName;

    @Column(name = "c_objactivity_status", table = "arts_t_objactivity", nullable = false)
    @Basic
    private Character cObjactivityStatus;

    @Column(name = "c_objactivity_domain", table = "arts_t_objactivity", nullable = false, length = 36)
    @Basic
    private String cObjactivityDomain;

    @Column(name = "c_objactivity_modifiedby", table = "arts_t_objactivity", nullable = false, length = 36)
    @Basic
    private String cObjactivityModifiedby;

    @Column(name = "c_objactivity_modifiedon", table = "arts_t_objactivity", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cObjactivityModifiedon;

    @Column(name = "c_module_id", table = "arts_t_objactivity", nullable = false, length = 36)
    @Basic
    private String cModuleId;

    @Column(name = "c_objactivity_code", table = "arts_t_objactivity", nullable = false, length = 50)
    @Basic
    private String cObjactivityCode;

    @Column(name = "c_objactivity_createdby", table = "arts_t_objactivity", length = 36)
    @Basic
    private String cObjactivityCreatedby;

    @Column(name = "c_objactivity_createdon", table = "arts_t_objactivity")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cObjactivityCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcObjactivityName() {
        return cObjactivityName;
    }

    public void setcObjactivityName(String cObjactivityName) {
        this.cObjactivityName = cObjactivityName;
    }

    public Character getcObjactivityStatus() {
        return cObjactivityStatus;
    }

    public void setcObjactivityStatus(Character cObjactivityStatus) {
        this.cObjactivityStatus = cObjactivityStatus;
    }

    public String getcObjactivityDomain() {
        return cObjactivityDomain;
    }

    public void setcObjactivityDomain(String cObjactivityDomain) {
        this.cObjactivityDomain = cObjactivityDomain;
    }

    public String getcObjactivityModifiedby() {
        return cObjactivityModifiedby;
    }

    public void setcObjactivityModifiedby(String cObjactivityModifiedby) {
        this.cObjactivityModifiedby = cObjactivityModifiedby;
    }

    public Date getcObjactivityModifiedon() {
        return cObjactivityModifiedon;
    }

    public void setcObjactivityModifiedon(Date cObjactivityModifiedon) {
        this.cObjactivityModifiedon = cObjactivityModifiedon;
    }

    public String getcModuleId() {
        return cModuleId;
    }

    public void setcModuleId(String cModuleId) {
        this.cModuleId = cModuleId;
    }

    public String getcObjactivityCode() {
        return cObjactivityCode;
    }

    public void setcObjactivityCode(String cObjactivityCode) {
        this.cObjactivityCode = cObjactivityCode;
    }

    public String getcObjactivityCreatedby() {
        return cObjactivityCreatedby;
    }

    public void setcObjactivityCreatedby(String cObjactivityCreatedby) {
        this.cObjactivityCreatedby = cObjactivityCreatedby;
    }

    public Date getcObjactivityCreatedon() {
        return cObjactivityCreatedon;
    }

    public void setcObjactivityCreatedon(Date cObjactivityCreatedon) {
        this.cObjactivityCreatedon = cObjactivityCreatedon;
    }
    
    

}
