/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.trains;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_subclass", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_subclass_code"})})
public class Subclass implements Serializable {

    @Column(name = "c_subclass_id", table = "arts_t_subclass", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_subclass_code", table = "arts_t_subclass", nullable = false, length = 10)
    @Basic
    private String cSubclassCode;

    @Column(name = "c_subclass_status", table = "arts_t_subclass", nullable = false)
    @Basic
    private Character cSubclassStatus;

    @Column(name = "c_subclass_domain", table = "arts_t_subclass", nullable = false, length = 36)
    @Basic
    private String cSubclassDomain;

    @Column(name = "c_subclass_modifiedby", table = "arts_t_subclass", nullable = false, length = 36)
    @Basic
    private String cSubclassModifiedby;

    @Column(name = "c_subclass_modifiedon", table = "arts_t_subclass", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSubclassModifiedon;

    @Column(name = "c_wagonclass_id", table = "arts_t_subclass", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_subclass_note", table = "arts_t_subclass", length = 300)
    @Basic
    private String cSubclassNote;

    @Column(name = "c_subclass_createdby", table = "arts_t_subclass", nullable = false, length = 36)
    @Basic
    private String cSubclassCreatedby;

    @Column(name = "c_subclass_createdon", table = "arts_t_subclass", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSubclassCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcSubclassCode() {
        return cSubclassCode;
    }

    public void setcSubclassCode(String cSubclassCode) {
        this.cSubclassCode = cSubclassCode;
    }

    public Character getcSubclassStatus() {
        return cSubclassStatus;
    }

    public void setcSubclassStatus(Character cSubclassStatus) {
        this.cSubclassStatus = cSubclassStatus;
    }

    public String getcSubclassDomain() {
        return cSubclassDomain;
    }

    public void setcSubclassDomain(String cSubclassDomain) {
        this.cSubclassDomain = cSubclassDomain;
    }

    public String getcSubclassModifiedby() {
        return cSubclassModifiedby;
    }

    public void setcSubclassModifiedby(String cSubclassModifiedby) {
        this.cSubclassModifiedby = cSubclassModifiedby;
    }

    public Date getcSubclassModifiedon() {
        return cSubclassModifiedon;
    }

    public void setcSubclassModifiedon(Date cSubclassModifiedon) {
        this.cSubclassModifiedon = cSubclassModifiedon;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public String getcSubclassNote() {
        return cSubclassNote;
    }

    public void setcSubclassNote(String cSubclassNote) {
        this.cSubclassNote = cSubclassNote;
    }

    public String getcSubclassCreatedby() {
        return cSubclassCreatedby;
    }

    public void setcSubclassCreatedby(String cSubclassCreatedby) {
        this.cSubclassCreatedby = cSubclassCreatedby;
    }

    public Date getcSubclassCreatedon() {
        return cSubclassCreatedon;
    }

    public void setcSubclassCreatedon(Date cSubclassCreatedon) {
        this.cSubclassCreatedon = cSubclassCreatedon;
    }

    
}
