/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.trains;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_trainmiles")
public class Trainmiles {

    @Column(name = "c_trainmiles_id", table = "arts_t_trainmiles", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_trainmiles_name", table = "arts_t_trainmiles", nullable = false, length = 200)
    @Basic
    private String cTrainmilesName;

    @Column(name = "c_trainmiles_status", table = "arts_t_trainmiles", nullable = false)
    @Basic
    private Character cTrainmilesStatus;

    @Column(name = "c_trainmiles_domain", table = "arts_t_trainmiles", nullable = false, length = 36)
    @Basic
    private String cTrainmilesDomain;

    @Column(name = "c_trainmiles_modifiedby", table = "arts_t_trainmiles", nullable = false, length = 36)
    @Basic
    private String cTrainmilesModifiedby;

    @Column(name = "c_trainmiles_modifiedon", table = "arts_t_trainmiles", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainmilesModifiedon;

    @Column(name = "c_trainmiles_createdby", table = "arts_t_trainmiles", nullable = false, length = 36)
    @Basic
    private String cTrainmilesCreatedby;

    @Column(name = "c_trainmiles_createdon", table = "arts_t_trainmiles", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainmilesCreatedon;

    @Column(name = "c_trainmiles_code", table = "arts_t_trainmiles", nullable = false, length = 10)
    @Basic
    private String cTrainmilesCode;

    @Column(name = "c_trainmiles_note", table = "arts_t_trainmiles", length = 100)
    @Basic
    private String cTrainmilesNote;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTrainmilesName() {
        return cTrainmilesName;
    }

    public void setcTrainmilesName(String cTrainmilesName) {
        this.cTrainmilesName = cTrainmilesName;
    }

    public Character getcTrainmilesStatus() {
        return cTrainmilesStatus;
    }

    public void setcTrainmilesStatus(Character cTrainmilesStatus) {
        this.cTrainmilesStatus = cTrainmilesStatus;
    }

    public String getcTrainmilesDomain() {
        return cTrainmilesDomain;
    }

    public void setcTrainmilesDomain(String cTrainmilesDomain) {
        this.cTrainmilesDomain = cTrainmilesDomain;
    }

    public String getcTrainmilesModifiedby() {
        return cTrainmilesModifiedby;
    }

    public void setcTrainmilesModifiedby(String cTrainmilesModifiedby) {
        this.cTrainmilesModifiedby = cTrainmilesModifiedby;
    }

    public Date getcTrainmilesModifiedon() {
        return cTrainmilesModifiedon;
    }

    public void setcTrainmilesModifiedon(Date cTrainmilesModifiedon) {
        this.cTrainmilesModifiedon = cTrainmilesModifiedon;
    }

    public String getcTrainmilesCreatedby() {
        return cTrainmilesCreatedby;
    }

    public void setcTrainmilesCreatedby(String cTrainmilesCreatedby) {
        this.cTrainmilesCreatedby = cTrainmilesCreatedby;
    }

    public Date getcTrainmilesCreatedon() {
        return cTrainmilesCreatedon;
    }

    public void setcTrainmilesCreatedon(Date cTrainmilesCreatedon) {
        this.cTrainmilesCreatedon = cTrainmilesCreatedon;
    }

    public String getcTrainmilesCode() {
        return cTrainmilesCode;
    }

    public void setcTrainmilesCode(String cTrainmilesCode) {
        this.cTrainmilesCode = cTrainmilesCode;
    }

    public String getcTrainmilesNote() {
        return cTrainmilesNote;
    }

    public void setcTrainmilesNote(String cTrainmilesNote) {
        this.cTrainmilesNote = cTrainmilesNote;
    }

    

}
