/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.trains;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_train")
public class Train {

    @Column(name = "c_train_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_train_name", table = "arts_t_train", nullable = false, length = 100)
    @Basic
    private String cTrainName;

    @Column(name = "c_train_status", table = "arts_t_train", nullable = false)
    @Basic
    private Character cTrainStatus;

    @Column(name = "c_train_domain", table = "arts_t_train", nullable = false, length = 36)
    @Basic
    private String cTrainDomain;

    @Column(name = "c_train_modifiedby", table = "arts_t_train", nullable = false, length = 36)
    @Basic
    private String cTrainModifiedby;

    @Column(name = "c_train_modifiedon", table = "arts_t_train", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainModifiedon;

    @Column(name = "c_train_createdby", table = "arts_t_train", nullable = false, length = 36)
    @Basic
    private String cTrainCreatedby;

    @Column(name = "c_train_createdon", table = "arts_t_train", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTrainName() {
        return cTrainName;
    }

    public void setcTrainName(String cTrainName) {
        this.cTrainName = cTrainName;
    }

    public Character getcTrainStatus() {
        return cTrainStatus;
    }

    public void setcTrainStatus(Character cTrainStatus) {
        this.cTrainStatus = cTrainStatus;
    }

    public String getcTrainDomain() {
        return cTrainDomain;
    }

    public void setcTrainDomain(String cTrainDomain) {
        this.cTrainDomain = cTrainDomain;
    }

    public String getcTrainModifiedby() {
        return cTrainModifiedby;
    }

    public void setcTrainModifiedby(String cTrainModifiedby) {
        this.cTrainModifiedby = cTrainModifiedby;
    }

    public Date getcTrainModifiedon() {
        return cTrainModifiedon;
    }

    public void setcTrainModifiedon(Date cTrainModifiedon) {
        this.cTrainModifiedon = cTrainModifiedon;
    }

    public String getcTrainCreatedby() {
        return cTrainCreatedby;
    }

    public void setcTrainCreatedby(String cTrainCreatedby) {
        this.cTrainCreatedby = cTrainCreatedby;
    }

    public Date getcTrainCreatedon() {
        return cTrainCreatedon;
    }

    public void setcTrainCreatedon(Date cTrainCreatedon) {
        this.cTrainCreatedon = cTrainCreatedon;
    }
    
    

}
