/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.trains;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_wagondet", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_wagon_id", "c_wagondet_col", "c_wagondet_row"})})
public class Wagondet implements Serializable {

    @Column(name = "c_wagondet_id", table = "arts_t_wagondet", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_wagondet_col", table = "arts_t_wagondet", nullable = false)
    @Basic
    private Character cWagondetCol;

    @Column(name = "c_wagon_id", table = "arts_t_wagondet", nullable = false, length = 36)
    @Basic
    private String cWagonId;

    @Column(name = "c_wagondet_status", table = "arts_t_wagondet", nullable = false)
    @Basic
    private Character cWagondetStatus;

    @Column(name = "c_wagondet_domain", table = "arts_t_wagondet", nullable = false, length = 36)
    @Basic
    private String cWagondetDomain;

    @Column(name = "c_wagondet_modifiedby", table = "arts_t_wagondet", nullable = false, length = 36)
    @Basic
    private String cWagondetModifiedby;

    @Column(name = "c_wagondet_modifiedon", table = "arts_t_wagondet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cWagondetModifiedon;

    @Column(name = "c_wagondet_row", table = "arts_t_wagondet", nullable = false)
    @Basic
    private short cWagondetRow;

    @Column(name = "c_wagondet_createdby", table = "arts_t_wagondet", nullable = false, length = 36)
    @Basic
    private String cWagondetCreatedby;

    @Column(name = "c_wagondet_createdon", table = "arts_t_wagondet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cWagondetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Character getcWagondetCol() {
        return cWagondetCol;
    }

    public void setcWagondetCol(Character cWagondetCol) {
        this.cWagondetCol = cWagondetCol;
    }

    public String getcWagonId() {
        return cWagonId;
    }

    public void setcWagonId(String cWagonId) {
        this.cWagonId = cWagonId;
    }

    public Character getcWagondetStatus() {
        return cWagondetStatus;
    }

    public void setcWagondetStatus(Character cWagondetStatus) {
        this.cWagondetStatus = cWagondetStatus;
    }

    public String getcWagondetDomain() {
        return cWagondetDomain;
    }

    public void setcWagondetDomain(String cWagondetDomain) {
        this.cWagondetDomain = cWagondetDomain;
    }

    public String getcWagondetModifiedby() {
        return cWagondetModifiedby;
    }

    public void setcWagondetModifiedby(String cWagondetModifiedby) {
        this.cWagondetModifiedby = cWagondetModifiedby;
    }

    public Date getcWagondetModifiedon() {
        return cWagondetModifiedon;
    }

    public void setcWagondetModifiedon(Date cWagondetModifiedon) {
        this.cWagondetModifiedon = cWagondetModifiedon;
    }

    public short getcWagondetRow() {
        return cWagondetRow;
    }

    public void setcWagondetRow(short cWagondetRow) {
        this.cWagondetRow = cWagondetRow;
    }

    public String getcWagondetCreatedby() {
        return cWagondetCreatedby;
    }

    public void setcWagondetCreatedby(String cWagondetCreatedby) {
        this.cWagondetCreatedby = cWagondetCreatedby;
    }

    public Date getcWagondetCreatedon() {
        return cWagondetCreatedon;
    }

    public void setcWagondetCreatedon(Date cWagondetCreatedon) {
        this.cWagondetCreatedon = cWagondetCreatedon;
    }
    
    
}
