/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_activitylog")
public class Activitylog implements Serializable {

    @Column(name = "c_activitylog_id", table = "arts_t_activitylog", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_activitylog_object", table = "arts_t_activitylog", nullable = false, length = 50)
    @Basic
    private String cActivitylogObject;

    @Column(name = "c_activitylog_objectid", table = "arts_t_activitylog", nullable = false, length = 36)
    @Basic
    private String cActivitylogObjectid;

    @Column(name = "c_activitylog_action", table = "arts_t_activitylog", nullable = false, length = 50)
    @Basic
    private String cActivitylogAction;

    @Column(name = "c_activitylog_date", table = "arts_t_activitylog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cActivitylogDate;

    @Column(name = "c_activitylog_value", table = "arts_t_activitylog", nullable = false, length = 2147483647)
    @Lob
    @Basic
    private String cActivitylogValue;

    @Column(name = "c_activitylog_domain", table = "arts_t_activitylog", nullable = false, length = 36)
    @Basic
    private String cActivitylogDomain;

    @Column(name = "c_user_id", table = "arts_t_activitylog", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_wslog_id", table = "arts_t_activitylog", length = 36)
    @Basic
    private String cWslogId;

    @Column(name = "c_unit_id", table = "arts_t_activitylog", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_activitylog_createdby", table = "arts_t_activitylog", nullable = false, length = 36)
    @Basic
    private String cActivitylogCreatedby;

    @Column(name = "c_activitylog_createdon", table = "arts_t_activitylog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cActivitylogCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcActivitylogObject() {
        return cActivitylogObject;
    }

    public void setcActivitylogObject(String cActivitylogObject) {
        this.cActivitylogObject = cActivitylogObject;
    }

    public String getcActivitylogObjectid() {
        return cActivitylogObjectid;
    }

    public void setcActivitylogObjectid(String cActivitylogObjectid) {
        this.cActivitylogObjectid = cActivitylogObjectid;
    }

    public String getcActivitylogAction() {
        return cActivitylogAction;
    }

    public void setcActivitylogAction(String cActivitylogAction) {
        this.cActivitylogAction = cActivitylogAction;
    }

    public Date getcActivitylogDate() {
        return cActivitylogDate;
    }

    public void setcActivitylogDate(Date cActivitylogDate) {
        this.cActivitylogDate = cActivitylogDate;
    }

    public String getcActivitylogValue() {
        return cActivitylogValue;
    }

    public void setcActivitylogValue(String cActivitylogValue) {
        this.cActivitylogValue = cActivitylogValue;
    }

    public String getcActivitylogDomain() {
        return cActivitylogDomain;
    }

    public void setcActivitylogDomain(String cActivitylogDomain) {
        this.cActivitylogDomain = cActivitylogDomain;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcWslogId() {
        return cWslogId;
    }

    public void setcWslogId(String cWslogId) {
        this.cWslogId = cWslogId;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public String getcActivitylogCreatedby() {
        return cActivitylogCreatedby;
    }

    public void setcActivitylogCreatedby(String cActivitylogCreatedby) {
        this.cActivitylogCreatedby = cActivitylogCreatedby;
    }

    public Date getcActivitylogCreatedon() {
        return cActivitylogCreatedon;
    }

    public void setcActivitylogCreatedon(Date cActivitylogCreatedon) {
        this.cActivitylogCreatedon = cActivitylogCreatedon;
    }
    
    
}
