/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_area", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_area_name", "c_area_domain"})})
public class Area implements Serializable {

    @Column(name = "c_area_id", table = "arts_t_area", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_area_bisnis", table = "arts_t_area", length = 50)
    @Basic
    private String cAreaBisnis;

    @Column(name = "c_area_name", table = "arts_t_area", nullable = false, length = 50)
    @Basic
    private String cAreaName;

    @Column(name = "c_area_status", table = "arts_t_area", nullable = false)
    @Basic
    private Character cAreaStatus;

    @Column(name = "c_area_domain", table = "arts_t_area", nullable = false, length = 36)
    @Basic
    private String cAreaDomain;

    @Column(name = "c_area_modifiedby", table = "arts_t_area", nullable = false, length = 36)
    @Basic
    private String cAreaModifiedby;

    @Column(name = "c_area_modifiedon", table = "arts_t_area", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAreaModifiedon;

    @Column(name = "c_area_createdby", table = "arts_t_area", nullable = false, length = 36)
    @Basic
    private String cAreaCreatedby;

    @Column(name = "c_area_createdon", table = "arts_t_area", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAreaCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcAreaBisnis() {
        return cAreaBisnis;
    }

    public void setcAreaBisnis(String cAreaBisnis) {
        this.cAreaBisnis = cAreaBisnis;
    }

    public String getcAreaName() {
        return cAreaName;
    }

    public void setcAreaName(String cAreaName) {
        this.cAreaName = cAreaName;
    }

    public Character getcAreaStatus() {
        return cAreaStatus;
    }

    public void setcAreaStatus(Character cAreaStatus) {
        this.cAreaStatus = cAreaStatus;
    }

    public String getcAreaDomain() {
        return cAreaDomain;
    }

    public void setcAreaDomain(String cAreaDomain) {
        this.cAreaDomain = cAreaDomain;
    }

    public String getcAreaModifiedby() {
        return cAreaModifiedby;
    }

    public void setcAreaModifiedby(String cAreaModifiedby) {
        this.cAreaModifiedby = cAreaModifiedby;
    }

    public Date getcAreaModifiedon() {
        return cAreaModifiedon;
    }

    public void setcAreaModifiedon(Date cAreaModifiedon) {
        this.cAreaModifiedon = cAreaModifiedon;
    }

    public String getcAreaCreatedby() {
        return cAreaCreatedby;
    }

    public void setcAreaCreatedby(String cAreaCreatedby) {
        this.cAreaCreatedby = cAreaCreatedby;
    }

    public Date getcAreaCreatedon() {
        return cAreaCreatedon;
    }

    public void setcAreaCreatedon(Date cAreaCreatedon) {
        this.cAreaCreatedon = cAreaCreatedon;
    }

    
}
