/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_cancellationdet", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_transactiondetid_cancelled"})})
public class Cancellationdet implements Serializable {

    @Column(name = "c_cancellationdet_id", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_cancellationdet_netamount", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    private long cCancellationdetNetamount;

    @Column(name = "c_cancellationdet_status", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    private Character cCancellationdetStatus;

    @Column(name = "c_cancellationdet_domain", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Basic
    private String cCancellationdetDomain;

    @Column(name = "c_cancellationdet_modifiedby", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Basic
    private String cCancellationdetModifiedby;

    @Column(name = "c_cancellationdet_modifiedon", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCancellationdetModifiedon;

    @Column(name = "c_cancellation_id", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Basic
    private String cCancellationId;

    @Column(name = "c_transactiondetid_cancelled", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Basic
    private String cTransactiondetidCancelled;

    @Column(name = "c_transactiondetid_new", table = "arts_t_cancellationdet", length = 36)
    @Basic
    private String cTransactiondetidNew;

    @Column(name = "c_cancellationdet_fee", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    private long cCancellationdetFee;

    @Column(name = "c_cancellationdet_diff", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    private long cCancellationdetDiff;

    @Column(name = "c_cancellationdet_amountticket", table = "arts_t_cancellationdet", scale = 2, precision = 11)
    @Basic
    private BigDecimal cCancellationdetAmountticket;

    @Column(name = "c_cancellationdet_createdby", table = "arts_t_cancellationdet", nullable = false, length = 36)
    @Basic
    private String cCancellationdetCreatedby;

    @Column(name = "c_cancellationdet_createdon", table = "arts_t_cancellationdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCancellationdetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getcCancellationdetNetamount() {
        return cCancellationdetNetamount;
    }

    public void setcCancellationdetNetamount(long cCancellationdetNetamount) {
        this.cCancellationdetNetamount = cCancellationdetNetamount;
    }

    public Character getcCancellationdetStatus() {
        return cCancellationdetStatus;
    }

    public void setcCancellationdetStatus(Character cCancellationdetStatus) {
        this.cCancellationdetStatus = cCancellationdetStatus;
    }

    public String getcCancellationdetDomain() {
        return cCancellationdetDomain;
    }

    public void setcCancellationdetDomain(String cCancellationdetDomain) {
        this.cCancellationdetDomain = cCancellationdetDomain;
    }

    public String getcCancellationdetModifiedby() {
        return cCancellationdetModifiedby;
    }

    public void setcCancellationdetModifiedby(String cCancellationdetModifiedby) {
        this.cCancellationdetModifiedby = cCancellationdetModifiedby;
    }

    public Date getcCancellationdetModifiedon() {
        return cCancellationdetModifiedon;
    }

    public void setcCancellationdetModifiedon(Date cCancellationdetModifiedon) {
        this.cCancellationdetModifiedon = cCancellationdetModifiedon;
    }

    public String getcCancellationId() {
        return cCancellationId;
    }

    public void setcCancellationId(String cCancellationId) {
        this.cCancellationId = cCancellationId;
    }

    public String getcTransactiondetidCancelled() {
        return cTransactiondetidCancelled;
    }

    public void setcTransactiondetidCancelled(String cTransactiondetidCancelled) {
        this.cTransactiondetidCancelled = cTransactiondetidCancelled;
    }

    public String getcTransactiondetidNew() {
        return cTransactiondetidNew;
    }

    public void setcTransactiondetidNew(String cTransactiondetidNew) {
        this.cTransactiondetidNew = cTransactiondetidNew;
    }

    public long getcCancellationdetFee() {
        return cCancellationdetFee;
    }

    public void setcCancellationdetFee(long cCancellationdetFee) {
        this.cCancellationdetFee = cCancellationdetFee;
    }

    public long getcCancellationdetDiff() {
        return cCancellationdetDiff;
    }

    public void setcCancellationdetDiff(long cCancellationdetDiff) {
        this.cCancellationdetDiff = cCancellationdetDiff;
    }

    public BigDecimal getcCancellationdetAmountticket() {
        return cCancellationdetAmountticket;
    }

    public void setcCancellationdetAmountticket(BigDecimal cCancellationdetAmountticket) {
        this.cCancellationdetAmountticket = cCancellationdetAmountticket;
    }

    public String getcCancellationdetCreatedby() {
        return cCancellationdetCreatedby;
    }

    public void setcCancellationdetCreatedby(String cCancellationdetCreatedby) {
        this.cCancellationdetCreatedby = cCancellationdetCreatedby;
    }

    public Date getcCancellationdetCreatedon() {
        return cCancellationdetCreatedon;
    }

    public void setcCancellationdetCreatedon(Date cCancellationdetCreatedon) {
        this.cCancellationdetCreatedon = cCancellationdetCreatedon;
    }

    

}
