/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_city", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_city_name", "c_province_id", "c_city_domain"})})
public class City implements Serializable {

    @Column(name = "c_city_id", table = "arts_t_city", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_city_name", table = "arts_t_city", nullable = false, length = 100)
    @Basic
    private String cCityName;

    @Column(name = "c_city_gmt", table = "arts_t_city", nullable = false)
    @Basic
    private double cCityGmt;

    @Column(name = "c_province_id", table = "arts_t_city", nullable = false, length = 36)
    @Basic
    private String cProvinceId;

    @Column(name = "c_city_status", table = "arts_t_city", nullable = false)
    @Basic
    private Character cCityStatus;

    @Column(name = "c_city_domain", table = "arts_t_city", nullable = false, length = 36)
    @Basic
    private String cCityDomain;

    @Column(name = "c_city_modifiedby", table = "arts_t_city", nullable = false, length = 36)
    @Basic
    private String cCityModifiedby;

    @Column(name = "c_city_modifiedon", table = "arts_t_city")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCityModifiedon;

    @Column(name = "c_city_createdby", table = "arts_t_city", nullable = false, length = 36)
    @Basic
    private String cCityCreatedby;

    @Column(name = "c_city_createdon", table = "arts_t_city", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCityCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcCityName() {
        return cCityName;
    }

    public void setcCityName(String cCityName) {
        this.cCityName = cCityName;
    }

    public double getcCityGmt() {
        return cCityGmt;
    }

    public void setcCityGmt(double cCityGmt) {
        this.cCityGmt = cCityGmt;
    }

    public String getcProvinceId() {
        return cProvinceId;
    }

    public void setcProvinceId(String cProvinceId) {
        this.cProvinceId = cProvinceId;
    }

    public Character getcCityStatus() {
        return cCityStatus;
    }

    public void setcCityStatus(Character cCityStatus) {
        this.cCityStatus = cCityStatus;
    }

    public String getcCityDomain() {
        return cCityDomain;
    }

    public void setcCityDomain(String cCityDomain) {
        this.cCityDomain = cCityDomain;
    }

    public String getcCityModifiedby() {
        return cCityModifiedby;
    }

    public void setcCityModifiedby(String cCityModifiedby) {
        this.cCityModifiedby = cCityModifiedby;
    }

    public Date getcCityModifiedon() {
        return cCityModifiedon;
    }

    public void setcCityModifiedon(Date cCityModifiedon) {
        this.cCityModifiedon = cCityModifiedon;
    }

    public String getcCityCreatedby() {
        return cCityCreatedby;
    }

    public void setcCityCreatedby(String cCityCreatedby) {
        this.cCityCreatedby = cCityCreatedby;
    }

    public Date getcCityCreatedon() {
        return cCityCreatedon;
    }

    public void setcCityCreatedon(Date cCityCreatedon) {
        this.cCityCreatedon = cCityCreatedon;
    }



}
