/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_grpreservationpsg")
public class Grpreservationpsg implements Serializable {

    @Column(name = "c_grpreservationpsg_id", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_grpreservationpsg_psgname", table = "arts_t_grpreservationpsg", nullable = false, length = 100)
    @Basic
    private String cGrpreservationpsgPsgname;

    @Column(name = "c_grpreservationpsg_infantname", table = "arts_t_grpreservationpsg", length = 100)
    @Basic
    private String cGrpreservationpsgInfantname;

    @Column(name = "c_grpreservationpsg_psgid", table = "arts_t_grpreservationpsg", nullable = false, length = 50)
    @Basic
    private String cGrpreservationpsgPsgid;

    @Column(name = "c_grpreservationdet_id", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Basic
    private String cGrpreservationdetId;

    @Column(name = "c_grpreservationpsg_status", table = "arts_t_grpreservationpsg", nullable = false)
    @Basic
    private Character cGrpreservationpsgStatus;

    @Column(name = "c_grpreservationpsg_domain", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Basic
    private String cGrpreservationpsgDomain;

    @Column(name = "c_grpreservationpsg_modifiedby", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Basic
    private String cGrpreservationpsgModifiedby;

    @Column(name = "c_grpreservationpsg_modifiedon", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Basic
    private String cGrpreservationpsgModifiedon;

    @Column(name = "c_grpreservationpsg_createdby", table = "arts_t_grpreservationpsg", nullable = false, length = 36)
    @Basic
    private String cGrpreservationpsgCreatedby;

    @Column(name = "c_grpreservationpsg_createdon", table = "arts_t_grpreservationpsg", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cGrpreservationpsgCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcGrpreservationpsgPsgname() {
        return cGrpreservationpsgPsgname;
    }

    public void setcGrpreservationpsgPsgname(String cGrpreservationpsgPsgname) {
        this.cGrpreservationpsgPsgname = cGrpreservationpsgPsgname;
    }

    public String getcGrpreservationpsgInfantname() {
        return cGrpreservationpsgInfantname;
    }

    public void setcGrpreservationpsgInfantname(String cGrpreservationpsgInfantname) {
        this.cGrpreservationpsgInfantname = cGrpreservationpsgInfantname;
    }

    public String getcGrpreservationpsgPsgid() {
        return cGrpreservationpsgPsgid;
    }

    public void setcGrpreservationpsgPsgid(String cGrpreservationpsgPsgid) {
        this.cGrpreservationpsgPsgid = cGrpreservationpsgPsgid;
    }

    public String getcGrpreservationdetId() {
        return cGrpreservationdetId;
    }

    public void setcGrpreservationdetId(String cGrpreservationdetId) {
        this.cGrpreservationdetId = cGrpreservationdetId;
    }

    public Character getcGrpreservationpsgStatus() {
        return cGrpreservationpsgStatus;
    }

    public void setcGrpreservationpsgStatus(Character cGrpreservationpsgStatus) {
        this.cGrpreservationpsgStatus = cGrpreservationpsgStatus;
    }

    public String getcGrpreservationpsgDomain() {
        return cGrpreservationpsgDomain;
    }

    public void setcGrpreservationpsgDomain(String cGrpreservationpsgDomain) {
        this.cGrpreservationpsgDomain = cGrpreservationpsgDomain;
    }

    public String getcGrpreservationpsgModifiedby() {
        return cGrpreservationpsgModifiedby;
    }

    public void setcGrpreservationpsgModifiedby(String cGrpreservationpsgModifiedby) {
        this.cGrpreservationpsgModifiedby = cGrpreservationpsgModifiedby;
    }

    public String getcGrpreservationpsgModifiedon() {
        return cGrpreservationpsgModifiedon;
    }

    public void setcGrpreservationpsgModifiedon(String cGrpreservationpsgModifiedon) {
        this.cGrpreservationpsgModifiedon = cGrpreservationpsgModifiedon;
    }

    public String getcGrpreservationpsgCreatedby() {
        return cGrpreservationpsgCreatedby;
    }

    public void setcGrpreservationpsgCreatedby(String cGrpreservationpsgCreatedby) {
        this.cGrpreservationpsgCreatedby = cGrpreservationpsgCreatedby;
    }

    public Date getcGrpreservationpsgCreatedon() {
        return cGrpreservationpsgCreatedon;
    }

    public void setcGrpreservationpsgCreatedon(Date cGrpreservationpsgCreatedon) {
        this.cGrpreservationpsgCreatedon = cGrpreservationpsgCreatedon;
    }
    
    

}
