/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_hobby")
public class Hobby {

    @Column(name = "c_hobby_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_hobby_code", table = "arts_t_hobby", nullable = false, length = 20)
    @Basic
    private String cHobbyCode;

    @Column(name = "c_hobby_name", table = "arts_t_hobby", nullable = false, length = 50)
    @Basic
    private String cHobbyName;

    @Column(name = "c_hobby_note", table = "arts_t_hobby", length = 100)
    @Basic
    private String cHobbyNote;

    @Column(name = "c_hobby_status", table = "arts_t_hobby", nullable = false)
    @Basic
    private Character cHobbyStatus;

    @Column(name = "c_hobby_domain", table = "arts_t_hobby", nullable = false, length = 36)
    @Basic
    private String cHobbyDomain;

    @Column(name = "c_hobby_createdby", table = "arts_t_hobby", nullable = false, length = 36)
    @Basic
    private String cHobbyCreatedby;

    @Column(name = "c_hobby_createdon", table = "arts_t_hobby", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cHobbyCreatedon;

    @Column(name = "c_hobby_modifiedby", table = "arts_t_hobby", nullable = false, length = 36)
    @Basic
    private String cHobbyModifiedby;

    @Column(name = "c_hobby_modifiedon", table = "arts_t_hobby", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cHobbyModifiedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcHobbyCode() {
        return cHobbyCode;
    }

    public void setcHobbyCode(String cHobbyCode) {
        this.cHobbyCode = cHobbyCode;
    }

    public String getcHobbyName() {
        return cHobbyName;
    }

    public void setcHobbyName(String cHobbyName) {
        this.cHobbyName = cHobbyName;
    }

    public String getcHobbyNote() {
        return cHobbyNote;
    }

    public void setcHobbyNote(String cHobbyNote) {
        this.cHobbyNote = cHobbyNote;
    }

    public Character getcHobbyStatus() {
        return cHobbyStatus;
    }

    public void setcHobbyStatus(Character cHobbyStatus) {
        this.cHobbyStatus = cHobbyStatus;
    }

    public String getcHobbyDomain() {
        return cHobbyDomain;
    }

    public void setcHobbyDomain(String cHobbyDomain) {
        this.cHobbyDomain = cHobbyDomain;
    }

    public String getcHobbyCreatedby() {
        return cHobbyCreatedby;
    }

    public void setcHobbyCreatedby(String cHobbyCreatedby) {
        this.cHobbyCreatedby = cHobbyCreatedby;
    }

    public Date getcHobbyCreatedon() {
        return cHobbyCreatedon;
    }

    public void setcHobbyCreatedon(Date cHobbyCreatedon) {
        this.cHobbyCreatedon = cHobbyCreatedon;
    }

    public String getcHobbyModifiedby() {
        return cHobbyModifiedby;
    }

    public void setcHobbyModifiedby(String cHobbyModifiedby) {
        this.cHobbyModifiedby = cHobbyModifiedby;
    }

    public Date getcHobbyModifiedon() {
        return cHobbyModifiedon;
    }

    public void setcHobbyModifiedon(Date cHobbyModifiedon) {
        this.cHobbyModifiedon = cHobbyModifiedon;
    }
    
    

}
