/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_inventory")
public class Inventory implements Serializable {

    @Column(name = "c_inventory_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_schedule_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cScheduleId;

    @Column(name = "c_inventory_noka", table = "arts_t_inventory", nullable = false, length = 50)
    @Basic
    private String cInventoryNoka;

    @Column(name = "c_trip_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_inventory_tripdate", table = "arts_t_inventory", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cInventoryTripdate;

    @Column(name = "c_stop_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cStopId;

    @Column(name = "c_inventory_stasiuncode", table = "arts_t_inventory", nullable = false, length = 10)
    @Basic
    private String cInventoryStasiuncode;

    @Column(name = "c_inventory_stoporder", table = "arts_t_inventory", nullable = false)
    @Basic
    private int cInventoryStoporder;

    @Column(name = "c_stamformdet_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cStamformdetId;

    @Column(name = "c_inventory_sfdcode", table = "arts_t_inventory", nullable = false, length = 10)
    @Basic
    private String cInventorySfdcode;

    @Column(name = "c_inventory_sfdorder", table = "arts_t_inventory", nullable = false)
    @Basic
    private int cInventorySfdorder;

    @Column(name = "c_wagondet_id", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cWagondetId;

    @Column(name = "c_inventory_wgdrow", table = "arts_t_inventory", nullable = false)
    @Basic
    private int cInventoryWgdrow;

    @Column(name = "c_inventory_wgdcol", table = "arts_t_inventory", nullable = false, length = 2)
    @Basic
    private String cInventoryWgdcol;

    @Column(name = "c_subclass_id", table = "arts_t_inventory", length = 36)
    @Basic
    private String cSubclassId;

    @Column(name = "c_inventory_subclasscode", table = "arts_t_inventory", length = 10)
    @Basic
    private String cInventorySubclasscode;

    @Column(name = "c_inventory_bookstat", table = "arts_t_inventory", nullable = false)
    @Basic
    private Character cInventoryBookstat;

    @Column(name = "c_inventory_status", table = "arts_t_inventory", nullable = false)
    @Basic
    private Character cInventoryStatus;

    @Column(name = "c_inventory_domain", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cInventoryDomain;

    @Column(name = "c_inventory_modifiedby", table = "arts_t_inventory", nullable = false, length = 36)
    @Basic
    private String cInventoryModifiedby;

    @Column(name = "c_inventory_modifiedon", table = "arts_t_inventory", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cInventoryModifiedon;

    @Column(name = "c_inventory_cols", table = "arts_t_inventory")
    @Basic
    private Short cInventoryCols;

    @Column(name = "c_inventory_createdby", table = "arts_t_inventory", length = 36)
    @Basic
    private String cInventoryCreatedby;

    @Column(name = "c_inventory_createdon", table = "arts_t_inventory")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cInventoryCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcScheduleId() {
        return cScheduleId;
    }

    public void setcScheduleId(String cScheduleId) {
        this.cScheduleId = cScheduleId;
    }

    public String getcInventoryNoka() {
        return cInventoryNoka;
    }

    public void setcInventoryNoka(String cInventoryNoka) {
        this.cInventoryNoka = cInventoryNoka;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public Date getcInventoryTripdate() {
        return cInventoryTripdate;
    }

    public void setcInventoryTripdate(Date cInventoryTripdate) {
        this.cInventoryTripdate = cInventoryTripdate;
    }

    public String getcStopId() {
        return cStopId;
    }

    public void setcStopId(String cStopId) {
        this.cStopId = cStopId;
    }

    public String getcInventoryStasiuncode() {
        return cInventoryStasiuncode;
    }

    public void setcInventoryStasiuncode(String cInventoryStasiuncode) {
        this.cInventoryStasiuncode = cInventoryStasiuncode;
    }

    public int getcInventoryStoporder() {
        return cInventoryStoporder;
    }

    public void setcInventoryStoporder(int cInventoryStoporder) {
        this.cInventoryStoporder = cInventoryStoporder;
    }

    public String getcStamformdetId() {
        return cStamformdetId;
    }

    public void setcStamformdetId(String cStamformdetId) {
        this.cStamformdetId = cStamformdetId;
    }

    public String getcInventorySfdcode() {
        return cInventorySfdcode;
    }

    public void setcInventorySfdcode(String cInventorySfdcode) {
        this.cInventorySfdcode = cInventorySfdcode;
    }

    public int getcInventorySfdorder() {
        return cInventorySfdorder;
    }

    public void setcInventorySfdorder(int cInventorySfdorder) {
        this.cInventorySfdorder = cInventorySfdorder;
    }

    public String getcWagondetId() {
        return cWagondetId;
    }

    public void setcWagondetId(String cWagondetId) {
        this.cWagondetId = cWagondetId;
    }

    public int getcInventoryWgdrow() {
        return cInventoryWgdrow;
    }

    public void setcInventoryWgdrow(int cInventoryWgdrow) {
        this.cInventoryWgdrow = cInventoryWgdrow;
    }

    public String getcInventoryWgdcol() {
        return cInventoryWgdcol;
    }

    public void setcInventoryWgdcol(String cInventoryWgdcol) {
        this.cInventoryWgdcol = cInventoryWgdcol;
    }

    public String getcSubclassId() {
        return cSubclassId;
    }

    public void setcSubclassId(String cSubclassId) {
        this.cSubclassId = cSubclassId;
    }

    public String getcInventorySubclasscode() {
        return cInventorySubclasscode;
    }

    public void setcInventorySubclasscode(String cInventorySubclasscode) {
        this.cInventorySubclasscode = cInventorySubclasscode;
    }

    public Character getcInventoryBookstat() {
        return cInventoryBookstat;
    }

    public void setcInventoryBookstat(Character cInventoryBookstat) {
        this.cInventoryBookstat = cInventoryBookstat;
    }

    public Character getcInventoryStatus() {
        return cInventoryStatus;
    }

    public void setcInventoryStatus(Character cInventoryStatus) {
        this.cInventoryStatus = cInventoryStatus;
    }

    public String getcInventoryDomain() {
        return cInventoryDomain;
    }

    public void setcInventoryDomain(String cInventoryDomain) {
        this.cInventoryDomain = cInventoryDomain;
    }

    public String getcInventoryModifiedby() {
        return cInventoryModifiedby;
    }

    public void setcInventoryModifiedby(String cInventoryModifiedby) {
        this.cInventoryModifiedby = cInventoryModifiedby;
    }

    public Date getcInventoryModifiedon() {
        return cInventoryModifiedon;
    }

    public void setcInventoryModifiedon(Date cInventoryModifiedon) {
        this.cInventoryModifiedon = cInventoryModifiedon;
    }

    public Short getcInventoryCols() {
        return cInventoryCols;
    }

    public void setcInventoryCols(Short cInventoryCols) {
        this.cInventoryCols = cInventoryCols;
    }

    public String getcInventoryCreatedby() {
        return cInventoryCreatedby;
    }

    public void setcInventoryCreatedby(String cInventoryCreatedby) {
        this.cInventoryCreatedby = cInventoryCreatedby;
    }

    public Date getcInventoryCreatedon() {
        return cInventoryCreatedon;
    }

    public void setcInventoryCreatedon(Date cInventoryCreatedon) {
        this.cInventoryCreatedon = cInventoryCreatedon;
    }
    
    

}
