/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_ip", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_ip_ip", "c_stasiun_id"})})
public class Ip implements Serializable {

    @Column(name = "c_ip_id", table = "arts_t_ip", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_ip_ip", table = "arts_t_ip", nullable = false, length = 50)
    @Basic
    private String cIpIp;

    @Column(name = "c_ip_name", table = "arts_t_ip", length = 100)
    @Basic
    private String cIpName;

    @Column(name = "c_ip_status", table = "arts_t_ip", nullable = false)
    @Basic
    private Character cIpStatus;

    @Column(name = "c_ip_domain", table = "arts_t_ip", nullable = false, length = 36)
    @Basic
    private String cIpDomain;

    @Column(name = "c_ip_modifiedby", table = "arts_t_ip", nullable = false, length = 36)
    @Basic
    private String cIpModifiedby;

    @Column(name = "c_ip_modifiedon", table = "arts_t_ip", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cIpModifiedon;

    @Column(name = "c_stasiun_id", table = "arts_t_ip", nullable = false, length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_ip_createdby", table = "arts_t_ip", nullable = false, length = 36)
    @Basic
    private String cIpCreatedby;

    @Column(name = "c_ip_createdon", table = "arts_t_ip", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cIpCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcIpIp() {
        return cIpIp;
    }

    public void setcIpIp(String cIpIp) {
        this.cIpIp = cIpIp;
    }

    public String getcIpName() {
        return cIpName;
    }

    public void setcIpName(String cIpName) {
        this.cIpName = cIpName;
    }

    public Character getcIpStatus() {
        return cIpStatus;
    }

    public void setcIpStatus(Character cIpStatus) {
        this.cIpStatus = cIpStatus;
    }

    public String getcIpDomain() {
        return cIpDomain;
    }

    public void setcIpDomain(String cIpDomain) {
        this.cIpDomain = cIpDomain;
    }

    public String getcIpModifiedby() {
        return cIpModifiedby;
    }

    public void setcIpModifiedby(String cIpModifiedby) {
        this.cIpModifiedby = cIpModifiedby;
    }

    public Date getcIpModifiedon() {
        return cIpModifiedon;
    }

    public void setcIpModifiedon(Date cIpModifiedon) {
        this.cIpModifiedon = cIpModifiedon;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public String getcIpCreatedby() {
        return cIpCreatedby;
    }

    public void setcIpCreatedby(String cIpCreatedby) {
        this.cIpCreatedby = cIpCreatedby;
    }

    public Date getcIpCreatedon() {
        return cIpCreatedon;
    }

    public void setcIpCreatedon(Date cIpCreatedon) {
        this.cIpCreatedon = cIpCreatedon;
    }
    
    

}
