/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_loginlog")
public class Loginlog implements Serializable {

    @Column(name = "c_loginlog_id", table = "arts_t_loginlog", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_loginlog_time", table = "arts_t_loginlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cLoginlogTime;

    @Column(name = "c_loginlog_ip", table = "arts_t_loginlog", nullable = false, length = 36)
    @Basic
    private String cLoginlogIp;

    @Column(name = "c_loginlog_username", table = "arts_t_loginlog", nullable = false, length = 100)
    @Basic
    private String cLoginlogUsername;

    @Column(name = "c_loginlog_status", table = "arts_t_loginlog", nullable = false)
    @Basic
    private Character cLoginlogStatus;

    @Column(name = "c_loginlog_domain", table = "arts_t_loginlog", nullable = false, length = 36)
    @Basic
    private String cLoginlogDomain;

    @Column(name = "c_user_id", table = "arts_t_loginlog", length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_loginlog_note", table = "arts_t_loginlog", length = 300)
    @Basic
    private String cLoginlogNote;

    @Column(name = "c_loginlog_createdby", table = "arts_t_loginlog", nullable = false, length = 36)
    @Basic
    private String cLoginlogCreatedby;

    @Column(name = "c_loginlog_createdon", table = "arts_t_loginlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cLoginlogCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcLoginlogTime() {
        return cLoginlogTime;
    }

    public void setcLoginlogTime(Date cLoginlogTime) {
        this.cLoginlogTime = cLoginlogTime;
    }

    public String getcLoginlogIp() {
        return cLoginlogIp;
    }

    public void setcLoginlogIp(String cLoginlogIp) {
        this.cLoginlogIp = cLoginlogIp;
    }

    public String getcLoginlogUsername() {
        return cLoginlogUsername;
    }

    public void setcLoginlogUsername(String cLoginlogUsername) {
        this.cLoginlogUsername = cLoginlogUsername;
    }

    public Character getcLoginlogStatus() {
        return cLoginlogStatus;
    }

    public void setcLoginlogStatus(Character cLoginlogStatus) {
        this.cLoginlogStatus = cLoginlogStatus;
    }

    public String getcLoginlogDomain() {
        return cLoginlogDomain;
    }

    public void setcLoginlogDomain(String cLoginlogDomain) {
        this.cLoginlogDomain = cLoginlogDomain;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcLoginlogNote() {
        return cLoginlogNote;
    }

    public void setcLoginlogNote(String cLoginlogNote) {
        this.cLoginlogNote = cLoginlogNote;
    }

    public String getcLoginlogCreatedby() {
        return cLoginlogCreatedby;
    }

    public void setcLoginlogCreatedby(String cLoginlogCreatedby) {
        this.cLoginlogCreatedby = cLoginlogCreatedby;
    }

    public Date getcLoginlogCreatedon() {
        return cLoginlogCreatedon;
    }

    public void setcLoginlogCreatedon(Date cLoginlogCreatedon) {
        this.cLoginlogCreatedon = cLoginlogCreatedon;
    }
    
    
}
