/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_memshiptype")
public class Memshiptype implements Serializable {

    @Column(name = "c_memshiptype_id", table = "arts_t_memshiptype", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_memshiptype_name", table = "arts_t_memshiptype", nullable = false, length = 200)
    @Basic
    private String cMemshiptypeName;

    @Column(name = "c_memshiptype_minvalue", table = "arts_t_memshiptype", nullable = false)
    @Basic
    private double cMemshiptypeMinvalue;

    @Column(name = "c_memshiptype_maxvalue", table = "arts_t_memshiptype", nullable = false)
    @Basic
    private double cMemshiptypeMaxvalue;

    @Column(name = "c_memshiptype_startdate", table = "arts_t_memshiptype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemshiptypeStartdate;

    @Column(name = "c_memshiptype_enddate", table = "arts_t_memshiptype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemshiptypeEnddate;

    @Column(name = "c_memshiptype_status", table = "arts_t_memshiptype", nullable = false)
    @Basic
    private Character cMemshiptypeStatus;

    @Column(name = "c_memshiptype_domain", table = "arts_t_memshiptype", nullable = false, length = 36)
    @Basic
    private String cMemshiptypeDomain;

    @Column(name = "c_memshiptype_modifiedby", table = "arts_t_memshiptype", nullable = false, length = 36)
    @Basic
    private String cMemshiptypeModifiedby;

    @Column(name = "c_memshiptype_modifiedon", table = "arts_t_memshiptype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemshiptypeModifiedon;

    @Column(name = "c_memshiptype_multiplier", table = "arts_t_memshiptype", nullable = false, scale = 2, precision = 5)
    @Basic
    private BigDecimal cMemshiptypeMultiplier;

    @Column(name = "c_memshiptype_createdby", table = "arts_t_memshiptype", nullable = false, length = 36)
    @Basic
    private String cMemshiptypeCreatedby;

    @Column(name = "c_memshiptype_createdon", table = "arts_t_memshiptype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cMemshiptypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcMemshiptypeName() {
        return cMemshiptypeName;
    }

    public void setcMemshiptypeName(String cMemshiptypeName) {
        this.cMemshiptypeName = cMemshiptypeName;
    }

    public double getcMemshiptypeMinvalue() {
        return cMemshiptypeMinvalue;
    }

    public void setcMemshiptypeMinvalue(double cMemshiptypeMinvalue) {
        this.cMemshiptypeMinvalue = cMemshiptypeMinvalue;
    }

    public double getcMemshiptypeMaxvalue() {
        return cMemshiptypeMaxvalue;
    }

    public void setcMemshiptypeMaxvalue(double cMemshiptypeMaxvalue) {
        this.cMemshiptypeMaxvalue = cMemshiptypeMaxvalue;
    }

    public Date getcMemshiptypeStartdate() {
        return cMemshiptypeStartdate;
    }

    public void setcMemshiptypeStartdate(Date cMemshiptypeStartdate) {
        this.cMemshiptypeStartdate = cMemshiptypeStartdate;
    }

    public Date getcMemshiptypeEnddate() {
        return cMemshiptypeEnddate;
    }

    public void setcMemshiptypeEnddate(Date cMemshiptypeEnddate) {
        this.cMemshiptypeEnddate = cMemshiptypeEnddate;
    }

    public Character getcMemshiptypeStatus() {
        return cMemshiptypeStatus;
    }

    public void setcMemshiptypeStatus(Character cMemshiptypeStatus) {
        this.cMemshiptypeStatus = cMemshiptypeStatus;
    }

    public String getcMemshiptypeDomain() {
        return cMemshiptypeDomain;
    }

    public void setcMemshiptypeDomain(String cMemshiptypeDomain) {
        this.cMemshiptypeDomain = cMemshiptypeDomain;
    }

    public String getcMemshiptypeModifiedby() {
        return cMemshiptypeModifiedby;
    }

    public void setcMemshiptypeModifiedby(String cMemshiptypeModifiedby) {
        this.cMemshiptypeModifiedby = cMemshiptypeModifiedby;
    }

    public Date getcMemshiptypeModifiedon() {
        return cMemshiptypeModifiedon;
    }

    public void setcMemshiptypeModifiedon(Date cMemshiptypeModifiedon) {
        this.cMemshiptypeModifiedon = cMemshiptypeModifiedon;
    }

    public BigDecimal getcMemshiptypeMultiplier() {
        return cMemshiptypeMultiplier;
    }

    public void setcMemshiptypeMultiplier(BigDecimal cMemshiptypeMultiplier) {
        this.cMemshiptypeMultiplier = cMemshiptypeMultiplier;
    }

    public String getcMemshiptypeCreatedby() {
        return cMemshiptypeCreatedby;
    }

    public void setcMemshiptypeCreatedby(String cMemshiptypeCreatedby) {
        this.cMemshiptypeCreatedby = cMemshiptypeCreatedby;
    }

    public Date getcMemshiptypeCreatedon() {
        return cMemshiptypeCreatedon;
    }

    public void setcMemshiptypeCreatedon(Date cMemshiptypeCreatedon) {
        this.cMemshiptypeCreatedon = cMemshiptypeCreatedon;
    }
    
    
}
