/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_parameter", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_parameter_code"})})
public class Parameter implements Serializable {

    @Column(name = "c_parameter_id", table = "arts_t_parameter", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_parameter_code", table = "arts_t_parameter", nullable = false, length = 100)
    @Basic
    private String cParameterCode;

    @Column(name = "c_parameter_name", table = "arts_t_parameter", nullable = false, length = 200)
    @Basic
    private String cParameterName;

    @Column(name = "c_parameter_valtype", table = "arts_t_parameter", nullable = false, length = 50)
    @Basic
    private String cParameterValtype;

    @Column(name = "c_parameter_value", table = "arts_t_parameter", nullable = false, length = 1000)
    @Basic
    private String cParameterValue;

    @Column(name = "c_parameter_status", table = "arts_t_parameter", nullable = false)
    @Basic
    private Character cParameterStatus;

    @Column(name = "c_parameter_domain", table = "arts_t_parameter", nullable = false, length = 36)
    @Basic
    private String cParameterDomain;

    @Column(name = "c_parameter_modifiedby", table = "arts_t_parameter", nullable = false, length = 36)
    @Basic
    private String cParameterModifiedby;

    @Column(name = "c_parameter_modifiedon", table = "arts_t_parameter", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cParameterModifiedon;

    @Column(name = "c_parameter_startdate", table = "arts_t_parameter", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cParameterStartdate;

    @Column(name = "c_parameter_enddate", table = "arts_t_parameter", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cParameterEnddate;

    @Column(name = "c_parameter_createdby", table = "arts_t_parameter", nullable = false, length = 36)
    @Basic
    private String cParameterCreatedby;

    @Column(name = "c_parameter_createdon", table = "arts_t_parameter", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cParameterCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcParameterCode() {
        return cParameterCode;
    }

    public void setcParameterCode(String cParameterCode) {
        this.cParameterCode = cParameterCode;
    }

    public String getcParameterName() {
        return cParameterName;
    }

    public void setcParameterName(String cParameterName) {
        this.cParameterName = cParameterName;
    }

    public String getcParameterValtype() {
        return cParameterValtype;
    }

    public void setcParameterValtype(String cParameterValtype) {
        this.cParameterValtype = cParameterValtype;
    }

    public String getcParameterValue() {
        return cParameterValue;
    }

    public void setcParameterValue(String cParameterValue) {
        this.cParameterValue = cParameterValue;
    }

    public Character getcParameterStatus() {
        return cParameterStatus;
    }

    public void setcParameterStatus(Character cParameterStatus) {
        this.cParameterStatus = cParameterStatus;
    }

    public String getcParameterDomain() {
        return cParameterDomain;
    }

    public void setcParameterDomain(String cParameterDomain) {
        this.cParameterDomain = cParameterDomain;
    }

    public String getcParameterModifiedby() {
        return cParameterModifiedby;
    }

    public void setcParameterModifiedby(String cParameterModifiedby) {
        this.cParameterModifiedby = cParameterModifiedby;
    }

    public Date getcParameterModifiedon() {
        return cParameterModifiedon;
    }

    public void setcParameterModifiedon(Date cParameterModifiedon) {
        this.cParameterModifiedon = cParameterModifiedon;
    }

    public Date getcParameterStartdate() {
        return cParameterStartdate;
    }

    public void setcParameterStartdate(Date cParameterStartdate) {
        this.cParameterStartdate = cParameterStartdate;
    }

    public Date getcParameterEnddate() {
        return cParameterEnddate;
    }

    public void setcParameterEnddate(Date cParameterEnddate) {
        this.cParameterEnddate = cParameterEnddate;
    }

    public String getcParameterCreatedby() {
        return cParameterCreatedby;
    }

    public void setcParameterCreatedby(String cParameterCreatedby) {
        this.cParameterCreatedby = cParameterCreatedby;
    }

    public Date getcParameterCreatedon() {
        return cParameterCreatedon;
    }

    public void setcParameterCreatedon(Date cParameterCreatedon) {
        this.cParameterCreatedon = cParameterCreatedon;
    }
    
    
}
