/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_ratedetail", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_rate_id", "c_ratetype_id"})})
public class Ratedetail implements Serializable {

    @Column(name = "c_ratedetail_id", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_ratedetail_amount", table = "arts_t_ratedetail", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cRatedetailAmount;

    @Column(name = "c_rate_id", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Basic
    private String cRateId;

    @Column(name = "c_ratedetail_status", table = "arts_t_ratedetail", nullable = false)
    @Basic
    private Character cRatedetailStatus;

    @Column(name = "c_ratedetail_domain", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Basic
    private String cRatedetailDomain;

    @Column(name = "c_ratedetail_modifiedby", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Basic
    private String cRatedetailModifiedby;

    @Column(name = "c_ratedetail_modifiedon", table = "arts_t_ratedetail", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRatedetailModifiedon;

    @Column(name = "c_ratetype_id", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Basic
    private String cRatetypeId;

    @Column(name = "c_ratedetail_createdby", table = "arts_t_ratedetail", nullable = false, length = 36)
    @Basic
    private String cRatedetailCreatedby;

    @Column(name = "c_ratedetail_createdon", table = "arts_t_ratedetail", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRatedetailCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public BigDecimal getcRatedetailAmount() {
        return cRatedetailAmount;
    }

    public void setcRatedetailAmount(BigDecimal cRatedetailAmount) {
        this.cRatedetailAmount = cRatedetailAmount;
    }

    public String getcRateId() {
        return cRateId;
    }

    public void setcRateId(String cRateId) {
        this.cRateId = cRateId;
    }

    public Character getcRatedetailStatus() {
        return cRatedetailStatus;
    }

    public void setcRatedetailStatus(Character cRatedetailStatus) {
        this.cRatedetailStatus = cRatedetailStatus;
    }

    public String getcRatedetailDomain() {
        return cRatedetailDomain;
    }

    public void setcRatedetailDomain(String cRatedetailDomain) {
        this.cRatedetailDomain = cRatedetailDomain;
    }

    public String getcRatedetailModifiedby() {
        return cRatedetailModifiedby;
    }

    public void setcRatedetailModifiedby(String cRatedetailModifiedby) {
        this.cRatedetailModifiedby = cRatedetailModifiedby;
    }

    public Date getcRatedetailModifiedon() {
        return cRatedetailModifiedon;
    }

    public void setcRatedetailModifiedon(Date cRatedetailModifiedon) {
        this.cRatedetailModifiedon = cRatedetailModifiedon;
    }

    public String getcRatetypeId() {
        return cRatetypeId;
    }

    public void setcRatetypeId(String cRatetypeId) {
        this.cRatetypeId = cRatetypeId;
    }

    public String getcRatedetailCreatedby() {
        return cRatedetailCreatedby;
    }

    public void setcRatedetailCreatedby(String cRatedetailCreatedby) {
        this.cRatedetailCreatedby = cRatedetailCreatedby;
    }

    public Date getcRatedetailCreatedon() {
        return cRatedetailCreatedon;
    }

    public void setcRatedetailCreatedon(Date cRatedetailCreatedon) {
        this.cRatedetailCreatedon = cRatedetailCreatedon;
    }
    
    
}
