/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_stamformdet")
public class Stamformdet implements Serializable {

    @Column(name = "c_stamformdet_id", table = "arts_t_stamformdet", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_stamformdet_order", table = "arts_t_stamformdet", nullable = false)
    @Basic
    private long cStamformdetOrder;

    @Column(name = "c_stamformdet_status", table = "arts_t_stamformdet", nullable = false)
    @Basic
    private Character cStamformdetStatus;

    @Column(name = "c_stamformdet_domain", table = "arts_t_stamformdet", nullable = false, length = 36)
    @Basic
    private String cStamformdetDomain;

    @Column(name = "c_stamformdet_modifiedby", table = "arts_t_stamformdet", nullable = false, length = 36)
    @Basic
    private String cStamformdetModifiedby;

    @Column(name = "c_stamformdet_modifiedon", table = "arts_t_stamformdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cStamformdetModifiedon;

    @Column(name = "c_wagon_id", table = "arts_t_stamformdet", nullable = false, length = 36)
    @Basic
    private String cWagonId;

    @Column(name = "c_trip_id", table = "arts_t_stamformdet", length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_stamformdet_createdby", table = "arts_t_stamformdet", nullable = false, length = 36)
    @Basic
    private String cStamformdetCreatedby;

    @Column(name = "c_stamformdet_createdon", table = "arts_t_stamformdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cStamformdetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getcStamformdetOrder() {
        return cStamformdetOrder;
    }

    public void setcStamformdetOrder(long cStamformdetOrder) {
        this.cStamformdetOrder = cStamformdetOrder;
    }

    public Character getcStamformdetStatus() {
        return cStamformdetStatus;
    }

    public void setcStamformdetStatus(Character cStamformdetStatus) {
        this.cStamformdetStatus = cStamformdetStatus;
    }

    public String getcStamformdetDomain() {
        return cStamformdetDomain;
    }

    public void setcStamformdetDomain(String cStamformdetDomain) {
        this.cStamformdetDomain = cStamformdetDomain;
    }

    public String getcStamformdetModifiedby() {
        return cStamformdetModifiedby;
    }

    public void setcStamformdetModifiedby(String cStamformdetModifiedby) {
        this.cStamformdetModifiedby = cStamformdetModifiedby;
    }

    public Date getcStamformdetModifiedon() {
        return cStamformdetModifiedon;
    }

    public void setcStamformdetModifiedon(Date cStamformdetModifiedon) {
        this.cStamformdetModifiedon = cStamformdetModifiedon;
    }

    public String getcWagonId() {
        return cWagonId;
    }

    public void setcWagonId(String cWagonId) {
        this.cWagonId = cWagonId;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public String getcStamformdetCreatedby() {
        return cStamformdetCreatedby;
    }

    public void setcStamformdetCreatedby(String cStamformdetCreatedby) {
        this.cStamformdetCreatedby = cStamformdetCreatedby;
    }

    public Date getcStamformdetCreatedon() {
        return cStamformdetCreatedon;
    }

    public void setcStamformdetCreatedon(Date cStamformdetCreatedon) {
        this.cStamformdetCreatedon = cStamformdetCreatedon;
    }
    
    

}
