/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_ticketsaleoffset")
public class Ticketsaleoffset implements Serializable {

    @Column(name = "c_ticketsaleoffset_id", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_ticketsaleoffset_value", table = "arts_t_ticketsaleoffset", nullable = false)
    @Basic
    private long cTicketsaleoffsetValue;

    @Column(name = "c_ticketsaleoffset_reason", table = "arts_t_ticketsaleoffset", nullable = false, length = 100)
    @Basic
    private String cTicketsaleoffsetReason;

    @Column(name = "c_stasiun_id", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_ticketsaleoffset_status", table = "arts_t_ticketsaleoffset", nullable = false)
    @Basic
    private Character cTicketsaleoffsetStatus;

    @Column(name = "c_ticketsaleoffset_domain", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Basic
    private String cTicketsaleoffsetDomain;

    @Column(name = "c_ticketsaleoffset_modifiedby", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Basic
    private String cTicketsaleoffsetModifiedby;

    @Column(name = "c_ticketsaleoffset_modifiedon", table = "arts_t_ticketsaleoffset", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTicketsaleoffsetModifiedon;

    @Column(name = "c_trip_id", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_ticketsaleoffset_tripdate", table = "arts_t_ticketsaleoffset", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTicketsaleoffsetTripdate;

    @Column(name = "c_ticketsaleoffset_noka", table = "arts_t_ticketsaleoffset", nullable = false, length = 50)
    @Basic
    private String cTicketsaleoffsetNoka;

    @Column(name = "c_ticketsaleoffset_createdby", table = "arts_t_ticketsaleoffset", nullable = false, length = 36)
    @Basic
    private String cTicketsaleoffsetCreatedby;

    @Column(name = "c_ticketsaleoffset_createdon", table = "arts_t_ticketsaleoffset", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTicketsaleoffsetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getcTicketsaleoffsetValue() {
        return cTicketsaleoffsetValue;
    }

    public void setcTicketsaleoffsetValue(long cTicketsaleoffsetValue) {
        this.cTicketsaleoffsetValue = cTicketsaleoffsetValue;
    }

    public String getcTicketsaleoffsetReason() {
        return cTicketsaleoffsetReason;
    }

    public void setcTicketsaleoffsetReason(String cTicketsaleoffsetReason) {
        this.cTicketsaleoffsetReason = cTicketsaleoffsetReason;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public Character getcTicketsaleoffsetStatus() {
        return cTicketsaleoffsetStatus;
    }

    public void setcTicketsaleoffsetStatus(Character cTicketsaleoffsetStatus) {
        this.cTicketsaleoffsetStatus = cTicketsaleoffsetStatus;
    }

    public String getcTicketsaleoffsetDomain() {
        return cTicketsaleoffsetDomain;
    }

    public void setcTicketsaleoffsetDomain(String cTicketsaleoffsetDomain) {
        this.cTicketsaleoffsetDomain = cTicketsaleoffsetDomain;
    }

    public String getcTicketsaleoffsetModifiedby() {
        return cTicketsaleoffsetModifiedby;
    }

    public void setcTicketsaleoffsetModifiedby(String cTicketsaleoffsetModifiedby) {
        this.cTicketsaleoffsetModifiedby = cTicketsaleoffsetModifiedby;
    }

    public Date getcTicketsaleoffsetModifiedon() {
        return cTicketsaleoffsetModifiedon;
    }

    public void setcTicketsaleoffsetModifiedon(Date cTicketsaleoffsetModifiedon) {
        this.cTicketsaleoffsetModifiedon = cTicketsaleoffsetModifiedon;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public Date getcTicketsaleoffsetTripdate() {
        return cTicketsaleoffsetTripdate;
    }

    public void setcTicketsaleoffsetTripdate(Date cTicketsaleoffsetTripdate) {
        this.cTicketsaleoffsetTripdate = cTicketsaleoffsetTripdate;
    }

    public String getcTicketsaleoffsetNoka() {
        return cTicketsaleoffsetNoka;
    }

    public void setcTicketsaleoffsetNoka(String cTicketsaleoffsetNoka) {
        this.cTicketsaleoffsetNoka = cTicketsaleoffsetNoka;
    }

    public String getcTicketsaleoffsetCreatedby() {
        return cTicketsaleoffsetCreatedby;
    }

    public void setcTicketsaleoffsetCreatedby(String cTicketsaleoffsetCreatedby) {
        this.cTicketsaleoffsetCreatedby = cTicketsaleoffsetCreatedby;
    }

    public Date getcTicketsaleoffsetCreatedon() {
        return cTicketsaleoffsetCreatedon;
    }

    public void setcTicketsaleoffsetCreatedon(Date cTicketsaleoffsetCreatedon) {
        this.cTicketsaleoffsetCreatedon = cTicketsaleoffsetCreatedon;
    }

    
}
