/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_title")
public class Title implements Serializable {

    @Column(name = "c_title_id", table = "arts_t_title", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_title_code", table = "arts_t_title", nullable = false, length = 10)
    @Basic
    private String cTitleCode;

    @Column(name = "c_title_name", table = "arts_t_title", nullable = false, length = 20)
    @Basic
    private String cTitleName;

    @Column(name = "c_title_gender", table = "arts_t_title", nullable = false)
    @Basic
    private Character cTitleGender;

    @Column(name = "c_title_status", table = "arts_t_title", nullable = false)
    @Basic
    private Character cTitleStatus;

    @Column(name = "c_title_domain", table = "arts_t_title", nullable = false, length = 36)
    @Basic
    private String cTitleDomain;

    @Column(name = "c_title_modifiedby", table = "arts_t_title", nullable = false, length = 36)
    @Basic
    private String cTitleModifiedby;

    @Column(name = "c_title_modifiedon", table = "arts_t_title", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTitleModifiedon;

    @Column(name = "c_title_createdby", table = "arts_t_title", nullable = false, length = 36)
    @Basic
    private String cTitleCreatedby;

    @Column(name = "c_title_createdon", table = "arts_t_title", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTitleCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTitleCode() {
        return cTitleCode;
    }

    public void setcTitleCode(String cTitleCode) {
        this.cTitleCode = cTitleCode;
    }

    public String getcTitleName() {
        return cTitleName;
    }

    public void setcTitleName(String cTitleName) {
        this.cTitleName = cTitleName;
    }

    public Character getcTitleGender() {
        return cTitleGender;
    }

    public void setcTitleGender(Character cTitleGender) {
        this.cTitleGender = cTitleGender;
    }

    public Character getcTitleStatus() {
        return cTitleStatus;
    }

    public void setcTitleStatus(Character cTitleStatus) {
        this.cTitleStatus = cTitleStatus;
    }

    public String getcTitleDomain() {
        return cTitleDomain;
    }

    public void setcTitleDomain(String cTitleDomain) {
        this.cTitleDomain = cTitleDomain;
    }

    public String getcTitleModifiedby() {
        return cTitleModifiedby;
    }

    public void setcTitleModifiedby(String cTitleModifiedby) {
        this.cTitleModifiedby = cTitleModifiedby;
    }

    public Date getcTitleModifiedon() {
        return cTitleModifiedon;
    }

    public void setcTitleModifiedon(Date cTitleModifiedon) {
        this.cTitleModifiedon = cTitleModifiedon;
    }

    public String getcTitleCreatedby() {
        return cTitleCreatedby;
    }

    public void setcTitleCreatedby(String cTitleCreatedby) {
        this.cTitleCreatedby = cTitleCreatedby;
    }

    public Date getcTitleCreatedon() {
        return cTitleCreatedon;
    }

    public void setcTitleCreatedon(Date cTitleCreatedon) {
        this.cTitleCreatedon = cTitleCreatedon;
    }
    
    
}
