/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_trainrunning", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_trainrunning_value", "c_trainrunning_domain"})})
public class Trainrunning implements Serializable {

    @Column(name = "c_trainrunning_id", table = "arts_t_trainrunning", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_trainrunning_name", table = "arts_t_trainrunning", nullable = false, length = 200)
    @Basic
    private String cTrainrunningName;

    @Column(name = "c_trainrunning_status", table = "arts_t_trainrunning", nullable = false)
    @Basic
    private Character cTrainrunningStatus;

    @Column(name = "c_trainrunning_domain", table = "arts_t_trainrunning", nullable = false, length = 36)
    @Basic
    private String cTrainrunningDomain;

    @Column(name = "c_trainrunning_modifiedby", table = "arts_t_trainrunning", nullable = false, length = 36)
    @Basic
    private String cTrainrunningModifiedby;

    @Column(name = "c_trainrunning_modifiedon", table = "arts_t_trainrunning", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainrunningModifiedon;

    @Column(name = "c_trainrunning_value", table = "arts_t_trainrunning", nullable = false)
    @Basic
    private short cTrainrunningValue;

    @Column(name = "c_trainrunning_createdby", table = "arts_t_trainrunning", nullable = false, length = 36)
    @Basic
    private String cTrainrunningCreatedby;

    @Column(name = "c_trainrunning_createdon", table = "arts_t_trainrunning", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTrainrunningCreatedon;

    @Column(name = "c_trainrunning_code", table = "arts_t_trainrunning", nullable = false, length = 10)
    @Basic
    private String cTrainrunningCode;

    @Column(name = "c_trainrunning_note", table = "arts_t_trainrunning", length = 100)
    @Basic
    private String cTrainrunningNote;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTrainrunningName() {
        return cTrainrunningName;
    }

    public void setcTrainrunningName(String cTrainrunningName) {
        this.cTrainrunningName = cTrainrunningName;
    }

    public Character getcTrainrunningStatus() {
        return cTrainrunningStatus;
    }

    public void setcTrainrunningStatus(Character cTrainrunningStatus) {
        this.cTrainrunningStatus = cTrainrunningStatus;
    }

    public String getcTrainrunningDomain() {
        return cTrainrunningDomain;
    }

    public void setcTrainrunningDomain(String cTrainrunningDomain) {
        this.cTrainrunningDomain = cTrainrunningDomain;
    }

    public String getcTrainrunningModifiedby() {
        return cTrainrunningModifiedby;
    }

    public void setcTrainrunningModifiedby(String cTrainrunningModifiedby) {
        this.cTrainrunningModifiedby = cTrainrunningModifiedby;
    }

    public Date getcTrainrunningModifiedon() {
        return cTrainrunningModifiedon;
    }

    public void setcTrainrunningModifiedon(Date cTrainrunningModifiedon) {
        this.cTrainrunningModifiedon = cTrainrunningModifiedon;
    }

    public short getcTrainrunningValue() {
        return cTrainrunningValue;
    }

    public void setcTrainrunningValue(short cTrainrunningValue) {
        this.cTrainrunningValue = cTrainrunningValue;
    }

    public String getcTrainrunningCreatedby() {
        return cTrainrunningCreatedby;
    }

    public void setcTrainrunningCreatedby(String cTrainrunningCreatedby) {
        this.cTrainrunningCreatedby = cTrainrunningCreatedby;
    }

    public Date getcTrainrunningCreatedon() {
        return cTrainrunningCreatedon;
    }

    public void setcTrainrunningCreatedon(Date cTrainrunningCreatedon) {
        this.cTrainrunningCreatedon = cTrainrunningCreatedon;
    }

    public String getcTrainrunningCode() {
        return cTrainrunningCode;
    }

    public void setcTrainrunningCode(String cTrainrunningCode) {
        this.cTrainrunningCode = cTrainrunningCode;
    }

    public String getcTrainrunningNote() {
        return cTrainrunningNote;
    }

    public void setcTrainrunningNote(String cTrainrunningNote) {
        this.cTrainrunningNote = cTrainrunningNote;
    }

    

}
