/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_traintype", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_traintype_code"})})
public class Traintype implements Serializable {

    @Column(name = "c_traintype_id", table = "arts_t_traintype", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_traintype_name", table = "arts_t_traintype", nullable = false, length = 100)
    @Basic
    private String cTraintypeName;

    @Column(name = "c_traintype_status", table = "arts_t_traintype", nullable = false)
    @Basic
    private Character cTraintypeStatus;

    @Column(name = "c_traintype_domain", table = "arts_t_traintype", nullable = false, length = 36)
    @Basic
    private String cTraintypeDomain;

    @Column(name = "c_traintype_modifiedby", table = "arts_t_traintype", nullable = false, length = 36)
    @Basic
    private String cTraintypeModifiedby;

    @Column(name = "c_traintype_modifiedon", table = "arts_t_traintype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTraintypeModifiedon;

    @Column(name = "c_traintype_code", table = "arts_t_traintype", nullable = false, length = 10)
    @Basic
    private String cTraintypeCode;

    @Column(name = "c_traintype_createdby", table = "arts_t_traintype", nullable = false, length = 36)
    @Basic
    private String cTraintypeCreatedby;

    @Column(name = "c_traintype_createdon", table = "arts_t_traintype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTraintypeCreatedon;

    @Column(name = "c_traintype_note", table = "arts_t_traintype", length = 100)
    @Basic
    private String cTraintypeNote;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTraintypeName() {
        return cTraintypeName;
    }

    public void setcTraintypeName(String cTraintypeName) {
        this.cTraintypeName = cTraintypeName;
    }

    public Character getcTraintypeStatus() {
        return cTraintypeStatus;
    }

    public void setcTraintypeStatus(Character cTraintypeStatus) {
        this.cTraintypeStatus = cTraintypeStatus;
    }

    public String getcTraintypeDomain() {
        return cTraintypeDomain;
    }

    public void setcTraintypeDomain(String cTraintypeDomain) {
        this.cTraintypeDomain = cTraintypeDomain;
    }

    public String getcTraintypeModifiedby() {
        return cTraintypeModifiedby;
    }

    public void setcTraintypeModifiedby(String cTraintypeModifiedby) {
        this.cTraintypeModifiedby = cTraintypeModifiedby;
    }

    public Date getcTraintypeModifiedon() {
        return cTraintypeModifiedon;
    }

    public void setcTraintypeModifiedon(Date cTraintypeModifiedon) {
        this.cTraintypeModifiedon = cTraintypeModifiedon;
    }

    public String getcTraintypeCode() {
        return cTraintypeCode;
    }

    public void setcTraintypeCode(String cTraintypeCode) {
        this.cTraintypeCode = cTraintypeCode;
    }

    public String getcTraintypeCreatedby() {
        return cTraintypeCreatedby;
    }

    public void setcTraintypeCreatedby(String cTraintypeCreatedby) {
        this.cTraintypeCreatedby = cTraintypeCreatedby;
    }

    public Date getcTraintypeCreatedon() {
        return cTraintypeCreatedon;
    }

    public void setcTraintypeCreatedon(Date cTraintypeCreatedon) {
        this.cTraintypeCreatedon = cTraintypeCreatedon;
    }

    public String getcTraintypeNote() {
        return cTraintypeNote;
    }

    public void setcTraintypeNote(String cTraintypeNote) {
        this.cTraintypeNote = cTraintypeNote;
    }
    
    
}
