/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.raws;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_trip", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_trip_date", "c_schedule_id"})})
public class Trip implements Serializable {

    @Column(name = "c_trip_id", table = "arts_t_trip", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_trip_date", table = "arts_t_trip", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTripDate;

    @Column(name = "c_schedule_id", table = "arts_t_trip", nullable = false, length = 36)
    @Basic
    private String cScheduleId;

    @Column(name = "c_trip_status", table = "arts_t_trip", nullable = false)
    @Basic
    private Character cTripStatus;

    @Column(name = "c_trip_domain", table = "arts_t_trip", nullable = false, length = 36)
    @Basic
    private String cTripDomain;

    @Column(name = "c_trip_modifiedby", table = "arts_t_trip", nullable = false, length = 36)
    @Basic
    private String cTripModifiedby;

    @Column(name = "c_trip_modifiedon", table = "arts_t_trip", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTripModifiedon;

    @Column(name = "c_trip_maxcapacity", table = "arts_t_trip")
    @Basic
    private Integer cTripMaxcapacity;

    @Column(name = "c_trip_createdby", table = "arts_t_trip", nullable = false, length = 36)
    @Basic
    private String cTripCreatedby;

    @Column(name = "c_trip_createdon", table = "arts_t_trip", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTripCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcTripDate() {
        return cTripDate;
    }

    public void setcTripDate(Date cTripDate) {
        this.cTripDate = cTripDate;
    }

    public String getcScheduleId() {
        return cScheduleId;
    }

    public void setcScheduleId(String cScheduleId) {
        this.cScheduleId = cScheduleId;
    }

    public Character getcTripStatus() {
        return cTripStatus;
    }

    public void setcTripStatus(Character cTripStatus) {
        this.cTripStatus = cTripStatus;
    }

    public String getcTripDomain() {
        return cTripDomain;
    }

    public void setcTripDomain(String cTripDomain) {
        this.cTripDomain = cTripDomain;
    }

    public String getcTripModifiedby() {
        return cTripModifiedby;
    }

    public void setcTripModifiedby(String cTripModifiedby) {
        this.cTripModifiedby = cTripModifiedby;
    }

    public Date getcTripModifiedon() {
        return cTripModifiedon;
    }

    public void setcTripModifiedon(Date cTripModifiedon) {
        this.cTripModifiedon = cTripModifiedon;
    }

    public Integer getcTripMaxcapacity() {
        return cTripMaxcapacity;
    }

    public void setcTripMaxcapacity(Integer cTripMaxcapacity) {
        this.cTripMaxcapacity = cTripMaxcapacity;
    }

    public String getcTripCreatedby() {
        return cTripCreatedby;
    }

    public void setcTripCreatedby(String cTripCreatedby) {
        this.cTripCreatedby = cTripCreatedby;
    }

    public Date getcTripCreatedon() {
        return cTripCreatedon;
    }

    public void setcTripCreatedon(Date cTripCreatedon) {
        this.cTripCreatedon = cTripCreatedon;
    }

    

}
