/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_cancellationtype")
public class Cancellationtype {

    @Column(name = "c_cancellationtype_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_cancellationtype_name", table = "arts_t_cancellationtype", nullable = false, length = 100)
    @Basic
    private String cCancellationtypeName;

    @Column(name = "c_cancellationtype_status", table = "arts_t_cancellationtype", nullable = false)
    @Basic
    private Character cCancellationtypeStatus;

    @Column(name = "c_cancellationtype_domain", table = "arts_t_cancellationtype", nullable = false, length = 36)
    @Basic
    private String cCancellationtypeDomain;

    @Column(name = "c_cancellationtype_modifiedby", table = "arts_t_cancellationtype", nullable = false, length = 36)
    @Basic
    private String cCancellationtypeModifiedby;

    @Column(name = "c_cancellationtype_modifiedon", table = "arts_t_cancellationtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCancellationtypeModifiedon;

    @Column(name = "c_cancellationtype_code", table = "arts_t_cancellationtype", nullable = false, length = 50)
    @Basic
    private String cCancellationtypeCode;

    @Column(name = "c_cancellationtype_createdby", table = "arts_t_cancellationtype", nullable = false, length = 36)
    @Basic
    private String cCancellationtypeCreatedby;

    @Column(name = "c_cancellationtype_createdon", table = "arts_t_cancellationtype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cCancellationtypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcCancellationtypeName() {
        return cCancellationtypeName;
    }

    public void setcCancellationtypeName(String cCancellationtypeName) {
        this.cCancellationtypeName = cCancellationtypeName;
    }

    public Character getcCancellationtypeStatus() {
        return cCancellationtypeStatus;
    }

    public void setcCancellationtypeStatus(Character cCancellationtypeStatus) {
        this.cCancellationtypeStatus = cCancellationtypeStatus;
    }

    public String getcCancellationtypeDomain() {
        return cCancellationtypeDomain;
    }

    public void setcCancellationtypeDomain(String cCancellationtypeDomain) {
        this.cCancellationtypeDomain = cCancellationtypeDomain;
    }

    public String getcCancellationtypeModifiedby() {
        return cCancellationtypeModifiedby;
    }

    public void setcCancellationtypeModifiedby(String cCancellationtypeModifiedby) {
        this.cCancellationtypeModifiedby = cCancellationtypeModifiedby;
    }

    public Date getcCancellationtypeModifiedon() {
        return cCancellationtypeModifiedon;
    }

    public void setcCancellationtypeModifiedon(Date cCancellationtypeModifiedon) {
        this.cCancellationtypeModifiedon = cCancellationtypeModifiedon;
    }

    public String getcCancellationtypeCode() {
        return cCancellationtypeCode;
    }

    public void setcCancellationtypeCode(String cCancellationtypeCode) {
        this.cCancellationtypeCode = cCancellationtypeCode;
    }

    public String getcCancellationtypeCreatedby() {
        return cCancellationtypeCreatedby;
    }

    public void setcCancellationtypeCreatedby(String cCancellationtypeCreatedby) {
        this.cCancellationtypeCreatedby = cCancellationtypeCreatedby;
    }

    public Date getcCancellationtypeCreatedon() {
        return cCancellationtypeCreatedon;
    }

    public void setcCancellationtypeCreatedon(Date cCancellationtypeCreatedon) {
        this.cCancellationtypeCreatedon = cCancellationtypeCreatedon;
    }

    

}
