/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_grpreservationdet")
public class Grpreservationdet implements Serializable {

    @Column(name = "c_grpreservationdet_id", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_grpreservationdet_psgnum", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    private short cGrpreservationdetPsgnum;

    @Column(name = "c_grpreservationdet_unitprice", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    private long cGrpreservationdetUnitprice;

    @Column(name = "c_grpreservationdet_amount", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    private long cGrpreservationdetAmount;

    @Column(name = "c_wagonclass_id", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_trip_id", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_grpreservation_id", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cGrpreservationId;

    @Column(name = "c_stasiun_idorg", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cStasiunIdorg;

    @Column(name = "c_stasiun_iddest", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cStasiunIddest;

    @Column(name = "c_grpreservationdet_status", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    private Character cGrpreservationdetStatus;

    @Column(name = "c_grpreservationdet_domain", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cGrpreservationdetDomain;

    @Column(name = "c_grpreservationdet_modifiedby", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cGrpreservationdetModifiedby;

    @Column(name = "c_grpreservationdet_modifiedon", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cGrpreservationdetModifiedon;

    @Column(name = "c_grpreservationdet_createdby", table = "arts_t_grpreservationdet", nullable = false, length = 36)
    @Basic
    private String cGrpreservationdetCreatedby;

    @Column(name = "c_grpreservationdet_createdon", table = "arts_t_grpreservationdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cGrpreservationdetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public short getcGrpreservationdetPsgnum() {
        return cGrpreservationdetPsgnum;
    }

    public void setcGrpreservationdetPsgnum(short cGrpreservationdetPsgnum) {
        this.cGrpreservationdetPsgnum = cGrpreservationdetPsgnum;
    }

    public long getcGrpreservationdetUnitprice() {
        return cGrpreservationdetUnitprice;
    }

    public void setcGrpreservationdetUnitprice(long cGrpreservationdetUnitprice) {
        this.cGrpreservationdetUnitprice = cGrpreservationdetUnitprice;
    }

    public long getcGrpreservationdetAmount() {
        return cGrpreservationdetAmount;
    }

    public void setcGrpreservationdetAmount(long cGrpreservationdetAmount) {
        this.cGrpreservationdetAmount = cGrpreservationdetAmount;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public String getcGrpreservationId() {
        return cGrpreservationId;
    }

    public void setcGrpreservationId(String cGrpreservationId) {
        this.cGrpreservationId = cGrpreservationId;
    }

    public String getcStasiunIdorg() {
        return cStasiunIdorg;
    }

    public void setcStasiunIdorg(String cStasiunIdorg) {
        this.cStasiunIdorg = cStasiunIdorg;
    }

    public String getcStasiunIddest() {
        return cStasiunIddest;
    }

    public void setcStasiunIddest(String cStasiunIddest) {
        this.cStasiunIddest = cStasiunIddest;
    }

    public Character getcGrpreservationdetStatus() {
        return cGrpreservationdetStatus;
    }

    public void setcGrpreservationdetStatus(Character cGrpreservationdetStatus) {
        this.cGrpreservationdetStatus = cGrpreservationdetStatus;
    }

    public String getcGrpreservationdetDomain() {
        return cGrpreservationdetDomain;
    }

    public void setcGrpreservationdetDomain(String cGrpreservationdetDomain) {
        this.cGrpreservationdetDomain = cGrpreservationdetDomain;
    }

    public String getcGrpreservationdetModifiedby() {
        return cGrpreservationdetModifiedby;
    }

    public void setcGrpreservationdetModifiedby(String cGrpreservationdetModifiedby) {
        this.cGrpreservationdetModifiedby = cGrpreservationdetModifiedby;
    }

    public Date getcGrpreservationdetModifiedon() {
        return cGrpreservationdetModifiedon;
    }

    public void setcGrpreservationdetModifiedon(Date cGrpreservationdetModifiedon) {
        this.cGrpreservationdetModifiedon = cGrpreservationdetModifiedon;
    }

    public String getcGrpreservationdetCreatedby() {
        return cGrpreservationdetCreatedby;
    }

    public void setcGrpreservationdetCreatedby(String cGrpreservationdetCreatedby) {
        this.cGrpreservationdetCreatedby = cGrpreservationdetCreatedby;
    }

    public Date getcGrpreservationdetCreatedon() {
        return cGrpreservationdetCreatedon;
    }

    public void setcGrpreservationdetCreatedon(Date cGrpreservationdetCreatedon) {
        this.cGrpreservationdetCreatedon = cGrpreservationdetCreatedon;
    }

    
}
