/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_refund")
public class Refund implements Serializable {

    @Column(name = "c_refund_id", table = "arts_t_refund", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_cancellation_id", table = "arts_t_refund", nullable = false, length = 36)
    @Basic
    private String cCancellationId;

    @Column(name = "c_refund_paytype", table = "arts_t_refund", nullable = false)
    @Basic
    private Character cRefundPaytype;

    @Column(name = "c_refund_paystartdate", table = "arts_t_refund", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundPaystartdate;

    @Column(name = "c_refund_payenddate", table = "arts_t_refund", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundPayenddate;

    @Column(name = "c_refund_paydate", table = "arts_t_refund")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundPaydate;

    @Column(name = "c_refund_bankaccnum", table = "arts_t_refund", length = 100)
    @Basic
    private String cRefundBankaccnum;

    @Column(name = "c_refund_bankaccname", table = "arts_t_refund", length = 100)
    @Basic
    private String cRefundBankaccname;

    @Column(name = "c_refund_status", table = "arts_t_refund", nullable = false)
    @Basic
    private Character cRefundStatus;

    @Column(name = "c_refund_domain", table = "arts_t_refund", nullable = false, length = 36)
    @Basic
    private String cRefundDomain;

    @Column(name = "c_refund_modifiedby", table = "arts_t_refund", nullable = false, length = 36)
    @Basic
    private String cRefundModifiedby;

    @Column(name = "c_refund_modifiedon", table = "arts_t_refund", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundModifiedon;

    @Column(name = "c_bank_id", table = "arts_t_refund", length = 36)
    @Basic
    private String cBankId;

    @Column(name = "c_stasiun_id", table = "arts_t_refund", length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_refund_maxprint", table = "arts_t_refund")
    @Basic
    private Short cRefundMaxprint;

    @Column(name = "c_refund_refundnum", table = "arts_t_refund", length = 50)
    @Basic
    private String cRefundRefundnum;

    @Column(name = "c_refund_printedon", table = "arts_t_refund")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundPrintedon;

    @Column(name = "c_refund_totamount", table = "arts_t_refund", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cRefundTotamount;

    @Column(name = "c_refund_phonenum", table = "arts_t_refund", length = 50)
    @Basic
    private String cRefundPhonenum;

    @Column(name = "c_shift_id", table = "arts_t_refund", length = 36)
    @Basic
    private String cShiftId;

    @Column(name = "c_refund_noka", table = "arts_t_refund", nullable = false, length = 50)
    @Basic
    private String cRefundNoka;

    @Column(name = "c_refund_contactname", table = "arts_t_refund", length = 100)
    @Basic
    private String cRefundContactname;

    @Column(name = "c_refund_createdby", table = "arts_t_refund", nullable = false, length = 36)
    @Basic
    private String cRefundCreatedby;

    @Column(name = "c_refund_createdon", table = "arts_t_refund", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cRefundCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcCancellationId() {
        return cCancellationId;
    }

    public void setcCancellationId(String cCancellationId) {
        this.cCancellationId = cCancellationId;
    }

    public Character getcRefundPaytype() {
        return cRefundPaytype;
    }

    public void setcRefundPaytype(Character cRefundPaytype) {
        this.cRefundPaytype = cRefundPaytype;
    }

    public Date getcRefundPaystartdate() {
        return cRefundPaystartdate;
    }

    public void setcRefundPaystartdate(Date cRefundPaystartdate) {
        this.cRefundPaystartdate = cRefundPaystartdate;
    }

    public Date getcRefundPayenddate() {
        return cRefundPayenddate;
    }

    public void setcRefundPayenddate(Date cRefundPayenddate) {
        this.cRefundPayenddate = cRefundPayenddate;
    }

    public Date getcRefundPaydate() {
        return cRefundPaydate;
    }

    public void setcRefundPaydate(Date cRefundPaydate) {
        this.cRefundPaydate = cRefundPaydate;
    }

    public String getcRefundBankaccnum() {
        return cRefundBankaccnum;
    }

    public void setcRefundBankaccnum(String cRefundBankaccnum) {
        this.cRefundBankaccnum = cRefundBankaccnum;
    }

    public String getcRefundBankaccname() {
        return cRefundBankaccname;
    }

    public void setcRefundBankaccname(String cRefundBankaccname) {
        this.cRefundBankaccname = cRefundBankaccname;
    }

    public Character getcRefundStatus() {
        return cRefundStatus;
    }

    public void setcRefundStatus(Character cRefundStatus) {
        this.cRefundStatus = cRefundStatus;
    }

    public String getcRefundDomain() {
        return cRefundDomain;
    }

    public void setcRefundDomain(String cRefundDomain) {
        this.cRefundDomain = cRefundDomain;
    }

    public String getcRefundModifiedby() {
        return cRefundModifiedby;
    }

    public void setcRefundModifiedby(String cRefundModifiedby) {
        this.cRefundModifiedby = cRefundModifiedby;
    }

    public Date getcRefundModifiedon() {
        return cRefundModifiedon;
    }

    public void setcRefundModifiedon(Date cRefundModifiedon) {
        this.cRefundModifiedon = cRefundModifiedon;
    }

    public String getcBankId() {
        return cBankId;
    }

    public void setcBankId(String cBankId) {
        this.cBankId = cBankId;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public Short getcRefundMaxprint() {
        return cRefundMaxprint;
    }

    public void setcRefundMaxprint(Short cRefundMaxprint) {
        this.cRefundMaxprint = cRefundMaxprint;
    }

    public String getcRefundRefundnum() {
        return cRefundRefundnum;
    }

    public void setcRefundRefundnum(String cRefundRefundnum) {
        this.cRefundRefundnum = cRefundRefundnum;
    }

    public Date getcRefundPrintedon() {
        return cRefundPrintedon;
    }

    public void setcRefundPrintedon(Date cRefundPrintedon) {
        this.cRefundPrintedon = cRefundPrintedon;
    }

    public BigDecimal getcRefundTotamount() {
        return cRefundTotamount;
    }

    public void setcRefundTotamount(BigDecimal cRefundTotamount) {
        this.cRefundTotamount = cRefundTotamount;
    }

    public String getcRefundPhonenum() {
        return cRefundPhonenum;
    }

    public void setcRefundPhonenum(String cRefundPhonenum) {
        this.cRefundPhonenum = cRefundPhonenum;
    }

    public String getcShiftId() {
        return cShiftId;
    }

    public void setcShiftId(String cShiftId) {
        this.cShiftId = cShiftId;
    }

    public String getcRefundNoka() {
        return cRefundNoka;
    }

    public void setcRefundNoka(String cRefundNoka) {
        this.cRefundNoka = cRefundNoka;
    }

    public String getcRefundContactname() {
        return cRefundContactname;
    }

    public void setcRefundContactname(String cRefundContactname) {
        this.cRefundContactname = cRefundContactname;
    }

    public String getcRefundCreatedby() {
        return cRefundCreatedby;
    }

    public void setcRefundCreatedby(String cRefundCreatedby) {
        this.cRefundCreatedby = cRefundCreatedby;
    }

    public Date getcRefundCreatedon() {
        return cRefundCreatedon;
    }

    public void setcRefundCreatedon(Date cRefundCreatedon) {
        this.cRefundCreatedon = cRefundCreatedon;
    }

    

}
