/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_ticketnumbertmp")
public class Ticketnumbertmp implements Serializable {

    @Column(name = "c_ticketnumbertmp_id", table = "arts_t_ticketnumbertmp", nullable = false, length = 50)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_transaction_id", table = "arts_t_ticketnumbertmp", nullable = false, length = 36)
    @Basic
    private String cTransactionId;

    @Column(name = "c_ticketnumbertmp_date", table = "arts_t_ticketnumbertmp", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTicketnumbertmpDate;

    @Column(name = "c_stasiun_idbook", table = "arts_t_ticketnumbertmp", nullable = false, length = 36)
    @Basic
    private String cStasiunIdbook;

    @Column(name = "c_ticketnumbertmp_createdby", table = "arts_t_ticketnumbertmp", nullable = false, length = 36)
    @Basic
    private String cTicketnumbertmpCreatedby;

    @Column(name = "c_ticketnumbertmp_createdon", table = "arts_t_ticketnumbertmp", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTicketnumbertmpCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTransactionId() {
        return cTransactionId;
    }

    public void setcTransactionId(String cTransactionId) {
        this.cTransactionId = cTransactionId;
    }

    public Date getcTicketnumbertmpDate() {
        return cTicketnumbertmpDate;
    }

    public void setcTicketnumbertmpDate(Date cTicketnumbertmpDate) {
        this.cTicketnumbertmpDate = cTicketnumbertmpDate;
    }

    public String getcStasiunIdbook() {
        return cStasiunIdbook;
    }

    public void setcStasiunIdbook(String cStasiunIdbook) {
        this.cStasiunIdbook = cStasiunIdbook;
    }

    public String getcTicketnumbertmpCreatedby() {
        return cTicketnumbertmpCreatedby;
    }

    public void setcTicketnumbertmpCreatedby(String cTicketnumbertmpCreatedby) {
        this.cTicketnumbertmpCreatedby = cTicketnumbertmpCreatedby;
    }

    public Date getcTicketnumbertmpCreatedon() {
        return cTicketnumbertmpCreatedon;
    }

    public void setcTicketnumbertmpCreatedon(Date cTicketnumbertmpCreatedon) {
        this.cTicketnumbertmpCreatedon = cTicketnumbertmpCreatedon;
    }

    

}
