/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_transactionlog")
public class Transactionlog implements Serializable {

    @Column(name = "c_transactionlog_id", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_transaction_id", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cTransactionId;

    @Column(name = "c_transaction_bookcode", table = "arts_t_transactionlog", nullable = false, length = 7)
    @Basic
    private String cTransactionBookcode;

    @Column(name = "c_transactiondet_id", table = "arts_t_transactionlog", length = 36)
    @Basic
    private String cTransactiondetId;

    @Column(name = "c_cancellation_id", table = "arts_t_transactionlog", length = 36)
    @Basic
    private String cCancellationId;

    @Column(name = "c_cancellationdet_id", table = "arts_t_transactionlog", length = 36)
    @Basic
    private String cCancellationdetId;

    @Column(name = "c_transactionlog_time", table = "arts_t_transactionlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionlogTime;

    @Column(name = "c_transactionlog_type", table = "arts_t_transactionlog", length = 50)
    @Basic
    private String cTransactionlogType;

    @Column(name = "c_transactionlog_value", table = "arts_t_transactionlog", nullable = false, length = 2147483647)
    @Lob
    @Basic
    private String cTransactionlogValue;

    @Column(name = "c_user_id", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_user_fullname", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cUserFullname;

    @Column(name = "c_stasiun_id", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_stasiun_code", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cStasiunCode;

    @Column(name = "c_unit_id", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_unit_code", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cUnitCode;

    @Column(name = "c_shift_id", table = "arts_t_transactionlog", length = 36)
    @Basic
    private String cShiftId;

    @Column(name = "c_transactionlog_status", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cTransactionlogStatus;

    @Column(name = "c_transactionlog_domain", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cTransactionlogDomain;

    @Column(name = "c_transactionlog_createdby", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cTransactionlogCreatedby;

    @Column(name = "c_transactionlog_createdon", table = "arts_t_transactionlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionlogCreatedon;

    @Column(name = "c_transactionlog_modifiedby", table = "arts_t_transactionlog", nullable = false, length = 36)
    @Basic
    private String cTransactionlogModifiedby;

    @Column(name = "c_transactionlog_modifiedon", table = "arts_t_transactionlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionlogModifiedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTransactionId() {
        return cTransactionId;
    }

    public void setcTransactionId(String cTransactionId) {
        this.cTransactionId = cTransactionId;
    }

    public String getcTransactionBookcode() {
        return cTransactionBookcode;
    }

    public void setcTransactionBookcode(String cTransactionBookcode) {
        this.cTransactionBookcode = cTransactionBookcode;
    }

    public String getcTransactiondetId() {
        return cTransactiondetId;
    }

    public void setcTransactiondetId(String cTransactiondetId) {
        this.cTransactiondetId = cTransactiondetId;
    }

    public String getcCancellationId() {
        return cCancellationId;
    }

    public void setcCancellationId(String cCancellationId) {
        this.cCancellationId = cCancellationId;
    }

    public String getcCancellationdetId() {
        return cCancellationdetId;
    }

    public void setcCancellationdetId(String cCancellationdetId) {
        this.cCancellationdetId = cCancellationdetId;
    }

    public Date getcTransactionlogTime() {
        return cTransactionlogTime;
    }

    public void setcTransactionlogTime(Date cTransactionlogTime) {
        this.cTransactionlogTime = cTransactionlogTime;
    }

    public String getcTransactionlogType() {
        return cTransactionlogType;
    }

    public void setcTransactionlogType(String cTransactionlogType) {
        this.cTransactionlogType = cTransactionlogType;
    }

    public String getcTransactionlogValue() {
        return cTransactionlogValue;
    }

    public void setcTransactionlogValue(String cTransactionlogValue) {
        this.cTransactionlogValue = cTransactionlogValue;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcUserFullname() {
        return cUserFullname;
    }

    public void setcUserFullname(String cUserFullname) {
        this.cUserFullname = cUserFullname;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public String getcStasiunCode() {
        return cStasiunCode;
    }

    public void setcStasiunCode(String cStasiunCode) {
        this.cStasiunCode = cStasiunCode;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public String getcUnitCode() {
        return cUnitCode;
    }

    public void setcUnitCode(String cUnitCode) {
        this.cUnitCode = cUnitCode;
    }

    public String getcShiftId() {
        return cShiftId;
    }

    public void setcShiftId(String cShiftId) {
        this.cShiftId = cShiftId;
    }

    public String getcTransactionlogStatus() {
        return cTransactionlogStatus;
    }

    public void setcTransactionlogStatus(String cTransactionlogStatus) {
        this.cTransactionlogStatus = cTransactionlogStatus;
    }

    public String getcTransactionlogDomain() {
        return cTransactionlogDomain;
    }

    public void setcTransactionlogDomain(String cTransactionlogDomain) {
        this.cTransactionlogDomain = cTransactionlogDomain;
    }

    public String getcTransactionlogCreatedby() {
        return cTransactionlogCreatedby;
    }

    public void setcTransactionlogCreatedby(String cTransactionlogCreatedby) {
        this.cTransactionlogCreatedby = cTransactionlogCreatedby;
    }

    public Date getcTransactionlogCreatedon() {
        return cTransactionlogCreatedon;
    }

    public void setcTransactionlogCreatedon(Date cTransactionlogCreatedon) {
        this.cTransactionlogCreatedon = cTransactionlogCreatedon;
    }

    public String getcTransactionlogModifiedby() {
        return cTransactionlogModifiedby;
    }

    public void setcTransactionlogModifiedby(String cTransactionlogModifiedby) {
        this.cTransactionlogModifiedby = cTransactionlogModifiedby;
    }

    public Date getcTransactionlogModifiedon() {
        return cTransactionlogModifiedon;
    }

    public void setcTransactionlogModifiedon(Date cTransactionlogModifiedon) {
        this.cTransactionlogModifiedon = cTransactionlogModifiedon;
    }
    
    

}
