/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author  root
 */

@Entity
@Table(name="arts_t_transactiondet")
public class Transactiondet {

    @Column(name="c_transactiondet_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name="c_transaction_id",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTransactionId;

    @Column(name="c_transaction_bookcode",table="arts_t_transactiondet",nullable=false,length=20)
    @Basic
    private String cTransactionBookcode;

    @Column(name="c_transaction_paycode",table="arts_t_transactiondet",nullable=false,length=20)
    @Basic
    private String cTransactionPaycode;

    @Column(name="c_transaction_transdate",table="arts_t_transactiondet",nullable=false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionTransdate;

    @Column(name="c_transaction_custname",table="arts_t_transactiondet",nullable=false,scale=2,precision=11)
    @Basic
    private BigDecimal cTransactionCustname;

    @Column(name="c_transaction_phonenum",table="arts_t_transactiondet",length=36)
    @Basic
    private String cTransactionPhonenum;

    @Column(name="c_transaction_email",table="arts_t_transactiondet",length=100)
    @Basic
    private String cTransactionEmail;

    @Column(name="c_stasiun_idorg",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cStasiunIdorg;

    @Column(name="c_stasiun_codeorg",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cStasiunCodeorg;

    @Column(name="c_stasiun_iddes",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cStasiunIddes;

    @Column(name="c_stasiun_codedes",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cStasiunCodedes;

    @Column(name="c_schedule_id",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cScheduleId;

    @Column(name="c_schedule_noka",table="arts_t_transactiondet",nullable=false,length=50)
    @Basic
    private String cScheduleNoka;

    @Column(name="c_schedule_localstat",table="arts_t_transactiondet",nullable=false)
    @Basic
    private Character cScheduleLocalstat;

    @Column(name="c_schedule_trainname",table="arts_t_transactiondet",nullable=false)
    @Basic
    private Character cScheduleTrainname;

    @Column(name="c_trip_id",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTripId;

    @Column(name="c_trip_date",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTripDate;

    @Column(name="c_subclass_id",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cSubclassId;

    @Column(name="c_subclass_code",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cSubclassCode;

    @Column(name="c_user_idbook",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cUserIdbook;

    @Column(name="c_user_fullnamebook",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cUserFullnamebook;

    @Column(name="c_unit_idbook",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitIdbook;

    @Column(name="c_unit_codebook",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitCodebook;

    @Column(name="c_shift_idbook",table="arts_t_transactiondet",length=36)
    @Basic
    private String cShiftIdbook;

    @Column(name="c_channel_idbook",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cChannelIdbook;

    @Column(name="c_channel_codebook",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cChannelCodebook;

    @Column(name="c_user_idpay",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUserIdpay;

    @Column(name="c_user_fullnamepay",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUserFullnamepay;

    @Column(name="c_unit_idpay",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitIdpay;

    @Column(name="c_unit_codepay",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitCodepay;

    @Column(name="c_shift_idpay",table="arts_t_transactiondet",length=36)
    @Basic
    private String cShiftIdpay;

    @Column(name="c_channel_idpay",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cChannelIdpay;

    @Column(name="c_channel_codepay",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cChannelCodepay;

    @Column(name="c_transaction_bookedon",table="arts_t_transactiondet")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionBookedon;

    @Column(name="c_transaction_booktimeouton",table="arts_t_transactiondet")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionBooktimeouton;

    @Column(name="c_transaction_paytimeouton",table="arts_t_transactiondet")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionPaytimeouton;

    @Column(name="c_transaction_paidon",table="arts_t_transactiondet")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionPaidon;

    @Column(name="c_transaction_reroutestat",table="arts_t_transactiondet")
    @Basic
    private Character cTransactionReroutestat;

    @Column(name="c_transaction_flexiredeemstat",table="arts_t_transactiondet")
    @Basic
    private Character cTransactionFlexiredeemstat;

    @Column(name="c_transactiondet_psgname",table="arts_t_transactiondet",nullable=false,length=100)
    @Basic
    private String cTransactiondetPsgname;

    @Column(name="c_transactiondet_psgid",table="arts_t_transactiondet",nullable=false,length=50)
    @Basic
    private String cTransactiondetPsgid;

    @Column(name="c_stamformdet_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStamformdetId;

    @Column(name="c_stamformdet_code",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStamformdetCode;

    @Column(name="c_wagondet_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cWagondetId;

    @Column(name="c_wagondet_row",table="arts_t_transactiondet",length=36)
    @Basic
    private String cWagondetRow;

    @Column(name="c_wagondet_col",table="arts_t_transactiondet",length=36)
    @Basic
    private String cWagondetCol;

    @Column(name="c_transactiondet_amount",table="arts_t_transactiondet",nullable=false,scale=2,precision=11)
    @Basic
    private BigDecimal cTransactiondetAmount;

    @Column(name="c_transactiondet_ticketnum",table="arts_t_transactiondet",length=50)
    @Basic
    private String cTransactiondetTicketnum;

    @Column(name="c_member_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cMemberId;

    @Column(name="c_reduction_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cReductionId;

    @Column(name="c_reduction_name",table="arts_t_transactiondet",length=36)
    @Basic
    private String cReductionName;

    @Column(name="c_reduction_amount",table="arts_t_transactiondet",length=36)
    @Basic
    private String cReductionAmount;

    @Column(name="c_reduction_amounttype",table="arts_t_transactiondet",length=36)
    @Basic
    private String cReductionAmounttype;

    @Column(name="c_reduction_amountconvert",table="arts_t_transactiondet",length=36)
    @Basic
    private String cReductionAmountconvert;

    @Column(name="c_discount_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cDiscountId;

    @Column(name="c_discount_name",table="arts_t_transactiondet",length=36)
    @Basic
    private String cDiscountName;

    @Column(name="c_discount_amount",table="arts_t_transactiondet",length=36)
    @Basic
    private String cDiscountAmount;

    @Column(name="c_discount_amounttype",table="arts_t_transactiondet",length=36)
    @Basic
    private String cDiscountAmounttype;

    @Column(name="c_discount_amountconvert",table="arts_t_transactiondet",length=36)
    @Basic
    private String cDiscountAmountconvert;

    @Column(name="c_fare_id",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareId;

    @Column(name="c_fare_basicfare",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareBasicfare;

    @Column(name="c_fare_tuslahfee",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareTuslahfee;

    @Column(name="c_fare_rsvfee",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareRsvfee;

    @Column(name="c_fare_stfee",table="arts_t_transactiondet")
    @Basic
    private Integer cFareStfee;

    @Column(name="c_fare_addfee",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareAddfee;

    @Column(name="c_fare_compinsurance",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareCompinsurance;

    @Column(name="c_fare_addinsurance",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareAddinsurance;

    @Column(name="c_fare_psofare",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFarePsofare;

    @Column(name="c_fare_totamount",table="arts_t_transactiondet",length=36)
    @Basic
    private String cFareTotamount;

    @Column(name="c_flexi_id",table="arts_t_transactiondet",nullable=false,length=20)
    @Basic
    private String cFlexiId;

    @Column(name="c_flexi_code",table="arts_t_transactiondet",nullable=false,length=20)
    @Basic
    private String cFlexiCode;

    @Column(name="c_stasiun_idgatein",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStasiunIdgatein;

    @Column(name="c_stasiun_codegateind",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStasiunCodegateind;

    @Column(name="c_unit_idgatein",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitIdgatein;

    @Column(name="c_unit_codegatein",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitCodegatein;

    @Column(name="c_transactiondet_gateinon",table="arts_t_transactiondet")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactiondetGateinon;

    @Column(name="c_stasiun_idgateout",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStasiunIdgateout;

    @Column(name="c_stasiun_codegateout",table="arts_t_transactiondet",length=36)
    @Basic
    private String cStasiunCodegateout;

    @Column(name="c_unit_idgateout",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitIdgateout;

    @Column(name="c_unit_codegateout",table="arts_t_transactiondet",length=36)
    @Basic
    private String cUnitCodegateout;

    @Column(name="c_transactiondet_gateouton",table="arts_t_transactiondet",nullable=false,length=20)
    @Basic
    private String cTransactiondetGateouton;

    @Column(name="c_transactiondet_max_print",table="arts_t_transactiondet",nullable=false)
    @Basic
    private short cTransactiondetMaxPrint;

    @Column(name="c_transactiondet_ref",table="arts_t_transactiondet",nullable=false)
    @Basic
    private short cTransactiondetRef;

    @Column(name="c_transactiondet_status",table="arts_t_transactiondet",nullable=false)
    @Basic
    private short cTransactiondetStatus;

    @Column(name="c_transactiondet_domain",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTransactiondetDomain;

    @Column(name="c_transactiondet_modifiedby",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTransactiondetModifiedby;

    @Column(name="c_transactiondet_modifiedon",table="arts_t_transactiondet",nullable=false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactiondetModifiedon;

    @Column(name="c_transactiondet_createdby",table="arts_t_transactiondet",nullable=false,length=36)
    @Basic
    private String cTransactiondetCreatedby;

    @Column(name="c_transactiondet_createdon",table="arts_t_transactiondet",nullable=false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactiondetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTransactionId() {
        return cTransactionId;
    }

    public void setcTransactionId(String cTransactionId) {
        this.cTransactionId = cTransactionId;
    }

    public String getcTransactionBookcode() {
        return cTransactionBookcode;
    }

    public void setcTransactionBookcode(String cTransactionBookcode) {
        this.cTransactionBookcode = cTransactionBookcode;
    }

    public String getcTransactionPaycode() {
        return cTransactionPaycode;
    }

    public void setcTransactionPaycode(String cTransactionPaycode) {
        this.cTransactionPaycode = cTransactionPaycode;
    }

    public Date getcTransactionTransdate() {
        return cTransactionTransdate;
    }

    public void setcTransactionTransdate(Date cTransactionTransdate) {
        this.cTransactionTransdate = cTransactionTransdate;
    }

    public BigDecimal getcTransactionCustname() {
        return cTransactionCustname;
    }

    public void setcTransactionCustname(BigDecimal cTransactionCustname) {
        this.cTransactionCustname = cTransactionCustname;
    }

    public String getcTransactionPhonenum() {
        return cTransactionPhonenum;
    }

    public void setcTransactionPhonenum(String cTransactionPhonenum) {
        this.cTransactionPhonenum = cTransactionPhonenum;
    }

    public String getcTransactionEmail() {
        return cTransactionEmail;
    }

    public void setcTransactionEmail(String cTransactionEmail) {
        this.cTransactionEmail = cTransactionEmail;
    }

    public String getcStasiunIdorg() {
        return cStasiunIdorg;
    }

    public void setcStasiunIdorg(String cStasiunIdorg) {
        this.cStasiunIdorg = cStasiunIdorg;
    }

    public String getcStasiunCodeorg() {
        return cStasiunCodeorg;
    }

    public void setcStasiunCodeorg(String cStasiunCodeorg) {
        this.cStasiunCodeorg = cStasiunCodeorg;
    }

    public String getcStasiunIddes() {
        return cStasiunIddes;
    }

    public void setcStasiunIddes(String cStasiunIddes) {
        this.cStasiunIddes = cStasiunIddes;
    }

    public String getcStasiunCodedes() {
        return cStasiunCodedes;
    }

    public void setcStasiunCodedes(String cStasiunCodedes) {
        this.cStasiunCodedes = cStasiunCodedes;
    }

    public String getcScheduleId() {
        return cScheduleId;
    }

    public void setcScheduleId(String cScheduleId) {
        this.cScheduleId = cScheduleId;
    }

    public String getcScheduleNoka() {
        return cScheduleNoka;
    }

    public void setcScheduleNoka(String cScheduleNoka) {
        this.cScheduleNoka = cScheduleNoka;
    }

    public Character getcScheduleLocalstat() {
        return cScheduleLocalstat;
    }

    public void setcScheduleLocalstat(Character cScheduleLocalstat) {
        this.cScheduleLocalstat = cScheduleLocalstat;
    }

    public Character getcScheduleTrainname() {
        return cScheduleTrainname;
    }

    public void setcScheduleTrainname(Character cScheduleTrainname) {
        this.cScheduleTrainname = cScheduleTrainname;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public String getcTripDate() {
        return cTripDate;
    }

    public void setcTripDate(String cTripDate) {
        this.cTripDate = cTripDate;
    }

    public String getcSubclassId() {
        return cSubclassId;
    }

    public void setcSubclassId(String cSubclassId) {
        this.cSubclassId = cSubclassId;
    }

    public String getcSubclassCode() {
        return cSubclassCode;
    }

    public void setcSubclassCode(String cSubclassCode) {
        this.cSubclassCode = cSubclassCode;
    }

    public String getcUserIdbook() {
        return cUserIdbook;
    }

    public void setcUserIdbook(String cUserIdbook) {
        this.cUserIdbook = cUserIdbook;
    }

    public String getcUserFullnamebook() {
        return cUserFullnamebook;
    }

    public void setcUserFullnamebook(String cUserFullnamebook) {
        this.cUserFullnamebook = cUserFullnamebook;
    }

    public String getcUnitIdbook() {
        return cUnitIdbook;
    }

    public void setcUnitIdbook(String cUnitIdbook) {
        this.cUnitIdbook = cUnitIdbook;
    }

    public String getcUnitCodebook() {
        return cUnitCodebook;
    }

    public void setcUnitCodebook(String cUnitCodebook) {
        this.cUnitCodebook = cUnitCodebook;
    }

    public String getcShiftIdbook() {
        return cShiftIdbook;
    }

    public void setcShiftIdbook(String cShiftIdbook) {
        this.cShiftIdbook = cShiftIdbook;
    }

    public String getcChannelIdbook() {
        return cChannelIdbook;
    }

    public void setcChannelIdbook(String cChannelIdbook) {
        this.cChannelIdbook = cChannelIdbook;
    }

    public String getcChannelCodebook() {
        return cChannelCodebook;
    }

    public void setcChannelCodebook(String cChannelCodebook) {
        this.cChannelCodebook = cChannelCodebook;
    }

    public String getcUserIdpay() {
        return cUserIdpay;
    }

    public void setcUserIdpay(String cUserIdpay) {
        this.cUserIdpay = cUserIdpay;
    }

    public String getcUserFullnamepay() {
        return cUserFullnamepay;
    }

    public void setcUserFullnamepay(String cUserFullnamepay) {
        this.cUserFullnamepay = cUserFullnamepay;
    }

    public String getcUnitIdpay() {
        return cUnitIdpay;
    }

    public void setcUnitIdpay(String cUnitIdpay) {
        this.cUnitIdpay = cUnitIdpay;
    }

    public String getcUnitCodepay() {
        return cUnitCodepay;
    }

    public void setcUnitCodepay(String cUnitCodepay) {
        this.cUnitCodepay = cUnitCodepay;
    }

    public String getcShiftIdpay() {
        return cShiftIdpay;
    }

    public void setcShiftIdpay(String cShiftIdpay) {
        this.cShiftIdpay = cShiftIdpay;
    }

    public String getcChannelIdpay() {
        return cChannelIdpay;
    }

    public void setcChannelIdpay(String cChannelIdpay) {
        this.cChannelIdpay = cChannelIdpay;
    }

    public String getcChannelCodepay() {
        return cChannelCodepay;
    }

    public void setcChannelCodepay(String cChannelCodepay) {
        this.cChannelCodepay = cChannelCodepay;
    }

    public Date getcTransactionBookedon() {
        return cTransactionBookedon;
    }

    public void setcTransactionBookedon(Date cTransactionBookedon) {
        this.cTransactionBookedon = cTransactionBookedon;
    }

    public Date getcTransactionBooktimeouton() {
        return cTransactionBooktimeouton;
    }

    public void setcTransactionBooktimeouton(Date cTransactionBooktimeouton) {
        this.cTransactionBooktimeouton = cTransactionBooktimeouton;
    }

    public Date getcTransactionPaytimeouton() {
        return cTransactionPaytimeouton;
    }

    public void setcTransactionPaytimeouton(Date cTransactionPaytimeouton) {
        this.cTransactionPaytimeouton = cTransactionPaytimeouton;
    }

    public Date getcTransactionPaidon() {
        return cTransactionPaidon;
    }

    public void setcTransactionPaidon(Date cTransactionPaidon) {
        this.cTransactionPaidon = cTransactionPaidon;
    }

    public Character getcTransactionReroutestat() {
        return cTransactionReroutestat;
    }

    public void setcTransactionReroutestat(Character cTransactionReroutestat) {
        this.cTransactionReroutestat = cTransactionReroutestat;
    }

    public Character getcTransactionFlexiredeemstat() {
        return cTransactionFlexiredeemstat;
    }

    public void setcTransactionFlexiredeemstat(Character cTransactionFlexiredeemstat) {
        this.cTransactionFlexiredeemstat = cTransactionFlexiredeemstat;
    }

    public String getcTransactiondetPsgname() {
        return cTransactiondetPsgname;
    }

    public void setcTransactiondetPsgname(String cTransactiondetPsgname) {
        this.cTransactiondetPsgname = cTransactiondetPsgname;
    }

    public String getcTransactiondetPsgid() {
        return cTransactiondetPsgid;
    }

    public void setcTransactiondetPsgid(String cTransactiondetPsgid) {
        this.cTransactiondetPsgid = cTransactiondetPsgid;
    }

    public String getcStamformdetId() {
        return cStamformdetId;
    }

    public void setcStamformdetId(String cStamformdetId) {
        this.cStamformdetId = cStamformdetId;
    }

    public String getcStamformdetCode() {
        return cStamformdetCode;
    }

    public void setcStamformdetCode(String cStamformdetCode) {
        this.cStamformdetCode = cStamformdetCode;
    }

    public String getcWagondetId() {
        return cWagondetId;
    }

    public void setcWagondetId(String cWagondetId) {
        this.cWagondetId = cWagondetId;
    }

    public String getcWagondetRow() {
        return cWagondetRow;
    }

    public void setcWagondetRow(String cWagondetRow) {
        this.cWagondetRow = cWagondetRow;
    }

    public String getcWagondetCol() {
        return cWagondetCol;
    }

    public void setcWagondetCol(String cWagondetCol) {
        this.cWagondetCol = cWagondetCol;
    }

    public BigDecimal getcTransactiondetAmount() {
        return cTransactiondetAmount;
    }

    public void setcTransactiondetAmount(BigDecimal cTransactiondetAmount) {
        this.cTransactiondetAmount = cTransactiondetAmount;
    }

    public String getcTransactiondetTicketnum() {
        return cTransactiondetTicketnum;
    }

    public void setcTransactiondetTicketnum(String cTransactiondetTicketnum) {
        this.cTransactiondetTicketnum = cTransactiondetTicketnum;
    }

    public String getcMemberId() {
        return cMemberId;
    }

    public void setcMemberId(String cMemberId) {
        this.cMemberId = cMemberId;
    }

    public String getcReductionId() {
        return cReductionId;
    }

    public void setcReductionId(String cReductionId) {
        this.cReductionId = cReductionId;
    }

    public String getcReductionName() {
        return cReductionName;
    }

    public void setcReductionName(String cReductionName) {
        this.cReductionName = cReductionName;
    }

    public String getcReductionAmount() {
        return cReductionAmount;
    }

    public void setcReductionAmount(String cReductionAmount) {
        this.cReductionAmount = cReductionAmount;
    }

    public String getcReductionAmounttype() {
        return cReductionAmounttype;
    }

    public void setcReductionAmounttype(String cReductionAmounttype) {
        this.cReductionAmounttype = cReductionAmounttype;
    }

    public String getcReductionAmountconvert() {
        return cReductionAmountconvert;
    }

    public void setcReductionAmountconvert(String cReductionAmountconvert) {
        this.cReductionAmountconvert = cReductionAmountconvert;
    }

    public String getcDiscountId() {
        return cDiscountId;
    }

    public void setcDiscountId(String cDiscountId) {
        this.cDiscountId = cDiscountId;
    }

    public String getcDiscountName() {
        return cDiscountName;
    }

    public void setcDiscountName(String cDiscountName) {
        this.cDiscountName = cDiscountName;
    }

    public String getcDiscountAmount() {
        return cDiscountAmount;
    }

    public void setcDiscountAmount(String cDiscountAmount) {
        this.cDiscountAmount = cDiscountAmount;
    }

    public String getcDiscountAmounttype() {
        return cDiscountAmounttype;
    }

    public void setcDiscountAmounttype(String cDiscountAmounttype) {
        this.cDiscountAmounttype = cDiscountAmounttype;
    }

    public String getcDiscountAmountconvert() {
        return cDiscountAmountconvert;
    }

    public void setcDiscountAmountconvert(String cDiscountAmountconvert) {
        this.cDiscountAmountconvert = cDiscountAmountconvert;
    }

    public String getcFareId() {
        return cFareId;
    }

    public void setcFareId(String cFareId) {
        this.cFareId = cFareId;
    }

    public String getcFareBasicfare() {
        return cFareBasicfare;
    }

    public void setcFareBasicfare(String cFareBasicfare) {
        this.cFareBasicfare = cFareBasicfare;
    }

    public String getcFareTuslahfee() {
        return cFareTuslahfee;
    }

    public void setcFareTuslahfee(String cFareTuslahfee) {
        this.cFareTuslahfee = cFareTuslahfee;
    }

    public String getcFareRsvfee() {
        return cFareRsvfee;
    }

    public void setcFareRsvfee(String cFareRsvfee) {
        this.cFareRsvfee = cFareRsvfee;
    }

    public Integer getcFareStfee() {
        return cFareStfee;
    }

    public void setcFareStfee(Integer cFareStfee) {
        this.cFareStfee = cFareStfee;
    }

    public String getcFareAddfee() {
        return cFareAddfee;
    }

    public void setcFareAddfee(String cFareAddfee) {
        this.cFareAddfee = cFareAddfee;
    }

    public String getcFareCompinsurance() {
        return cFareCompinsurance;
    }

    public void setcFareCompinsurance(String cFareCompinsurance) {
        this.cFareCompinsurance = cFareCompinsurance;
    }

    public String getcFareAddinsurance() {
        return cFareAddinsurance;
    }

    public void setcFareAddinsurance(String cFareAddinsurance) {
        this.cFareAddinsurance = cFareAddinsurance;
    }

    public String getcFarePsofare() {
        return cFarePsofare;
    }

    public void setcFarePsofare(String cFarePsofare) {
        this.cFarePsofare = cFarePsofare;
    }

    public String getcFareTotamount() {
        return cFareTotamount;
    }

    public void setcFareTotamount(String cFareTotamount) {
        this.cFareTotamount = cFareTotamount;
    }

    public String getcFlexiId() {
        return cFlexiId;
    }

    public void setcFlexiId(String cFlexiId) {
        this.cFlexiId = cFlexiId;
    }

    public String getcFlexiCode() {
        return cFlexiCode;
    }

    public void setcFlexiCode(String cFlexiCode) {
        this.cFlexiCode = cFlexiCode;
    }

    public String getcStasiunIdgatein() {
        return cStasiunIdgatein;
    }

    public void setcStasiunIdgatein(String cStasiunIdgatein) {
        this.cStasiunIdgatein = cStasiunIdgatein;
    }

    public String getcStasiunCodegateind() {
        return cStasiunCodegateind;
    }

    public void setcStasiunCodegateind(String cStasiunCodegateind) {
        this.cStasiunCodegateind = cStasiunCodegateind;
    }

    public String getcUnitIdgatein() {
        return cUnitIdgatein;
    }

    public void setcUnitIdgatein(String cUnitIdgatein) {
        this.cUnitIdgatein = cUnitIdgatein;
    }

    public String getcUnitCodegatein() {
        return cUnitCodegatein;
    }

    public void setcUnitCodegatein(String cUnitCodegatein) {
        this.cUnitCodegatein = cUnitCodegatein;
    }

    public Date getcTransactiondetGateinon() {
        return cTransactiondetGateinon;
    }

    public void setcTransactiondetGateinon(Date cTransactiondetGateinon) {
        this.cTransactiondetGateinon = cTransactiondetGateinon;
    }

    public String getcStasiunIdgateout() {
        return cStasiunIdgateout;
    }

    public void setcStasiunIdgateout(String cStasiunIdgateout) {
        this.cStasiunIdgateout = cStasiunIdgateout;
    }

    public String getcStasiunCodegateout() {
        return cStasiunCodegateout;
    }

    public void setcStasiunCodegateout(String cStasiunCodegateout) {
        this.cStasiunCodegateout = cStasiunCodegateout;
    }

    public String getcUnitIdgateout() {
        return cUnitIdgateout;
    }

    public void setcUnitIdgateout(String cUnitIdgateout) {
        this.cUnitIdgateout = cUnitIdgateout;
    }

    public String getcUnitCodegateout() {
        return cUnitCodegateout;
    }

    public void setcUnitCodegateout(String cUnitCodegateout) {
        this.cUnitCodegateout = cUnitCodegateout;
    }

    public String getcTransactiondetGateouton() {
        return cTransactiondetGateouton;
    }

    public void setcTransactiondetGateouton(String cTransactiondetGateouton) {
        this.cTransactiondetGateouton = cTransactiondetGateouton;
    }

    public short getcTransactiondetMaxPrint() {
        return cTransactiondetMaxPrint;
    }

    public void setcTransactiondetMaxPrint(short cTransactiondetMaxPrint) {
        this.cTransactiondetMaxPrint = cTransactiondetMaxPrint;
    }

    public short getcTransactiondetRef() {
        return cTransactiondetRef;
    }

    public void setcTransactiondetRef(short cTransactiondetRef) {
        this.cTransactiondetRef = cTransactiondetRef;
    }

    public short getcTransactiondetStatus() {
        return cTransactiondetStatus;
    }

    public void setcTransactiondetStatus(short cTransactiondetStatus) {
        this.cTransactiondetStatus = cTransactiondetStatus;
    }

    public String getcTransactiondetDomain() {
        return cTransactiondetDomain;
    }

    public void setcTransactiondetDomain(String cTransactiondetDomain) {
        this.cTransactiondetDomain = cTransactiondetDomain;
    }

    public String getcTransactiondetModifiedby() {
        return cTransactiondetModifiedby;
    }

    public void setcTransactiondetModifiedby(String cTransactiondetModifiedby) {
        this.cTransactiondetModifiedby = cTransactiondetModifiedby;
    }

    public Date getcTransactiondetModifiedon() {
        return cTransactiondetModifiedon;
    }

    public void setcTransactiondetModifiedon(Date cTransactiondetModifiedon) {
        this.cTransactiondetModifiedon = cTransactiondetModifiedon;
    }

    public String getcTransactiondetCreatedby() {
        return cTransactiondetCreatedby;
    }

    public void setcTransactiondetCreatedby(String cTransactiondetCreatedby) {
        this.cTransactiondetCreatedby = cTransactiondetCreatedby;
    }

    public Date getcTransactiondetCreatedon() {
        return cTransactiondetCreatedon;
    }

    public void setcTransactiondetCreatedon(Date cTransactiondetCreatedon) {
        this.cTransactiondetCreatedon = cTransactiondetCreatedon;
    }

    

}
