/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.transactions;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_transaction")
public class Transaction {

    @Column(name = "c_transaction_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_transaction_bookcode", table = "arts_t_transaction", nullable = false, length = 20)
    @Basic
    private String cTransactionBookcode;

    @Column(name = "c_transaction_paycode", table = "arts_t_transaction", nullable = false, length = 20)
    @Basic
    private String cTransactionPaycode;

    @Column(name = "c_transaction_transdate", table = "arts_t_transaction", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionTransdate;

    @Column(name = "c_transaction_departdate", table = "arts_t_transaction", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionDepartdate;

    @Column(name = "c_transaction_totamount", table = "arts_t_transaction", scale = 2, precision = 11)
    @Basic
    private BigDecimal cTransactionTotamount;

    @Column(name = "c_transaction_extrafee", table = "arts_t_transaction", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cTransactionExtrafee;

    @Column(name = "c_transaction_netamount", table = "arts_t_transaction", scale = 2, precision = 11)
    @Basic
    private BigDecimal cTransactionNetamount;

    @Column(name = "c_transaction_paidamount", table = "arts_t_transaction", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cTransactionPaidamount;

    @Column(name = "c_transaction_custname", table = "arts_t_transaction", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cTransactionCustname;

    @Column(name = "c_transaction_phonenum", table = "arts_t_transaction", length = 36)
    @Basic
    private String cTransactionPhonenum;

    @Column(name = "c_transaction_email", table = "arts_t_transaction", length = 100)
    @Basic
    private String cTransactionEmail;

    @Column(name = "c_transaction_totpsgadult", table = "arts_t_transaction", nullable = false)
    @Basic
    private double cTransactionTotpsgadult;

    @Column(name = "c_transaction_totpsgchild", table = "arts_t_transaction", precision = 22)
    @Basic
    private Double cTransactionTotpsgchild;

    @Column(name = "c_transaction_totpsginfant", table = "arts_t_transaction", precision = 22)
    @Basic
    private Double cTransactionTotpsginfant;

    @Column(name = "c_stasiun_idorg", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cStasiunIdorg;

    @Column(name = "c_stasiun_codeorg", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cStasiunCodeorg;

    @Column(name = "c_stasiun_iddes", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cStasiunIddes;

    @Column(name = "c_stasiun_codedes", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cStasiunCodedes;

    @Column(name = "c_schedule_id", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cScheduleId;

    @Column(name = "c_schedule_noka", table = "arts_t_transaction", nullable = false, length = 50)
    @Basic
    private String cScheduleNoka;

    @Column(name = "c_schedule_localstat", table = "arts_t_transaction", nullable = false)
    @Basic
    private Character cScheduleLocalstat;

    @Column(name = "c_schedule_trainname", table = "arts_t_transaction", nullable = false)
    @Basic
    private Character cScheduleTrainname;

    @Column(name = "c_trip_id", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_trip_date", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cTripDate;

    @Column(name = "c_subclass_id", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cSubclassId;

    @Column(name = "c_subclass_code", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cSubclassCode;

    @Column(name = "c_paytype_id", table = "arts_t_transaction", length = 36)
    @Basic
    private String cPaytypeId;

    @Column(name = "c_paytype_code", table = "arts_t_transaction", length = 36)
    @Basic
    private String cPaytypeCode;

    @Column(name = "c_user_idbook", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cUserIdbook;

    @Column(name = "c_user_fullnamebook", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cUserFullnamebook;

    @Column(name = "c_unit_idbook", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUnitIdbook;

    @Column(name = "c_unit_codebook", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUnitCodebook;

    @Column(name = "c_shift_idbook", table = "arts_t_transaction", length = 36)
    @Basic
    private String cShiftIdbook;

    @Column(name = "c_channel_idbook", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cChannelIdbook;

    @Column(name = "c_channel_codebook", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cChannelCodebook;

    @Column(name = "c_user_idpay", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUserIdpay;

    @Column(name = "c_user_fullnamepay", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUserFullnamepay;

    @Column(name = "c_unit_idpay", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUnitIdpay;

    @Column(name = "c_unit_codepay", table = "arts_t_transaction", length = 36)
    @Basic
    private String cUnitCodepay;

    @Column(name = "c_shift_idpay", table = "arts_t_transaction", length = 36)
    @Basic
    private String cShiftIdpay;

    @Column(name = "c_channel_idpay", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cChannelIdpay;

    @Column(name = "c_channel_codepay", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cChannelCodepay;

    @Column(name = "c_transaction_bookedon", table = "arts_t_transaction")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionBookedon;

    @Column(name = "c_transaction_booktimeouton", table = "arts_t_transaction")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionBooktimeouton;

    @Column(name = "c_transaction_paytimeouton", table = "arts_t_transaction")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionPaytimeouton;

    @Column(name = "c_transaction_paidon", table = "arts_t_transaction")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionPaidon;

    @Column(name = "c_transaction_smsbooksent", table = "arts_t_transaction")
    @Basic
    private Character cTransactionSmsbooksent;

    @Column(name = "c_transaction_emailbooksent", table = "arts_t_transaction")
    @Basic
    private Character cTransactionEmailbooksent;

    @Column(name = "c_transaction_smspaysent", table = "arts_t_transaction")
    @Basic
    private Character cTransactionSmspaysent;

    @Column(name = "c_transaction_emailpaysent", table = "arts_t_transaction")
    @Basic
    private Character cTransactionEmailpaysent;

    @Column(name = "c_transaction_reroutestat", table = "arts_t_transaction")
    @Basic
    private Character cTransactionReroutestat;

    @Column(name = "c_transaction_flexiredeemstat", table = "arts_t_transaction")
    @Basic
    private Character cTransactionFlexiredeemstat;

    @Column(name = "c_transaction_ref1", table = "arts_t_transaction", length = 100)
    @Basic
    private String cTransactionRef1;

    @Column(name = "c_transaction_ref2", table = "arts_t_transaction", length = 100)
    @Basic
    private String cTransactionRef2;

    @Column(name = "c_transaction_ref3", table = "arts_t_transaction", length = 100)
    @Basic
    private String cTransactionRef3;

    @Column(name = "c_voucher_id", table = "arts_t_transaction", length = 36)
    @Basic
    private String cVoucherId;

    @Column(name = "c_voucher_code", table = "arts_t_transaction", length = 36)
    @Basic
    private String cVoucherCode;

    @Column(name = "c_voucher_amount", table = "arts_t_transaction", length = 36)
    @Basic
    private String cVoucherAmount;

    @Column(name = "c_voucher_amounttype", table = "arts_t_transaction", length = 36)
    @Basic
    private String cVoucherAmounttype;

    @Column(name = "c_voucher_amountconvert", table = "arts_t_transaction", length = 36)
    @Basic
    private String cVoucherAmountconvert;

    @Column(name = "c_transaction_status", table = "arts_t_transaction", nullable = false)
    @Basic
    private Character cTransactionStatus;

    @Column(name = "c_transaction_domain", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cTransactionDomain;

    @Column(name = "c_transaction_createdby", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cTransactionCreatedby;

    @Column(name = "c_transaction_createdon", table = "arts_t_transaction", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionCreatedon;

    @Column(name = "c_transaction_modifiedby", table = "arts_t_transaction", nullable = false, length = 36)
    @Basic
    private String cTransactionModifiedby;

    @Column(name = "c_transaction_modifiedon", table = "arts_t_transaction", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cTransactionModifiedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcTransactionBookcode() {
        return cTransactionBookcode;
    }

    public void setcTransactionBookcode(String cTransactionBookcode) {
        this.cTransactionBookcode = cTransactionBookcode;
    }

    public String getcTransactionPaycode() {
        return cTransactionPaycode;
    }

    public void setcTransactionPaycode(String cTransactionPaycode) {
        this.cTransactionPaycode = cTransactionPaycode;
    }

    public Date getcTransactionTransdate() {
        return cTransactionTransdate;
    }

    public void setcTransactionTransdate(Date cTransactionTransdate) {
        this.cTransactionTransdate = cTransactionTransdate;
    }

    public Date getcTransactionDepartdate() {
        return cTransactionDepartdate;
    }

    public void setcTransactionDepartdate(Date cTransactionDepartdate) {
        this.cTransactionDepartdate = cTransactionDepartdate;
    }

    public BigDecimal getcTransactionTotamount() {
        return cTransactionTotamount;
    }

    public void setcTransactionTotamount(BigDecimal cTransactionTotamount) {
        this.cTransactionTotamount = cTransactionTotamount;
    }

    public BigDecimal getcTransactionExtrafee() {
        return cTransactionExtrafee;
    }

    public void setcTransactionExtrafee(BigDecimal cTransactionExtrafee) {
        this.cTransactionExtrafee = cTransactionExtrafee;
    }

    public BigDecimal getcTransactionNetamount() {
        return cTransactionNetamount;
    }

    public void setcTransactionNetamount(BigDecimal cTransactionNetamount) {
        this.cTransactionNetamount = cTransactionNetamount;
    }

    public BigDecimal getcTransactionPaidamount() {
        return cTransactionPaidamount;
    }

    public void setcTransactionPaidamount(BigDecimal cTransactionPaidamount) {
        this.cTransactionPaidamount = cTransactionPaidamount;
    }

    public BigDecimal getcTransactionCustname() {
        return cTransactionCustname;
    }

    public void setcTransactionCustname(BigDecimal cTransactionCustname) {
        this.cTransactionCustname = cTransactionCustname;
    }

    public String getcTransactionPhonenum() {
        return cTransactionPhonenum;
    }

    public void setcTransactionPhonenum(String cTransactionPhonenum) {
        this.cTransactionPhonenum = cTransactionPhonenum;
    }

    public String getcTransactionEmail() {
        return cTransactionEmail;
    }

    public void setcTransactionEmail(String cTransactionEmail) {
        this.cTransactionEmail = cTransactionEmail;
    }

    public double getcTransactionTotpsgadult() {
        return cTransactionTotpsgadult;
    }

    public void setcTransactionTotpsgadult(double cTransactionTotpsgadult) {
        this.cTransactionTotpsgadult = cTransactionTotpsgadult;
    }

    public Double getcTransactionTotpsgchild() {
        return cTransactionTotpsgchild;
    }

    public void setcTransactionTotpsgchild(Double cTransactionTotpsgchild) {
        this.cTransactionTotpsgchild = cTransactionTotpsgchild;
    }

    public Double getcTransactionTotpsginfant() {
        return cTransactionTotpsginfant;
    }

    public void setcTransactionTotpsginfant(Double cTransactionTotpsginfant) {
        this.cTransactionTotpsginfant = cTransactionTotpsginfant;
    }

    public String getcStasiunIdorg() {
        return cStasiunIdorg;
    }

    public void setcStasiunIdorg(String cStasiunIdorg) {
        this.cStasiunIdorg = cStasiunIdorg;
    }

    public String getcStasiunCodeorg() {
        return cStasiunCodeorg;
    }

    public void setcStasiunCodeorg(String cStasiunCodeorg) {
        this.cStasiunCodeorg = cStasiunCodeorg;
    }

    public String getcStasiunIddes() {
        return cStasiunIddes;
    }

    public void setcStasiunIddes(String cStasiunIddes) {
        this.cStasiunIddes = cStasiunIddes;
    }

    public String getcStasiunCodedes() {
        return cStasiunCodedes;
    }

    public void setcStasiunCodedes(String cStasiunCodedes) {
        this.cStasiunCodedes = cStasiunCodedes;
    }

    public String getcScheduleId() {
        return cScheduleId;
    }

    public void setcScheduleId(String cScheduleId) {
        this.cScheduleId = cScheduleId;
    }

    public String getcScheduleNoka() {
        return cScheduleNoka;
    }

    public void setcScheduleNoka(String cScheduleNoka) {
        this.cScheduleNoka = cScheduleNoka;
    }

    public Character getcScheduleLocalstat() {
        return cScheduleLocalstat;
    }

    public void setcScheduleLocalstat(Character cScheduleLocalstat) {
        this.cScheduleLocalstat = cScheduleLocalstat;
    }

    public Character getcScheduleTrainname() {
        return cScheduleTrainname;
    }

    public void setcScheduleTrainname(Character cScheduleTrainname) {
        this.cScheduleTrainname = cScheduleTrainname;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public String getcTripDate() {
        return cTripDate;
    }

    public void setcTripDate(String cTripDate) {
        this.cTripDate = cTripDate;
    }

    public String getcSubclassId() {
        return cSubclassId;
    }

    public void setcSubclassId(String cSubclassId) {
        this.cSubclassId = cSubclassId;
    }

    public String getcSubclassCode() {
        return cSubclassCode;
    }

    public void setcSubclassCode(String cSubclassCode) {
        this.cSubclassCode = cSubclassCode;
    }

    public String getcPaytypeId() {
        return cPaytypeId;
    }

    public void setcPaytypeId(String cPaytypeId) {
        this.cPaytypeId = cPaytypeId;
    }

    public String getcPaytypeCode() {
        return cPaytypeCode;
    }

    public void setcPaytypeCode(String cPaytypeCode) {
        this.cPaytypeCode = cPaytypeCode;
    }

    public String getcUserIdbook() {
        return cUserIdbook;
    }

    public void setcUserIdbook(String cUserIdbook) {
        this.cUserIdbook = cUserIdbook;
    }

    public String getcUserFullnamebook() {
        return cUserFullnamebook;
    }

    public void setcUserFullnamebook(String cUserFullnamebook) {
        this.cUserFullnamebook = cUserFullnamebook;
    }

    public String getcUnitIdbook() {
        return cUnitIdbook;
    }

    public void setcUnitIdbook(String cUnitIdbook) {
        this.cUnitIdbook = cUnitIdbook;
    }

    public String getcUnitCodebook() {
        return cUnitCodebook;
    }

    public void setcUnitCodebook(String cUnitCodebook) {
        this.cUnitCodebook = cUnitCodebook;
    }

    public String getcShiftIdbook() {
        return cShiftIdbook;
    }

    public void setcShiftIdbook(String cShiftIdbook) {
        this.cShiftIdbook = cShiftIdbook;
    }

    public String getcChannelIdbook() {
        return cChannelIdbook;
    }

    public void setcChannelIdbook(String cChannelIdbook) {
        this.cChannelIdbook = cChannelIdbook;
    }

    public String getcChannelCodebook() {
        return cChannelCodebook;
    }

    public void setcChannelCodebook(String cChannelCodebook) {
        this.cChannelCodebook = cChannelCodebook;
    }

    public String getcUserIdpay() {
        return cUserIdpay;
    }

    public void setcUserIdpay(String cUserIdpay) {
        this.cUserIdpay = cUserIdpay;
    }

    public String getcUserFullnamepay() {
        return cUserFullnamepay;
    }

    public void setcUserFullnamepay(String cUserFullnamepay) {
        this.cUserFullnamepay = cUserFullnamepay;
    }

    public String getcUnitIdpay() {
        return cUnitIdpay;
    }

    public void setcUnitIdpay(String cUnitIdpay) {
        this.cUnitIdpay = cUnitIdpay;
    }

    public String getcUnitCodepay() {
        return cUnitCodepay;
    }

    public void setcUnitCodepay(String cUnitCodepay) {
        this.cUnitCodepay = cUnitCodepay;
    }

    public String getcShiftIdpay() {
        return cShiftIdpay;
    }

    public void setcShiftIdpay(String cShiftIdpay) {
        this.cShiftIdpay = cShiftIdpay;
    }

    public String getcChannelIdpay() {
        return cChannelIdpay;
    }

    public void setcChannelIdpay(String cChannelIdpay) {
        this.cChannelIdpay = cChannelIdpay;
    }

    public String getcChannelCodepay() {
        return cChannelCodepay;
    }

    public void setcChannelCodepay(String cChannelCodepay) {
        this.cChannelCodepay = cChannelCodepay;
    }

    public Date getcTransactionBookedon() {
        return cTransactionBookedon;
    }

    public void setcTransactionBookedon(Date cTransactionBookedon) {
        this.cTransactionBookedon = cTransactionBookedon;
    }

    public Date getcTransactionBooktimeouton() {
        return cTransactionBooktimeouton;
    }

    public void setcTransactionBooktimeouton(Date cTransactionBooktimeouton) {
        this.cTransactionBooktimeouton = cTransactionBooktimeouton;
    }

    public Date getcTransactionPaytimeouton() {
        return cTransactionPaytimeouton;
    }

    public void setcTransactionPaytimeouton(Date cTransactionPaytimeouton) {
        this.cTransactionPaytimeouton = cTransactionPaytimeouton;
    }

    public Date getcTransactionPaidon() {
        return cTransactionPaidon;
    }

    public void setcTransactionPaidon(Date cTransactionPaidon) {
        this.cTransactionPaidon = cTransactionPaidon;
    }

    public Character getcTransactionSmsbooksent() {
        return cTransactionSmsbooksent;
    }

    public void setcTransactionSmsbooksent(Character cTransactionSmsbooksent) {
        this.cTransactionSmsbooksent = cTransactionSmsbooksent;
    }

    public Character getcTransactionEmailbooksent() {
        return cTransactionEmailbooksent;
    }

    public void setcTransactionEmailbooksent(Character cTransactionEmailbooksent) {
        this.cTransactionEmailbooksent = cTransactionEmailbooksent;
    }

    public Character getcTransactionSmspaysent() {
        return cTransactionSmspaysent;
    }

    public void setcTransactionSmspaysent(Character cTransactionSmspaysent) {
        this.cTransactionSmspaysent = cTransactionSmspaysent;
    }

    public Character getcTransactionEmailpaysent() {
        return cTransactionEmailpaysent;
    }

    public void setcTransactionEmailpaysent(Character cTransactionEmailpaysent) {
        this.cTransactionEmailpaysent = cTransactionEmailpaysent;
    }

    public Character getcTransactionReroutestat() {
        return cTransactionReroutestat;
    }

    public void setcTransactionReroutestat(Character cTransactionReroutestat) {
        this.cTransactionReroutestat = cTransactionReroutestat;
    }

    public Character getcTransactionFlexiredeemstat() {
        return cTransactionFlexiredeemstat;
    }

    public void setcTransactionFlexiredeemstat(Character cTransactionFlexiredeemstat) {
        this.cTransactionFlexiredeemstat = cTransactionFlexiredeemstat;
    }

    public String getcTransactionRef1() {
        return cTransactionRef1;
    }

    public void setcTransactionRef1(String cTransactionRef1) {
        this.cTransactionRef1 = cTransactionRef1;
    }

    public String getcTransactionRef2() {
        return cTransactionRef2;
    }

    public void setcTransactionRef2(String cTransactionRef2) {
        this.cTransactionRef2 = cTransactionRef2;
    }

    public String getcTransactionRef3() {
        return cTransactionRef3;
    }

    public void setcTransactionRef3(String cTransactionRef3) {
        this.cTransactionRef3 = cTransactionRef3;
    }

    public String getcVoucherId() {
        return cVoucherId;
    }

    public void setcVoucherId(String cVoucherId) {
        this.cVoucherId = cVoucherId;
    }

    public String getcVoucherCode() {
        return cVoucherCode;
    }

    public void setcVoucherCode(String cVoucherCode) {
        this.cVoucherCode = cVoucherCode;
    }

    public String getcVoucherAmount() {
        return cVoucherAmount;
    }

    public void setcVoucherAmount(String cVoucherAmount) {
        this.cVoucherAmount = cVoucherAmount;
    }

    public String getcVoucherAmounttype() {
        return cVoucherAmounttype;
    }

    public void setcVoucherAmounttype(String cVoucherAmounttype) {
        this.cVoucherAmounttype = cVoucherAmounttype;
    }

    public String getcVoucherAmountconvert() {
        return cVoucherAmountconvert;
    }

    public void setcVoucherAmountconvert(String cVoucherAmountconvert) {
        this.cVoucherAmountconvert = cVoucherAmountconvert;
    }

    public Character getcTransactionStatus() {
        return cTransactionStatus;
    }

    public void setcTransactionStatus(Character cTransactionStatus) {
        this.cTransactionStatus = cTransactionStatus;
    }

    public String getcTransactionDomain() {
        return cTransactionDomain;
    }

    public void setcTransactionDomain(String cTransactionDomain) {
        this.cTransactionDomain = cTransactionDomain;
    }

    public String getcTransactionCreatedby() {
        return cTransactionCreatedby;
    }

    public void setcTransactionCreatedby(String cTransactionCreatedby) {
        this.cTransactionCreatedby = cTransactionCreatedby;
    }

    public Date getcTransactionCreatedon() {
        return cTransactionCreatedon;
    }

    public void setcTransactionCreatedon(Date cTransactionCreatedon) {
        this.cTransactionCreatedon = cTransactionCreatedon;
    }

    public String getcTransactionModifiedby() {
        return cTransactionModifiedby;
    }

    public void setcTransactionModifiedby(String cTransactionModifiedby) {
        this.cTransactionModifiedby = cTransactionModifiedby;
    }

    public Date getcTransactionModifiedon() {
        return cTransactionModifiedon;
    }

    public void setcTransactionModifiedon(Date cTransactionModifiedon) {
        this.cTransactionModifiedon = cTransactionModifiedon;
    }

    
}
