/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.log;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_seatlog")
public class Seatlog {

    @Column(name = "c_seatlog_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_wagondet_id", table = "arts_t_seatlog", nullable = false, length = 36)
    @Basic
    private String cWagondetId;

    @Column(name = "c_seatlog_date", table = "arts_t_seatlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSeatlogDate;

    @Column(name = "c_seatlog_status", table = "arts_t_seatlog", nullable = false)
    @Basic
    private Character cSeatlogStatus;

    @Column(name = "c_seatlog_wagonorder", table = "arts_t_seatlog", nullable = false)
    @Basic
    private short cSeatlogWagonorder;

    @Column(name = "c_seatlog_domain", table = "arts_t_seatlog", nullable = false, length = 36)
    @Basic
    private String cSeatlogDomain;

    @Column(name = "c_user_id", table = "arts_t_seatlog", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_seatlog_object", table = "arts_t_seatlog", nullable = false, length = 50)
    @Basic
    private String cSeatlogObject;

    @Column(name = "c_seatlog_objectid", table = "arts_t_seatlog", nullable = false, length = 36)
    @Basic
    private String cSeatlogObjectid;

    @Column(name = "c_seatlog_action", table = "arts_t_seatlog", nullable = false, length = 50)
    @Basic
    private String cSeatlogAction;

    @Column(name = "c_seatlog_value", table = "arts_t_seatlog", nullable = false, length = 2147483647)
    @Lob
    @Basic
    private String cSeatlogValue;

    @Column(name = "c_seatlog_createdby", table = "arts_t_seatlog", nullable = false, length = 36)
    @Basic
    private String cSeatlogCreatedby;

    @Column(name = "c_seatlog_createdon", table = "arts_t_seatlog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSeatlogCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcWagondetId() {
        return cWagondetId;
    }

    public void setcWagondetId(String cWagondetId) {
        this.cWagondetId = cWagondetId;
    }

    public Date getcSeatlogDate() {
        return cSeatlogDate;
    }

    public void setcSeatlogDate(Date cSeatlogDate) {
        this.cSeatlogDate = cSeatlogDate;
    }

    public Character getcSeatlogStatus() {
        return cSeatlogStatus;
    }

    public void setcSeatlogStatus(Character cSeatlogStatus) {
        this.cSeatlogStatus = cSeatlogStatus;
    }

    public short getcSeatlogWagonorder() {
        return cSeatlogWagonorder;
    }

    public void setcSeatlogWagonorder(short cSeatlogWagonorder) {
        this.cSeatlogWagonorder = cSeatlogWagonorder;
    }

    public String getcSeatlogDomain() {
        return cSeatlogDomain;
    }

    public void setcSeatlogDomain(String cSeatlogDomain) {
        this.cSeatlogDomain = cSeatlogDomain;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcSeatlogObject() {
        return cSeatlogObject;
    }

    public void setcSeatlogObject(String cSeatlogObject) {
        this.cSeatlogObject = cSeatlogObject;
    }

    public String getcSeatlogObjectid() {
        return cSeatlogObjectid;
    }

    public void setcSeatlogObjectid(String cSeatlogObjectid) {
        this.cSeatlogObjectid = cSeatlogObjectid;
    }

    public String getcSeatlogAction() {
        return cSeatlogAction;
    }

    public void setcSeatlogAction(String cSeatlogAction) {
        this.cSeatlogAction = cSeatlogAction;
    }

    public String getcSeatlogValue() {
        return cSeatlogValue;
    }

    public void setcSeatlogValue(String cSeatlogValue) {
        this.cSeatlogValue = cSeatlogValue;
    }

    public String getcSeatlogCreatedby() {
        return cSeatlogCreatedby;
    }

    public void setcSeatlogCreatedby(String cSeatlogCreatedby) {
        this.cSeatlogCreatedby = cSeatlogCreatedby;
    }

    public Date getcSeatlogCreatedon() {
        return cSeatlogCreatedon;
    }

    public void setcSeatlogCreatedon(Date cSeatlogCreatedon) {
        this.cSeatlogCreatedon = cSeatlogCreatedon;
    }

    

}
