/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.log;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_wslog")
public class Wslog implements Serializable {

    @Column(name = "c_wslog_id", table = "arts_t_wslog", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_wslog_reqtime", table = "arts_t_wslog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cWslogReqtime;

    @Column(name = "c_wslog_ip", table = "arts_t_wslog", nullable = false, length = 20)
    @Basic
    private String cWslogIp;

    @Column(name = "c_wslog_req", table = "arts_t_wslog", nullable = false, length = 2147483647)
    @Lob
    @Basic
    private String cWslogReq;

    @Column(name = "c_wslog_res", table = "arts_t_wslog", length = 2147483647)
    @Lob
    @Basic
    private String cWslogRes;

    @Column(name = "c_wslog_errcode", table = "arts_t_wslog", length = 10)
    @Basic
    private String cWslogErrcode;

    @Column(name = "c_wslog_status", table = "arts_t_wslog", nullable = false)
    @Basic
    private Character cWslogStatus;

    @Column(name = "c_wslog_domain", table = "arts_t_wslog", length = 36)
    @Basic
    private String cWslogDomain;

    @Column(name = "c_user_id", table = "arts_t_wslog", length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_wslog_restime", table = "arts_t_wslog")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cWslogRestime;

    @Column(name = "c_wslog_createdby", table = "arts_t_wslog", nullable = false, length = 36)
    @Basic
    private String cWslogCreatedby;

    @Column(name = "c_wslog_createdon", table = "arts_t_wslog", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cWslogCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcWslogReqtime() {
        return cWslogReqtime;
    }

    public void setcWslogReqtime(Date cWslogReqtime) {
        this.cWslogReqtime = cWslogReqtime;
    }

    public String getcWslogIp() {
        return cWslogIp;
    }

    public void setcWslogIp(String cWslogIp) {
        this.cWslogIp = cWslogIp;
    }

    public String getcWslogReq() {
        return cWslogReq;
    }

    public void setcWslogReq(String cWslogReq) {
        this.cWslogReq = cWslogReq;
    }

    public String getcWslogRes() {
        return cWslogRes;
    }

    public void setcWslogRes(String cWslogRes) {
        this.cWslogRes = cWslogRes;
    }

    public String getcWslogErrcode() {
        return cWslogErrcode;
    }

    public void setcWslogErrcode(String cWslogErrcode) {
        this.cWslogErrcode = cWslogErrcode;
    }

    public Character getcWslogStatus() {
        return cWslogStatus;
    }

    public void setcWslogStatus(Character cWslogStatus) {
        this.cWslogStatus = cWslogStatus;
    }

    public String getcWslogDomain() {
        return cWslogDomain;
    }

    public void setcWslogDomain(String cWslogDomain) {
        this.cWslogDomain = cWslogDomain;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public Date getcWslogRestime() {
        return cWslogRestime;
    }

    public void setcWslogRestime(Date cWslogRestime) {
        this.cWslogRestime = cWslogRestime;
    }

    public String getcWslogCreatedby() {
        return cWslogCreatedby;
    }

    public void setcWslogCreatedby(String cWslogCreatedby) {
        this.cWslogCreatedby = cWslogCreatedby;
    }

    public Date getcWslogCreatedon() {
        return cWslogCreatedon;
    }

    public void setcWslogCreatedon(Date cWslogCreatedon) {
        this.cWslogCreatedon = cWslogCreatedon;
    }
    
    
}
