/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.schedule;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_allocdetsubcl", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_subclass_id", "c_allocdet_id", "c_stop_id"})})
public class Allocdetsubcl implements Serializable {

    @Column(name = "c_adsc_id", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_subclass_id", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cSubclassId;

    @Column(name = "c_adsc_maxsell", table = "arts_t_allocdetsubcl", nullable = false)
    @Basic
    private int cAdscMaxsell;

    @Column(name = "c_adsc_status", table = "arts_t_allocdetsubcl", nullable = false)
    @Basic
    private Character cAdscStatus;

    @Column(name = "c_adsc_domain", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cAdscDomain;

    @Column(name = "c_adsc_modifiedby", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cAdscModifiedby;

    @Column(name = "c_adsc_modifiedon", table = "arts_t_allocdetsubcl", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAdscModifiedon;

    @Column(name = "c_allocdet_id", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cAllocdetId;

    @Column(name = "c_stop_id", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cStopId;

    @Column(name = "c_adsc_noseatable", table = "arts_t_allocdetsubcl", nullable = false)
    @Basic
    private Character cAdscNoseatable;

    @Column(name = "c_adsc_order", table = "arts_t_allocdetsubcl")
    @Basic
    private Integer cAdscOrder;

    @Column(name = "c_adsc_createdby", table = "arts_t_allocdetsubcl", nullable = false, length = 36)
    @Basic
    private String cAdscCreatedby;

    @Column(name = "c_adsc_createdon", table = "arts_t_allocdetsubcl", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAdscCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcSubclassId() {
        return cSubclassId;
    }

    public void setcSubclassId(String cSubclassId) {
        this.cSubclassId = cSubclassId;
    }

    public int getcAdscMaxsell() {
        return cAdscMaxsell;
    }

    public void setcAdscMaxsell(int cAdscMaxsell) {
        this.cAdscMaxsell = cAdscMaxsell;
    }

    public Character getcAdscStatus() {
        return cAdscStatus;
    }

    public void setcAdscStatus(Character cAdscStatus) {
        this.cAdscStatus = cAdscStatus;
    }

    public String getcAdscDomain() {
        return cAdscDomain;
    }

    public void setcAdscDomain(String cAdscDomain) {
        this.cAdscDomain = cAdscDomain;
    }

    public String getcAdscModifiedby() {
        return cAdscModifiedby;
    }

    public void setcAdscModifiedby(String cAdscModifiedby) {
        this.cAdscModifiedby = cAdscModifiedby;
    }

    public Date getcAdscModifiedon() {
        return cAdscModifiedon;
    }

    public void setcAdscModifiedon(Date cAdscModifiedon) {
        this.cAdscModifiedon = cAdscModifiedon;
    }

    public String getcAllocdetId() {
        return cAllocdetId;
    }

    public void setcAllocdetId(String cAllocdetId) {
        this.cAllocdetId = cAllocdetId;
    }

    public String getcStopId() {
        return cStopId;
    }

    public void setcStopId(String cStopId) {
        this.cStopId = cStopId;
    }

    public Character getcAdscNoseatable() {
        return cAdscNoseatable;
    }

    public void setcAdscNoseatable(Character cAdscNoseatable) {
        this.cAdscNoseatable = cAdscNoseatable;
    }

    public Integer getcAdscOrder() {
        return cAdscOrder;
    }

    public void setcAdscOrder(Integer cAdscOrder) {
        this.cAdscOrder = cAdscOrder;
    }

    public String getcAdscCreatedby() {
        return cAdscCreatedby;
    }

    public void setcAdscCreatedby(String cAdscCreatedby) {
        this.cAdscCreatedby = cAdscCreatedby;
    }

    public Date getcAdscCreatedon() {
        return cAdscCreatedon;
    }

    public void setcAdscCreatedon(Date cAdscCreatedon) {
        this.cAdscCreatedon = cAdscCreatedon;
    }

   

}
