/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.schedule;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_allocdet")
public class Allocdet {

    @Column(name = "c_allocdet_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_allocdet_status", table = "arts_t_allocdet", nullable = false)
    @Basic
    private Character cAllocdetStatus;

    @Column(name = "c_allocdet_domain", table = "arts_t_allocdet", nullable = false, length = 36)
    @Basic
    private String cAllocdetDomain;

    @Column(name = "c_allocdet_modifiedby", table = "arts_t_allocdet", nullable = false, length = 36)
    @Basic
    private String cAllocdetModifiedby;

    @Column(name = "c_allocdet_modifiedon", table = "arts_t_allocdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAllocdetModifiedon;

    @Column(name = "c_allocdet_maxsell", table = "arts_t_allocdet", nullable = false)
    @Basic
    private int cAllocdetMaxsell;

    @Column(name = "c_wagonclass_id", table = "arts_t_allocdet", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_stop_id", table = "arts_t_allocdet", nullable = false, length = 36)
    @Basic
    private String cStopId;

    @Column(name = "c_allocdet_maxcapacity", table = "arts_t_allocdet", nullable = false)
    @Basic
    private double cAllocdetMaxcapacity;

    @Column(name = "c_trip_id", table = "arts_t_allocdet", length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_allocdet_order", table = "arts_t_allocdet", nullable = false)
    @Basic
    private double cAllocdetOrder;

    @Column(name = "c_allocdet_createdby", table = "arts_t_allocdet", nullable = false, length = 36)
    @Basic
    private String cAllocdetCreatedby;

    @Column(name = "c_allocdet_createdon", table = "arts_t_allocdet", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAllocdetCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Character getcAllocdetStatus() {
        return cAllocdetStatus;
    }

    public void setcAllocdetStatus(Character cAllocdetStatus) {
        this.cAllocdetStatus = cAllocdetStatus;
    }

    public String getcAllocdetDomain() {
        return cAllocdetDomain;
    }

    public void setcAllocdetDomain(String cAllocdetDomain) {
        this.cAllocdetDomain = cAllocdetDomain;
    }

    public String getcAllocdetModifiedby() {
        return cAllocdetModifiedby;
    }

    public void setcAllocdetModifiedby(String cAllocdetModifiedby) {
        this.cAllocdetModifiedby = cAllocdetModifiedby;
    }

    public Date getcAllocdetModifiedon() {
        return cAllocdetModifiedon;
    }

    public void setcAllocdetModifiedon(Date cAllocdetModifiedon) {
        this.cAllocdetModifiedon = cAllocdetModifiedon;
    }

    public int getcAllocdetMaxsell() {
        return cAllocdetMaxsell;
    }

    public void setcAllocdetMaxsell(int cAllocdetMaxsell) {
        this.cAllocdetMaxsell = cAllocdetMaxsell;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public String getcStopId() {
        return cStopId;
    }

    public void setcStopId(String cStopId) {
        this.cStopId = cStopId;
    }

    public double getcAllocdetMaxcapacity() {
        return cAllocdetMaxcapacity;
    }

    public void setcAllocdetMaxcapacity(double cAllocdetMaxcapacity) {
        this.cAllocdetMaxcapacity = cAllocdetMaxcapacity;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public double getcAllocdetOrder() {
        return cAllocdetOrder;
    }

    public void setcAllocdetOrder(double cAllocdetOrder) {
        this.cAllocdetOrder = cAllocdetOrder;
    }

    public String getcAllocdetCreatedby() {
        return cAllocdetCreatedby;
    }

    public void setcAllocdetCreatedby(String cAllocdetCreatedby) {
        this.cAllocdetCreatedby = cAllocdetCreatedby;
    }

    public Date getcAllocdetCreatedon() {
        return cAllocdetCreatedon;
    }

    public void setcAllocdetCreatedon(Date cAllocdetCreatedon) {
        this.cAllocdetCreatedon = cAllocdetCreatedon;
    }

    

}
