/**
 * This file was generated by the JPA Modeler
 */
package users;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_shift")
public class Shift implements Serializable {

    @Column(name = "c_shift_id", table = "arts_t_shift", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_shift_name", table = "arts_t_shift", nullable = false, length = 50)
    @Basic
    private String cShiftName;

    @Column(name = "c_shift_openon", table = "arts_t_shift", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cShiftOpenon;

    @Column(name = "c_shift_closedon", table = "arts_t_shift")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cShiftClosedon;

    @Column(name = "c_shift_docnum", table = "arts_t_shift", length = 50)
    @Basic
    private String cShiftDocnum;

    @Column(name = "c_shift_status", table = "arts_t_shift", nullable = false)
    @Basic
    private Character cShiftStatus;

    @Column(name = "c_shift_domain", table = "arts_t_shift", nullable = false, length = 36)
    @Basic
    private String cShiftDomain;

    @Column(name = "c_shift_modifiedby", table = "arts_t_shift", nullable = false, length = 36)
    @Basic
    private String cShiftModifiedby;

    @Column(name = "c_shift_modifiedon", table = "arts_t_shift", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cShiftModifiedon;

    @Column(name = "c_user_id", table = "arts_t_shift", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_unit_id", table = "arts_t_shift", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_shift_createdby", table = "arts_t_shift", nullable = false, length = 36)
    @Basic
    private String cShiftCreatedby;

    @Column(name = "c_shift_createdon", table = "arts_t_shift", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cShiftCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcShiftName() {
        return cShiftName;
    }

    public void setcShiftName(String cShiftName) {
        this.cShiftName = cShiftName;
    }

    public Date getcShiftOpenon() {
        return cShiftOpenon;
    }

    public void setcShiftOpenon(Date cShiftOpenon) {
        this.cShiftOpenon = cShiftOpenon;
    }

    public Date getcShiftClosedon() {
        return cShiftClosedon;
    }

    public void setcShiftClosedon(Date cShiftClosedon) {
        this.cShiftClosedon = cShiftClosedon;
    }

    public String getcShiftDocnum() {
        return cShiftDocnum;
    }

    public void setcShiftDocnum(String cShiftDocnum) {
        this.cShiftDocnum = cShiftDocnum;
    }

    public Character getcShiftStatus() {
        return cShiftStatus;
    }

    public void setcShiftStatus(Character cShiftStatus) {
        this.cShiftStatus = cShiftStatus;
    }

    public String getcShiftDomain() {
        return cShiftDomain;
    }

    public void setcShiftDomain(String cShiftDomain) {
        this.cShiftDomain = cShiftDomain;
    }

    public String getcShiftModifiedby() {
        return cShiftModifiedby;
    }

    public void setcShiftModifiedby(String cShiftModifiedby) {
        this.cShiftModifiedby = cShiftModifiedby;
    }

    public Date getcShiftModifiedon() {
        return cShiftModifiedon;
    }

    public void setcShiftModifiedon(Date cShiftModifiedon) {
        this.cShiftModifiedon = cShiftModifiedon;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public String getcShiftCreatedby() {
        return cShiftCreatedby;
    }

    public void setcShiftCreatedby(String cShiftCreatedby) {
        this.cShiftCreatedby = cShiftCreatedby;
    }

    public Date getcShiftCreatedon() {
        return cShiftCreatedon;
    }

    public void setcShiftCreatedon(Date cShiftCreatedon) {
        this.cShiftCreatedon = cShiftCreatedon;
    }
    
    
}
