/**
 * This file was generated by the JPA Modeler
 */
package users;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_user")
public class User {

    @Column(name = "c_user_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_user_username", table = "arts_t_user", nullable = false, length = 50)
    @Basic
    private String cUserUsername;

    @Column(name = "c_user_password", table = "arts_t_user", nullable = false, length = 60)
    @Basic
    private String cUserPassword;

    @Column(name = "c_user_rqid", table = "arts_t_user", nullable = false, length = 100)
    @Basic
    private String cUserRqid;

    @Column(name = "c_user_firstname", table = "arts_t_user", nullable = false, length = 100)
    @Basic
    private String cUserFirstname;

    @Column(name = "c_user_lastname", table = "arts_t_user", length = 100)
    @Basic
    private String cUserLastname;

    @Column(name = "c_user_callname", table = "arts_t_user", length = 50)
    @Basic
    private String cUserCallname;

    @Column(name = "c_user_dateofbirth", table = "arts_t_user", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUserDateofbirth;

    @Column(name = "c_user_phone", table = "arts_t_user", length = 50)
    @Basic
    private String cUserPhone;

    @Column(name = "c_user_fax", table = "arts_t_user", length = 50)
    @Basic
    private String cUserFax;

    @Column(name = "c_user_mobile", table = "arts_t_user", nullable = false, length = 50)
    @Basic
    private String cUserMobile;

    @Column(name = "c_user_email", table = "arts_t_user", nullable = false, length = 100)
    @Basic
    private String cUserEmail;

    @Column(name = "c_user_altemail", table = "arts_t_user", length = 100)
    @Basic
    private String cUserAltemail;

    @Column(name = "c_user_address1", table = "arts_t_user", nullable = false)
    @Basic
    private String cUserAddress1;

    @Column(name = "c_user_address2", table = "arts_t_user")
    @Basic
    private String cUserAddress2;

    @Column(name = "c_user_postalcode", table = "arts_t_user", length = 10)
    @Basic
    private String cUserPostalcode;

    @Column(name = "c_user_loginattempt", table = "arts_t_user", nullable = false)
    @Basic
    private double cUserLoginattempt;

    @Column(name = "c_user_startdate", table = "arts_t_user", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUserStartdate;

    @Column(name = "c_user_enddate", table = "arts_t_user", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUserEnddate;

    @Column(name = "c_usergroup_id", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cUsergroupId;

    @Column(name = "c_user_status", table = "arts_t_user", nullable = false, length = 1)
    @Basic
    private String cUserStatus;

    @Column(name = "c_user_domain", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cUserDomain;

    @Column(name = "c_user_modifiedby", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cUserModifiedby;

    @Column(name = "c_user_modifiedon", table = "arts_t_user")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUserModifiedon;

    @Column(name = "c_stasiun_id", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_usertype_id", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cUsertypeId;

    @Column(name = "c_user_bypassip", table = "arts_t_user", nullable = false)
    @Basic
    private Character cUserBypassip;

    @Column(name = "c_user_createdby", table = "arts_t_user", nullable = false, length = 36)
    @Basic
    private String cUserCreatedby;

    @Column(name = "c_user_createdon", table = "arts_t_user", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUserCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcUserUsername() {
        return cUserUsername;
    }

    public void setcUserUsername(String cUserUsername) {
        this.cUserUsername = cUserUsername;
    }

    public String getcUserPassword() {
        return cUserPassword;
    }

    public void setcUserPassword(String cUserPassword) {
        this.cUserPassword = cUserPassword;
    }

    public String getcUserRqid() {
        return cUserRqid;
    }

    public void setcUserRqid(String cUserRqid) {
        this.cUserRqid = cUserRqid;
    }

    public String getcUserFirstname() {
        return cUserFirstname;
    }

    public void setcUserFirstname(String cUserFirstname) {
        this.cUserFirstname = cUserFirstname;
    }

    public String getcUserLastname() {
        return cUserLastname;
    }

    public void setcUserLastname(String cUserLastname) {
        this.cUserLastname = cUserLastname;
    }

    public String getcUserCallname() {
        return cUserCallname;
    }

    public void setcUserCallname(String cUserCallname) {
        this.cUserCallname = cUserCallname;
    }

    public Date getcUserDateofbirth() {
        return cUserDateofbirth;
    }

    public void setcUserDateofbirth(Date cUserDateofbirth) {
        this.cUserDateofbirth = cUserDateofbirth;
    }

    public String getcUserPhone() {
        return cUserPhone;
    }

    public void setcUserPhone(String cUserPhone) {
        this.cUserPhone = cUserPhone;
    }

    public String getcUserFax() {
        return cUserFax;
    }

    public void setcUserFax(String cUserFax) {
        this.cUserFax = cUserFax;
    }

    public String getcUserMobile() {
        return cUserMobile;
    }

    public void setcUserMobile(String cUserMobile) {
        this.cUserMobile = cUserMobile;
    }

    public String getcUserEmail() {
        return cUserEmail;
    }

    public void setcUserEmail(String cUserEmail) {
        this.cUserEmail = cUserEmail;
    }

    public String getcUserAltemail() {
        return cUserAltemail;
    }

    public void setcUserAltemail(String cUserAltemail) {
        this.cUserAltemail = cUserAltemail;
    }

    public String getcUserAddress1() {
        return cUserAddress1;
    }

    public void setcUserAddress1(String cUserAddress1) {
        this.cUserAddress1 = cUserAddress1;
    }

    public String getcUserAddress2() {
        return cUserAddress2;
    }

    public void setcUserAddress2(String cUserAddress2) {
        this.cUserAddress2 = cUserAddress2;
    }

    public String getcUserPostalcode() {
        return cUserPostalcode;
    }

    public void setcUserPostalcode(String cUserPostalcode) {
        this.cUserPostalcode = cUserPostalcode;
    }

    public double getcUserLoginattempt() {
        return cUserLoginattempt;
    }

    public void setcUserLoginattempt(double cUserLoginattempt) {
        this.cUserLoginattempt = cUserLoginattempt;
    }

    public Date getcUserStartdate() {
        return cUserStartdate;
    }

    public void setcUserStartdate(Date cUserStartdate) {
        this.cUserStartdate = cUserStartdate;
    }

    public Date getcUserEnddate() {
        return cUserEnddate;
    }

    public void setcUserEnddate(Date cUserEnddate) {
        this.cUserEnddate = cUserEnddate;
    }

    public String getcUsergroupId() {
        return cUsergroupId;
    }

    public void setcUsergroupId(String cUsergroupId) {
        this.cUsergroupId = cUsergroupId;
    }

    public String getcUserStatus() {
        return cUserStatus;
    }

    public void setcUserStatus(String cUserStatus) {
        this.cUserStatus = cUserStatus;
    }

    public String getcUserDomain() {
        return cUserDomain;
    }

    public void setcUserDomain(String cUserDomain) {
        this.cUserDomain = cUserDomain;
    }

    public String getcUserModifiedby() {
        return cUserModifiedby;
    }

    public void setcUserModifiedby(String cUserModifiedby) {
        this.cUserModifiedby = cUserModifiedby;
    }

    public Date getcUserModifiedon() {
        return cUserModifiedon;
    }

    public void setcUserModifiedon(Date cUserModifiedon) {
        this.cUserModifiedon = cUserModifiedon;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public String getcUsertypeId() {
        return cUsertypeId;
    }

    public void setcUsertypeId(String cUsertypeId) {
        this.cUsertypeId = cUsertypeId;
    }

    public Character getcUserBypassip() {
        return cUserBypassip;
    }

    public void setcUserBypassip(Character cUserBypassip) {
        this.cUserBypassip = cUserBypassip;
    }

    public String getcUserCreatedby() {
        return cUserCreatedby;
    }

    public void setcUserCreatedby(String cUserCreatedby) {
        this.cUserCreatedby = cUserCreatedby;
    }

    public Date getcUserCreatedon() {
        return cUserCreatedon;
    }

    public void setcUserCreatedon(Date cUserCreatedon) {
        this.cUserCreatedon = cUserCreatedon;
    }
    
    

}
