/**
 * This file was generated by the JPA Modeler
 */
package users;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_usertype")
public class Usertype {

    @Column(name = "c_usertype_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_usertype_name", table = "arts_t_usertype", nullable = false, length = 100)
    @Basic
    private String cUsertypeName;

    @Column(name = "c_usertype_status", table = "arts_t_usertype", nullable = false)
    @Basic
    private Character cUsertypeStatus;

    @Column(name = "c_usertype_domain", table = "arts_t_usertype", nullable = false, length = 36)
    @Basic
    private String cUsertypeDomain;

    @Column(name = "c_usertype_modifiedby", table = "arts_t_usertype", nullable = false, length = 36)
    @Basic
    private String cUsertypeModifiedby;

    @Column(name = "c_usertype_modifiedon", table = "arts_t_usertype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUsertypeModifiedon;

    @Column(name = "c_usertype_createdby", table = "arts_t_usertype", nullable = false, length = 36)
    @Basic
    private String cUsertypeCreatedby;

    @Column(name = "c_usertype_createdon", table = "arts_t_usertype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUsertypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcUsertypeName() {
        return cUsertypeName;
    }

    public void setcUsertypeName(String cUsertypeName) {
        this.cUsertypeName = cUsertypeName;
    }

    public Character getcUsertypeStatus() {
        return cUsertypeStatus;
    }

    public void setcUsertypeStatus(Character cUsertypeStatus) {
        this.cUsertypeStatus = cUsertypeStatus;
    }

    public String getcUsertypeDomain() {
        return cUsertypeDomain;
    }

    public void setcUsertypeDomain(String cUsertypeDomain) {
        this.cUsertypeDomain = cUsertypeDomain;
    }

    public String getcUsertypeModifiedby() {
        return cUsertypeModifiedby;
    }

    public void setcUsertypeModifiedby(String cUsertypeModifiedby) {
        this.cUsertypeModifiedby = cUsertypeModifiedby;
    }

    public Date getcUsertypeModifiedon() {
        return cUsertypeModifiedon;
    }

    public void setcUsertypeModifiedon(Date cUsertypeModifiedon) {
        this.cUsertypeModifiedon = cUsertypeModifiedon;
    }

    public String getcUsertypeCreatedby() {
        return cUsertypeCreatedby;
    }

    public void setcUsertypeCreatedby(String cUsertypeCreatedby) {
        this.cUsertypeCreatedby = cUsertypeCreatedby;
    }

    public Date getcUsertypeCreatedon() {
        return cUsertypeCreatedon;
    }

    public void setcUsertypeCreatedon(Date cUsertypeCreatedon) {
        this.cUsertypeCreatedon = cUsertypeCreatedon;
    }
    
    

}
