/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_domain")
public class Domain {

    @Column(name = "c_domain_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_domain_compcode", table = "arts_t_domain", nullable = false, length = 8)
    @Basic
    private String cDomainCompcode;

    @Column(name = "c_domain_name", table = "arts_t_domain", nullable = false, length = 50)
    @Basic
    private String cDomainName;

    @Column(name = "c_domain_status", table = "arts_t_domain", nullable = false)
    @Basic
    private Character cDomainStatus;

    @Column(name = "c_domain_modifiedby", table = "arts_t_domain", nullable = false, length = 36)
    @Basic
    private String cDomainModifiedby;

    @Column(name = "c_domain_modifiedon", table = "arts_t_domain", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDomainModifiedon;

    @Column(name = "c_domain_createdby", table = "arts_t_domain", length = 36)
    @Basic
    private String cDomainCreatedby;

    @Column(name = "c_domain_createdon", table = "arts_t_domain")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDomainCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcDomainCompcode() {
        return cDomainCompcode;
    }

    public void setcDomainCompcode(String cDomainCompcode) {
        this.cDomainCompcode = cDomainCompcode;
    }

    public String getcDomainName() {
        return cDomainName;
    }

    public void setcDomainName(String cDomainName) {
        this.cDomainName = cDomainName;
    }

    public Character getcDomainStatus() {
        return cDomainStatus;
    }

    public void setcDomainStatus(Character cDomainStatus) {
        this.cDomainStatus = cDomainStatus;
    }

    public String getcDomainModifiedby() {
        return cDomainModifiedby;
    }

    public void setcDomainModifiedby(String cDomainModifiedby) {
        this.cDomainModifiedby = cDomainModifiedby;
    }

    public Date getcDomainModifiedon() {
        return cDomainModifiedon;
    }

    public void setcDomainModifiedon(Date cDomainModifiedon) {
        this.cDomainModifiedon = cDomainModifiedon;
    }

    public String getcDomainCreatedby() {
        return cDomainCreatedby;
    }

    public void setcDomainCreatedby(String cDomainCreatedby) {
        this.cDomainCreatedby = cDomainCreatedby;
    }

    public Date getcDomainCreatedon() {
        return cDomainCreatedon;
    }

    public void setcDomainCreatedon(Date cDomainCreatedon) {
        this.cDomainCreatedon = cDomainCreatedon;
    }
    
    

}
