/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_holiday", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_holiday_date", "c_holiday_name"})})
public class Holiday implements Serializable {

    @Column(name = "c_holiday_id", table = "arts_t_holiday", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_holiday_date", table = "arts_t_holiday", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cHolidayDate;

    @Column(name = "c_holiday_name", table = "arts_t_holiday", nullable = false, length = 100)
    @Basic
    private String cHolidayName;

    @Column(name = "c_holiday_status", table = "arts_t_holiday", nullable = false)
    @Basic
    private Character cHolidayStatus;

    @Column(name = "c_holiday_domain", table = "arts_t_holiday", nullable = false, length = 36)
    @Basic
    private String cHolidayDomain;

    @Column(name = "c_holiday_modifiedby", table = "arts_t_holiday", nullable = false, length = 36)
    @Basic
    private String cHolidayModifiedby;

    @Column(name = "c_holiday_modifiedon", table = "arts_t_holiday", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cHolidayModifiedon;

    @Column(name = "c_holiday_createdby", table = "arts_t_holiday", nullable = false, length = 36)
    @Basic
    private String cHolidayCreatedby;

    @Column(name = "c_holiday_createdon", table = "arts_t_holiday", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cHolidayCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcHolidayDate() {
        return cHolidayDate;
    }

    public void setcHolidayDate(Date cHolidayDate) {
        this.cHolidayDate = cHolidayDate;
    }

    public String getcHolidayName() {
        return cHolidayName;
    }

    public void setcHolidayName(String cHolidayName) {
        this.cHolidayName = cHolidayName;
    }

    public Character getcHolidayStatus() {
        return cHolidayStatus;
    }

    public void setcHolidayStatus(Character cHolidayStatus) {
        this.cHolidayStatus = cHolidayStatus;
    }

    public String getcHolidayDomain() {
        return cHolidayDomain;
    }

    public void setcHolidayDomain(String cHolidayDomain) {
        this.cHolidayDomain = cHolidayDomain;
    }

    public String getcHolidayModifiedby() {
        return cHolidayModifiedby;
    }

    public void setcHolidayModifiedby(String cHolidayModifiedby) {
        this.cHolidayModifiedby = cHolidayModifiedby;
    }

    public Date getcHolidayModifiedon() {
        return cHolidayModifiedon;
    }

    public void setcHolidayModifiedon(Date cHolidayModifiedon) {
        this.cHolidayModifiedon = cHolidayModifiedon;
    }

    public String getcHolidayCreatedby() {
        return cHolidayCreatedby;
    }

    public void setcHolidayCreatedby(String cHolidayCreatedby) {
        this.cHolidayCreatedby = cHolidayCreatedby;
    }

    public Date getcHolidayCreatedon() {
        return cHolidayCreatedon;
    }

    public void setcHolidayCreatedon(Date cHolidayCreatedon) {
        this.cHolidayCreatedon = cHolidayCreatedon;
    }
    
    

}
