/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_ipunit")
public class Ipunit {

    @Column(name = "c_ipunit_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_unit_id", table = "arts_t_ipunit", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_ip_id", table = "arts_t_ipunit", nullable = false, length = 36)
    @Basic
    private String cIpId;

    @Column(name = "c_ipunit_status", table = "arts_t_ipunit", nullable = false)
    @Basic
    private Character cIpunitStatus;

    @Column(name = "c_ipunit_domain", table = "arts_t_ipunit", nullable = false, length = 36)
    @Basic
    private String cIpunitDomain;

    @Column(name = "c_ipunit_modifiedby", table = "arts_t_ipunit", nullable = false, length = 36)
    @Basic
    private String cIpunitModifiedby;

    @Column(name = "c_ipunit_modifiedon", table = "arts_t_ipunit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cIpunitModifiedon;

    @Column(name = "c_ipunit_createdby", table = "arts_t_ipunit", nullable = false, length = 36)
    @Basic
    private String cIpunitCreatedby;

    @Column(name = "c_ipunit_createdon", table = "arts_t_ipunit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cIpunitCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public String getcIpId() {
        return cIpId;
    }

    public void setcIpId(String cIpId) {
        this.cIpId = cIpId;
    }

    public Character getcIpunitStatus() {
        return cIpunitStatus;
    }

    public void setcIpunitStatus(Character cIpunitStatus) {
        this.cIpunitStatus = cIpunitStatus;
    }

    public String getcIpunitDomain() {
        return cIpunitDomain;
    }

    public void setcIpunitDomain(String cIpunitDomain) {
        this.cIpunitDomain = cIpunitDomain;
    }

    public String getcIpunitModifiedby() {
        return cIpunitModifiedby;
    }

    public void setcIpunitModifiedby(String cIpunitModifiedby) {
        this.cIpunitModifiedby = cIpunitModifiedby;
    }

    public Date getcIpunitModifiedon() {
        return cIpunitModifiedon;
    }

    public void setcIpunitModifiedon(Date cIpunitModifiedon) {
        this.cIpunitModifiedon = cIpunitModifiedon;
    }

    public String getcIpunitCreatedby() {
        return cIpunitCreatedby;
    }

    public void setcIpunitCreatedby(String cIpunitCreatedby) {
        this.cIpunitCreatedby = cIpunitCreatedby;
    }

    public Date getcIpunitCreatedon() {
        return cIpunitCreatedon;
    }

    public void setcIpunitCreatedon(Date cIpunitCreatedon) {
        this.cIpunitCreatedon = cIpunitCreatedon;
    }
    
    

}
