/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_stdistance", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_stasiunid_from", "c_stasiunid_to"})})
public class Stdistance implements Serializable {

    @Column(name = "c_stdistance_id", table = "arts_t_stdistance", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_stasiunid_from", table = "arts_t_stdistance", nullable = false, length = 36)
    @Basic
    private String cStasiunidFrom;

    @Column(name = "c_stasiunid_to", table = "arts_t_stdistance", nullable = false, length = 36)
    @Basic
    private String cStasiunidTo;

    @Column(name = "c_stdistance_value", table = "arts_t_stdistance", nullable = false, scale = 3, precision = 11)
    @Basic
    private BigDecimal cStdistanceValue;

    @Column(name = "c_stdistance_status", table = "arts_t_stdistance", nullable = false)
    @Basic
    private Character cStdistanceStatus;

    @Column(name = "c_stdistance_domain", table = "arts_t_stdistance", nullable = false, length = 36)
    @Basic
    private String cStdistanceDomain;

    @Column(name = "c_stdistance_modifiedby", table = "arts_t_stdistance", nullable = false, length = 36)
    @Basic
    private String cStdistanceModifiedby;

    @Column(name = "c_stdistance_modifiedon", table = "arts_t_stdistance", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cStdistanceModifiedon;

    @Column(name = "c_stdistance_createdby", table = "arts_t_stdistance", nullable = false, length = 36)
    @Basic
    private String cStdistanceCreatedby;

    @Column(name = "c_stdistance_createdon", table = "arts_t_stdistance", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cStdistanceCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcStasiunidFrom() {
        return cStasiunidFrom;
    }

    public void setcStasiunidFrom(String cStasiunidFrom) {
        this.cStasiunidFrom = cStasiunidFrom;
    }

    public String getcStasiunidTo() {
        return cStasiunidTo;
    }

    public void setcStasiunidTo(String cStasiunidTo) {
        this.cStasiunidTo = cStasiunidTo;
    }

    public BigDecimal getcStdistanceValue() {
        return cStdistanceValue;
    }

    public void setcStdistanceValue(BigDecimal cStdistanceValue) {
        this.cStdistanceValue = cStdistanceValue;
    }

    public Character getcStdistanceStatus() {
        return cStdistanceStatus;
    }

    public void setcStdistanceStatus(Character cStdistanceStatus) {
        this.cStdistanceStatus = cStdistanceStatus;
    }

    public String getcStdistanceDomain() {
        return cStdistanceDomain;
    }

    public void setcStdistanceDomain(String cStdistanceDomain) {
        this.cStdistanceDomain = cStdistanceDomain;
    }

    public String getcStdistanceModifiedby() {
        return cStdistanceModifiedby;
    }

    public void setcStdistanceModifiedby(String cStdistanceModifiedby) {
        this.cStdistanceModifiedby = cStdistanceModifiedby;
    }

    public Date getcStdistanceModifiedon() {
        return cStdistanceModifiedon;
    }

    public void setcStdistanceModifiedon(Date cStdistanceModifiedon) {
        this.cStdistanceModifiedon = cStdistanceModifiedon;
    }

    public String getcStdistanceCreatedby() {
        return cStdistanceCreatedby;
    }

    public void setcStdistanceCreatedby(String cStdistanceCreatedby) {
        this.cStdistanceCreatedby = cStdistanceCreatedby;
    }

    public Date getcStdistanceCreatedon() {
        return cStdistanceCreatedon;
    }

    public void setcStdistanceCreatedon(Date cStdistanceCreatedon) {
        this.cStdistanceCreatedon = cStdistanceCreatedon;
    }
    
    

}
