/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_unit", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_unit_code"})})
public class Unit implements Serializable {

    @Column(name = "c_unit_id", table = "arts_t_unit", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_unit_name", table = "arts_t_unit", nullable = false, length = 50)
    @Basic
    private String cUnitName;

    @Column(name = "c_unit_status", table = "arts_t_unit", nullable = false)
    @Basic
    private Character cUnitStatus;

    @Column(name = "c_unit_domain", table = "arts_t_unit", nullable = false, length = 36)
    @Basic
    private String cUnitDomain;

    @Column(name = "c_unit_modifiedby", table = "arts_t_unit", nullable = false, length = 40)
    @Basic
    private String cUnitModifiedby;

    @Column(name = "c_unit_modifiedon", table = "arts_t_unit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitModifiedon;

    @Column(name = "c_stasiun_id", table = "arts_t_unit", nullable = false, length = 36)
    @Basic
    private String cStasiunId;

    @Column(name = "c_unit_code", table = "arts_t_unit", nullable = false, length = 36)
    @Basic
    private String cUnitCode;

    @Column(name = "c_channel_id", table = "arts_t_unit", nullable = false, length = 36)
    @Basic
    private String cChannelId;

    @Column(name = "c_unit_balancelimit", table = "arts_t_unit", scale = 2, precision = 11)
    @Basic
    private BigDecimal cUnitBalancelimit;

    @Column(name = "c_paytype_id", table = "arts_t_unit", length = 36)
    @Basic
    private String cPaytypeId;

    @Column(name = "c_unit_sellnoseat", table = "arts_t_unit", nullable = false)
    @Basic
    private Character cUnitSellnoseat;

    @Column(name = "c_unit_localpay", table = "arts_t_unit", nullable = false)
    @Basic
    private Character cUnitLocalpay;

    @Column(name = "c_unit_reversaltime", table = "arts_t_unit", nullable = false)
    @Basic
    private short cUnitReversaltime;

    @Column(name = "c_unit_createdby", table = "arts_t_unit", nullable = false, length = 36)
    @Basic
    private String cUnitCreatedby;

    @Column(name = "c_unit_createdon", table = "arts_t_unit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcUnitName() {
        return cUnitName;
    }

    public void setcUnitName(String cUnitName) {
        this.cUnitName = cUnitName;
    }

    public Character getcUnitStatus() {
        return cUnitStatus;
    }

    public void setcUnitStatus(Character cUnitStatus) {
        this.cUnitStatus = cUnitStatus;
    }

    public String getcUnitDomain() {
        return cUnitDomain;
    }

    public void setcUnitDomain(String cUnitDomain) {
        this.cUnitDomain = cUnitDomain;
    }

    public String getcUnitModifiedby() {
        return cUnitModifiedby;
    }

    public void setcUnitModifiedby(String cUnitModifiedby) {
        this.cUnitModifiedby = cUnitModifiedby;
    }

    public Date getcUnitModifiedon() {
        return cUnitModifiedon;
    }

    public void setcUnitModifiedon(Date cUnitModifiedon) {
        this.cUnitModifiedon = cUnitModifiedon;
    }

    public String getcStasiunId() {
        return cStasiunId;
    }

    public void setcStasiunId(String cStasiunId) {
        this.cStasiunId = cStasiunId;
    }

    public String getcUnitCode() {
        return cUnitCode;
    }

    public void setcUnitCode(String cUnitCode) {
        this.cUnitCode = cUnitCode;
    }

    public String getcChannelId() {
        return cChannelId;
    }

    public void setcChannelId(String cChannelId) {
        this.cChannelId = cChannelId;
    }

    public BigDecimal getcUnitBalancelimit() {
        return cUnitBalancelimit;
    }

    public void setcUnitBalancelimit(BigDecimal cUnitBalancelimit) {
        this.cUnitBalancelimit = cUnitBalancelimit;
    }

    public String getcPaytypeId() {
        return cPaytypeId;
    }

    public void setcPaytypeId(String cPaytypeId) {
        this.cPaytypeId = cPaytypeId;
    }

    public Character getcUnitSellnoseat() {
        return cUnitSellnoseat;
    }

    public void setcUnitSellnoseat(Character cUnitSellnoseat) {
        this.cUnitSellnoseat = cUnitSellnoseat;
    }

    public Character getcUnitLocalpay() {
        return cUnitLocalpay;
    }

    public void setcUnitLocalpay(Character cUnitLocalpay) {
        this.cUnitLocalpay = cUnitLocalpay;
    }

    public short getcUnitReversaltime() {
        return cUnitReversaltime;
    }

    public void setcUnitReversaltime(short cUnitReversaltime) {
        this.cUnitReversaltime = cUnitReversaltime;
    }

    public String getcUnitCreatedby() {
        return cUnitCreatedby;
    }

    public void setcUnitCreatedby(String cUnitCreatedby) {
        this.cUnitCreatedby = cUnitCreatedby;
    }

    public Date getcUnitCreatedon() {
        return cUnitCreatedon;
    }

    public void setcUnitCreatedon(Date cUnitCreatedon) {
        this.cUnitCreatedon = cUnitCreatedon;
    }
    
    
}
