/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.org;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_unitfee")
public class Unitfee {

    @Column(name = "c_unitfee_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_unitfee_startdate", table = "arts_t_unitfee", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitfeeStartdate;

    @Column(name = "c_unitfee_enddate", table = "arts_t_unitfee", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitfeeEnddate;

    @Column(name = "c_unitfee_status", table = "arts_t_unitfee", nullable = false)
    @Basic
    private Character cUnitfeeStatus;

    @Column(name = "c_unitfee_domain", table = "arts_t_unitfee", nullable = false, length = 36)
    @Basic
    private String cUnitfeeDomain;

    @Column(name = "c_unitfee_modifiedby", table = "arts_t_unitfee", nullable = false, length = 36)
    @Basic
    private String cUnitfeeModifiedby;

    @Column(name = "c_unitfee_modifiedon", table = "arts_t_unitfee", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitfeeModifiedon;

    @Column(name = "c_unit_id", table = "arts_t_unitfee", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_unitfee_amountkai", table = "arts_t_unitfee", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cUnitfeeAmountkai;

    @Column(name = "c_unitfee_amountagent", table = "arts_t_unitfee", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cUnitfeeAmountagent;

    @Column(name = "c_unitfee_createdby", table = "arts_t_unitfee", nullable = false, length = 36)
    @Basic
    private String cUnitfeeCreatedby;

    @Column(name = "c_unitfee_createdon", table = "arts_t_unitfee", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cUnitfeeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcUnitfeeStartdate() {
        return cUnitfeeStartdate;
    }

    public void setcUnitfeeStartdate(Date cUnitfeeStartdate) {
        this.cUnitfeeStartdate = cUnitfeeStartdate;
    }

    public Date getcUnitfeeEnddate() {
        return cUnitfeeEnddate;
    }

    public void setcUnitfeeEnddate(Date cUnitfeeEnddate) {
        this.cUnitfeeEnddate = cUnitfeeEnddate;
    }

    public Character getcUnitfeeStatus() {
        return cUnitfeeStatus;
    }

    public void setcUnitfeeStatus(Character cUnitfeeStatus) {
        this.cUnitfeeStatus = cUnitfeeStatus;
    }

    public String getcUnitfeeDomain() {
        return cUnitfeeDomain;
    }

    public void setcUnitfeeDomain(String cUnitfeeDomain) {
        this.cUnitfeeDomain = cUnitfeeDomain;
    }

    public String getcUnitfeeModifiedby() {
        return cUnitfeeModifiedby;
    }

    public void setcUnitfeeModifiedby(String cUnitfeeModifiedby) {
        this.cUnitfeeModifiedby = cUnitfeeModifiedby;
    }

    public Date getcUnitfeeModifiedon() {
        return cUnitfeeModifiedon;
    }

    public void setcUnitfeeModifiedon(Date cUnitfeeModifiedon) {
        this.cUnitfeeModifiedon = cUnitfeeModifiedon;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public BigDecimal getcUnitfeeAmountkai() {
        return cUnitfeeAmountkai;
    }

    public void setcUnitfeeAmountkai(BigDecimal cUnitfeeAmountkai) {
        this.cUnitfeeAmountkai = cUnitfeeAmountkai;
    }

    public BigDecimal getcUnitfeeAmountagent() {
        return cUnitfeeAmountagent;
    }

    public void setcUnitfeeAmountagent(BigDecimal cUnitfeeAmountagent) {
        this.cUnitfeeAmountagent = cUnitfeeAmountagent;
    }

    public String getcUnitfeeCreatedby() {
        return cUnitfeeCreatedby;
    }

    public void setcUnitfeeCreatedby(String cUnitfeeCreatedby) {
        this.cUnitfeeCreatedby = cUnitfeeCreatedby;
    }

    public Date getcUnitfeeCreatedon() {
        return cUnitfeeCreatedon;
    }

    public void setcUnitfeeCreatedon(Date cUnitfeeCreatedon) {
        this.cUnitfeeCreatedon = cUnitfeeCreatedon;
    }
    
    

}
