/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_discounttype")
public class Discounttype {

    @Column(name = "c_discounttype_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_discounttype_name", table = "arts_t_discounttype", nullable = false, length = 200)
    @Basic
    private String cDiscounttypeName;

    @Column(name = "c_discounttype_status", table = "arts_t_discounttype", nullable = false)
    @Basic
    private Character cDiscounttypeStatus;

    @Column(name = "c_discounttype_domain", table = "arts_t_discounttype", nullable = false, length = 36)
    @Basic
    private String cDiscounttypeDomain;

    @Column(name = "c_discounttype_modifiedby", table = "arts_t_discounttype", nullable = false, length = 36)
    @Basic
    private String cDiscounttypeModifiedby;

    @Column(name = "c_discounttype_modifiedon", table = "arts_t_discounttype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscounttypeModifiedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcDiscounttypeName() {
        return cDiscounttypeName;
    }

    public void setcDiscounttypeName(String cDiscounttypeName) {
        this.cDiscounttypeName = cDiscounttypeName;
    }

    public Character getcDiscounttypeStatus() {
        return cDiscounttypeStatus;
    }

    public void setcDiscounttypeStatus(Character cDiscounttypeStatus) {
        this.cDiscounttypeStatus = cDiscounttypeStatus;
    }

    public String getcDiscounttypeDomain() {
        return cDiscounttypeDomain;
    }

    public void setcDiscounttypeDomain(String cDiscounttypeDomain) {
        this.cDiscounttypeDomain = cDiscounttypeDomain;
    }

    public String getcDiscounttypeModifiedby() {
        return cDiscounttypeModifiedby;
    }

    public void setcDiscounttypeModifiedby(String cDiscounttypeModifiedby) {
        this.cDiscounttypeModifiedby = cDiscounttypeModifiedby;
    }

    public Date getcDiscounttypeModifiedon() {
        return cDiscounttypeModifiedon;
    }

    public void setcDiscounttypeModifiedon(Date cDiscounttypeModifiedon) {
        this.cDiscounttypeModifiedon = cDiscounttypeModifiedon;
    }
    
    

}
