/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_discount")
public class Discount {

    @Column(name = "c_discount_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_discount_value", table = "arts_t_discount", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cDiscountValue;

    @Column(name = "c_discount_startdate", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountStartdate;

    @Column(name = "c_discount_enddate", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountEnddate;

    @Column(name = "c_discount_status", table = "arts_t_discount", nullable = false)
    @Basic
    private Character cDiscountStatus;

    @Column(name = "c_discount_domain", table = "arts_t_discount", nullable = false, length = 36)
    @Basic
    private String cDiscountDomain;

    @Column(name = "c_discount_modifiedby", table = "arts_t_discount", nullable = false, length = 36)
    @Basic
    private String cDiscountModifiedby;

    @Column(name = "c_discount_modifiedon", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountModifiedon;

    @Column(name = "c_discount_psgnum", table = "arts_t_discount")
    @Basic
    private Short cDiscountPsgnum;

    @Column(name = "c_discount_psgcount", table = "arts_t_discount")
    @Basic
    private Short cDiscountPsgcount;

    @Column(name = "c_discount_sellstartdate", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountSellstartdate;

    @Column(name = "c_discount_sellenddate", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountSellenddate;

    @Column(name = "c_discount_valuetype", table = "arts_t_discount", nullable = false)
    @Basic
    private Character cDiscountValuetype;

    @Column(name = "c_discount_validdays", table = "arts_t_discount", nullable = false, length = 7)
    @Basic
    private String cDiscountValiddays;

    @Column(name = "c_discount_holidaystat", table = "arts_t_discount", nullable = false)
    @Basic
    private Character cDiscountHolidaystat;

    @Column(name = "c_discounttype_id", table = "arts_t_discount", nullable = false, length = 36)
    @Basic
    private String cDiscounttypeId;

    @Column(name = "c_discount_createdby", table = "arts_t_discount", nullable = false, length = 36)
    @Basic
    private String cDiscountCreatedby;

    @Column(name = "c_discount_createdon", table = "arts_t_discount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public BigDecimal getcDiscountValue() {
        return cDiscountValue;
    }

    public void setcDiscountValue(BigDecimal cDiscountValue) {
        this.cDiscountValue = cDiscountValue;
    }

    public Date getcDiscountStartdate() {
        return cDiscountStartdate;
    }

    public void setcDiscountStartdate(Date cDiscountStartdate) {
        this.cDiscountStartdate = cDiscountStartdate;
    }

    public Date getcDiscountEnddate() {
        return cDiscountEnddate;
    }

    public void setcDiscountEnddate(Date cDiscountEnddate) {
        this.cDiscountEnddate = cDiscountEnddate;
    }

    public Character getcDiscountStatus() {
        return cDiscountStatus;
    }

    public void setcDiscountStatus(Character cDiscountStatus) {
        this.cDiscountStatus = cDiscountStatus;
    }

    public String getcDiscountDomain() {
        return cDiscountDomain;
    }

    public void setcDiscountDomain(String cDiscountDomain) {
        this.cDiscountDomain = cDiscountDomain;
    }

    public String getcDiscountModifiedby() {
        return cDiscountModifiedby;
    }

    public void setcDiscountModifiedby(String cDiscountModifiedby) {
        this.cDiscountModifiedby = cDiscountModifiedby;
    }

    public Date getcDiscountModifiedon() {
        return cDiscountModifiedon;
    }

    public void setcDiscountModifiedon(Date cDiscountModifiedon) {
        this.cDiscountModifiedon = cDiscountModifiedon;
    }

    public Short getcDiscountPsgnum() {
        return cDiscountPsgnum;
    }

    public void setcDiscountPsgnum(Short cDiscountPsgnum) {
        this.cDiscountPsgnum = cDiscountPsgnum;
    }

    public Short getcDiscountPsgcount() {
        return cDiscountPsgcount;
    }

    public void setcDiscountPsgcount(Short cDiscountPsgcount) {
        this.cDiscountPsgcount = cDiscountPsgcount;
    }

    public Date getcDiscountSellstartdate() {
        return cDiscountSellstartdate;
    }

    public void setcDiscountSellstartdate(Date cDiscountSellstartdate) {
        this.cDiscountSellstartdate = cDiscountSellstartdate;
    }

    public Date getcDiscountSellenddate() {
        return cDiscountSellenddate;
    }

    public void setcDiscountSellenddate(Date cDiscountSellenddate) {
        this.cDiscountSellenddate = cDiscountSellenddate;
    }

    public Character getcDiscountValuetype() {
        return cDiscountValuetype;
    }

    public void setcDiscountValuetype(Character cDiscountValuetype) {
        this.cDiscountValuetype = cDiscountValuetype;
    }

    public String getcDiscountValiddays() {
        return cDiscountValiddays;
    }

    public void setcDiscountValiddays(String cDiscountValiddays) {
        this.cDiscountValiddays = cDiscountValiddays;
    }

    public Character getcDiscountHolidaystat() {
        return cDiscountHolidaystat;
    }

    public void setcDiscountHolidaystat(Character cDiscountHolidaystat) {
        this.cDiscountHolidaystat = cDiscountHolidaystat;
    }

    public String getcDiscounttypeId() {
        return cDiscounttypeId;
    }

    public void setcDiscounttypeId(String cDiscounttypeId) {
        this.cDiscounttypeId = cDiscounttypeId;
    }

    public String getcDiscountCreatedby() {
        return cDiscountCreatedby;
    }

    public void setcDiscountCreatedby(String cDiscountCreatedby) {
        this.cDiscountCreatedby = cDiscountCreatedby;
    }

    public Date getcDiscountCreatedon() {
        return cDiscountCreatedon;
    }

    public void setcDiscountCreatedon(Date cDiscountCreatedon) {
        this.cDiscountCreatedon = cDiscountCreatedon;
    }
    
    

}
