/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_discountsch")
public class Discountsch implements Serializable {

    @Column(name = "c_discountsch_id", table = "arts_t_discountsch", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_discount_id", table = "arts_t_discountsch", nullable = false, length = 36)
    @Basic
    private String cDiscountId;

    @Column(name = "c_discountsch_status", table = "arts_t_discountsch", nullable = false)
    @Basic
    private Character cDiscountschStatus;

    @Column(name = "c_discountsch_domain", table = "arts_t_discountsch", nullable = false, length = 36)
    @Basic
    private String cDiscountschDomain;

    @Column(name = "c_discountsch_modifiedby", table = "arts_t_discountsch", nullable = false, length = 36)
    @Basic
    private String cDiscountschModifiedby;

    @Column(name = "c_discountsch_modifiedon", table = "arts_t_discountsch", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountschModifiedon;

    @Column(name = "c_discountsch_noka", table = "arts_t_discountsch", nullable = false, length = 50)
    @Basic
    private String cDiscountschNoka;

    @Column(name = "c_discountsch_createdby", table = "arts_t_discountsch", nullable = false, length = 36)
    @Basic
    private String cDiscountschCreatedby;

    @Column(name = "c_discountsch_createdon", table = "arts_t_discountsch", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountschCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcDiscountId() {
        return cDiscountId;
    }

    public void setcDiscountId(String cDiscountId) {
        this.cDiscountId = cDiscountId;
    }

    public Character getcDiscountschStatus() {
        return cDiscountschStatus;
    }

    public void setcDiscountschStatus(Character cDiscountschStatus) {
        this.cDiscountschStatus = cDiscountschStatus;
    }

    public String getcDiscountschDomain() {
        return cDiscountschDomain;
    }

    public void setcDiscountschDomain(String cDiscountschDomain) {
        this.cDiscountschDomain = cDiscountschDomain;
    }

    public String getcDiscountschModifiedby() {
        return cDiscountschModifiedby;
    }

    public void setcDiscountschModifiedby(String cDiscountschModifiedby) {
        this.cDiscountschModifiedby = cDiscountschModifiedby;
    }

    public Date getcDiscountschModifiedon() {
        return cDiscountschModifiedon;
    }

    public void setcDiscountschModifiedon(Date cDiscountschModifiedon) {
        this.cDiscountschModifiedon = cDiscountschModifiedon;
    }

    public String getcDiscountschNoka() {
        return cDiscountschNoka;
    }

    public void setcDiscountschNoka(String cDiscountschNoka) {
        this.cDiscountschNoka = cDiscountschNoka;
    }

    public String getcDiscountschCreatedby() {
        return cDiscountschCreatedby;
    }

    public void setcDiscountschCreatedby(String cDiscountschCreatedby) {
        this.cDiscountschCreatedby = cDiscountschCreatedby;
    }

    public Date getcDiscountschCreatedon() {
        return cDiscountschCreatedon;
    }

    public void setcDiscountschCreatedon(Date cDiscountschCreatedon) {
        this.cDiscountschCreatedon = cDiscountschCreatedon;
    }
    
    

}
