/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_discountunit")
public class Discountunit  {

    @Column(name = "c_discountunit_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_discount_id", table = "arts_t_discountunit", nullable = false, length = 36)
    @Basic
    private String cDiscountId;

    @Column(name = "c_unit_id", table = "arts_t_discountunit", nullable = false, length = 36)
    @Basic
    private String cUnitId;

    @Column(name = "c_discountunit_status", table = "arts_t_discountunit", nullable = false)
    @Basic
    private Character cDiscountunitStatus;

    @Column(name = "c_discountunit_domain", table = "arts_t_discountunit", nullable = false, length = 36)
    @Basic
    private String cDiscountunitDomain;

    @Column(name = "c_discountunit_modifiedby", table = "arts_t_discountunit", nullable = false, length = 36)
    @Basic
    private String cDiscountunitModifiedby;

    @Column(name = "c_discountunit_modifiedon", table = "arts_t_discountunit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountunitModifiedon;

    @Column(name = "c_discountunit_createdby", table = "arts_t_discountunit", nullable = false, length = 36)
    @Basic
    private String cDiscountunitCreatedby;

    @Column(name = "c_discountunit_createdon", table = "arts_t_discountunit", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cDiscountunitCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcDiscountId() {
        return cDiscountId;
    }

    public void setcDiscountId(String cDiscountId) {
        this.cDiscountId = cDiscountId;
    }

    public String getcUnitId() {
        return cUnitId;
    }

    public void setcUnitId(String cUnitId) {
        this.cUnitId = cUnitId;
    }

    public Character getcDiscountunitStatus() {
        return cDiscountunitStatus;
    }

    public void setcDiscountunitStatus(Character cDiscountunitStatus) {
        this.cDiscountunitStatus = cDiscountunitStatus;
    }

    public String getcDiscountunitDomain() {
        return cDiscountunitDomain;
    }

    public void setcDiscountunitDomain(String cDiscountunitDomain) {
        this.cDiscountunitDomain = cDiscountunitDomain;
    }

    public String getcDiscountunitModifiedby() {
        return cDiscountunitModifiedby;
    }

    public void setcDiscountunitModifiedby(String cDiscountunitModifiedby) {
        this.cDiscountunitModifiedby = cDiscountunitModifiedby;
    }

    public Date getcDiscountunitModifiedon() {
        return cDiscountunitModifiedon;
    }

    public void setcDiscountunitModifiedon(Date cDiscountunitModifiedon) {
        this.cDiscountunitModifiedon = cDiscountunitModifiedon;
    }

    public String getcDiscountunitCreatedby() {
        return cDiscountunitCreatedby;
    }

    public void setcDiscountunitCreatedby(String cDiscountunitCreatedby) {
        this.cDiscountunitCreatedby = cDiscountunitCreatedby;
    }

    public Date getcDiscountunitCreatedon() {
        return cDiscountunitCreatedon;
    }

    public void setcDiscountunitCreatedon(Date cDiscountunitCreatedon) {
        this.cDiscountunitCreatedon = cDiscountunitCreatedon;
    }
    
    
}
