/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_paytype", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_paytype_domain", "c_paytype_code"})})
public class Paytype implements Serializable {

    @Column(name = "c_paytype_id", table = "arts_t_paytype", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_paytype_name", table = "arts_t_paytype", nullable = false, length = 100)
    @Basic
    private String cPaytypeName;

    @Column(name = "c_paytype_fee", table = "arts_t_paytype", nullable = false, scale = 2, precision = 11)
    @Basic
    private BigDecimal cPaytypeFee;

    @Column(name = "c_paytype_status", table = "arts_t_paytype", nullable = false)
    @Basic
    private Character cPaytypeStatus;

    @Column(name = "c_paytype_domain", table = "arts_t_paytype", nullable = false, length = 36)
    @Basic
    private String cPaytypeDomain;

    @Column(name = "c_paytype_modifiedby", table = "arts_t_paytype", nullable = false, length = 36)
    @Basic
    private String cPaytypeModifiedby;

    @Column(name = "c_paytype_modifiedon", table = "arts_t_paytype", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cPaytypeModifiedon;

    @Column(name = "c_paytype_timeout", table = "arts_t_paytype", nullable = false)
    @Basic
    private short cPaytypeTimeout;

    @Column(name = "c_paytype_timeoutstat", table = "arts_t_paytype", nullable = false)
    @Basic
    private Character cPaytypeTimeoutstat;

    @Column(name = "c_paytype_amounttype", table = "arts_t_paytype", nullable = false)
    @Basic
    private Character cPaytypeAmounttype;

    @Column(name = "c_paytype_code", table = "arts_t_paytype", nullable = false, length = 50)
    @Basic
    private String cPaytypeCode;

    @Column(name = "c_paytype_createdby", table = "arts_t_paytype", length = 36)
    @Basic
    private String cPaytypeCreatedby;

    @Column(name = "c_paytype_createdon", table = "arts_t_paytype")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cPaytypeCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcPaytypeName() {
        return cPaytypeName;
    }

    public void setcPaytypeName(String cPaytypeName) {
        this.cPaytypeName = cPaytypeName;
    }

    public BigDecimal getcPaytypeFee() {
        return cPaytypeFee;
    }

    public void setcPaytypeFee(BigDecimal cPaytypeFee) {
        this.cPaytypeFee = cPaytypeFee;
    }

    public Character getcPaytypeStatus() {
        return cPaytypeStatus;
    }

    public void setcPaytypeStatus(Character cPaytypeStatus) {
        this.cPaytypeStatus = cPaytypeStatus;
    }

    public String getcPaytypeDomain() {
        return cPaytypeDomain;
    }

    public void setcPaytypeDomain(String cPaytypeDomain) {
        this.cPaytypeDomain = cPaytypeDomain;
    }

    public String getcPaytypeModifiedby() {
        return cPaytypeModifiedby;
    }

    public void setcPaytypeModifiedby(String cPaytypeModifiedby) {
        this.cPaytypeModifiedby = cPaytypeModifiedby;
    }

    public Date getcPaytypeModifiedon() {
        return cPaytypeModifiedon;
    }

    public void setcPaytypeModifiedon(Date cPaytypeModifiedon) {
        this.cPaytypeModifiedon = cPaytypeModifiedon;
    }

    public short getcPaytypeTimeout() {
        return cPaytypeTimeout;
    }

    public void setcPaytypeTimeout(short cPaytypeTimeout) {
        this.cPaytypeTimeout = cPaytypeTimeout;
    }

    public Character getcPaytypeTimeoutstat() {
        return cPaytypeTimeoutstat;
    }

    public void setcPaytypeTimeoutstat(Character cPaytypeTimeoutstat) {
        this.cPaytypeTimeoutstat = cPaytypeTimeoutstat;
    }

    public Character getcPaytypeAmounttype() {
        return cPaytypeAmounttype;
    }

    public void setcPaytypeAmounttype(Character cPaytypeAmounttype) {
        this.cPaytypeAmounttype = cPaytypeAmounttype;
    }

    public String getcPaytypeCode() {
        return cPaytypeCode;
    }

    public void setcPaytypeCode(String cPaytypeCode) {
        this.cPaytypeCode = cPaytypeCode;
    }

    public String getcPaytypeCreatedby() {
        return cPaytypeCreatedby;
    }

    public void setcPaytypeCreatedby(String cPaytypeCreatedby) {
        this.cPaytypeCreatedby = cPaytypeCreatedby;
    }

    public Date getcPaytypeCreatedon() {
        return cPaytypeCreatedon;
    }

    public void setcPaytypeCreatedon(Date cPaytypeCreatedon) {
        this.cPaytypeCreatedon = cPaytypeCreatedon;
    }
    
    

}
