/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.payments;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_voucheramount")
public class Voucheramount {

    @Column(name = "c_voucheramount_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_voucheramount_value", table = "arts_t_voucheramount", nullable = false)
    @Basic
    private double cVoucheramountValue;

    @Column(name = "c_voucheramount_valuetype", table = "arts_t_voucheramount", nullable = false)
    @Basic
    private Character cVoucheramountValuetype;

    @Column(name = "c_vouchertype_id", table = "arts_t_voucheramount", nullable = false, length = 36)
    @Basic
    private String cVouchertypeId;

    @Column(name = "c_voucheramount_startdate", table = "arts_t_voucheramount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cVoucheramountStartdate;

    @Column(name = "c_voucheramount_enddate", table = "arts_t_voucheramount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cVoucheramountEnddate;

    @Column(name = "c_voucheramount_status", table = "arts_t_voucheramount", nullable = false)
    @Basic
    private Character cVoucheramountStatus;

    @Column(name = "c_voucheramount_domain", table = "arts_t_voucheramount", nullable = false, length = 36)
    @Basic
    private String cVoucheramountDomain;

    @Column(name = "c_voucheramount_modifiedby", table = "arts_t_voucheramount", nullable = false, length = 36)
    @Basic
    private String cVoucheramountModifiedby;

    @Column(name = "c_voucheramount_modifiedon", table = "arts_t_voucheramount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cVoucheramountModifiedon;

    @Column(name = "c_voucheramount_createdby", table = "arts_t_voucheramount", nullable = false, length = 36)
    @Basic
    private String cVoucheramountCreatedby;

    @Column(name = "c_voucheramount_createdon", table = "arts_t_voucheramount", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cVoucheramountCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public double getcVoucheramountValue() {
        return cVoucheramountValue;
    }

    public void setcVoucheramountValue(double cVoucheramountValue) {
        this.cVoucheramountValue = cVoucheramountValue;
    }

    public Character getcVoucheramountValuetype() {
        return cVoucheramountValuetype;
    }

    public void setcVoucheramountValuetype(Character cVoucheramountValuetype) {
        this.cVoucheramountValuetype = cVoucheramountValuetype;
    }

    public String getcVouchertypeId() {
        return cVouchertypeId;
    }

    public void setcVouchertypeId(String cVouchertypeId) {
        this.cVouchertypeId = cVouchertypeId;
    }

    public Date getcVoucheramountStartdate() {
        return cVoucheramountStartdate;
    }

    public void setcVoucheramountStartdate(Date cVoucheramountStartdate) {
        this.cVoucheramountStartdate = cVoucheramountStartdate;
    }

    public Date getcVoucheramountEnddate() {
        return cVoucheramountEnddate;
    }

    public void setcVoucheramountEnddate(Date cVoucheramountEnddate) {
        this.cVoucheramountEnddate = cVoucheramountEnddate;
    }

    public Character getcVoucheramountStatus() {
        return cVoucheramountStatus;
    }

    public void setcVoucheramountStatus(Character cVoucheramountStatus) {
        this.cVoucheramountStatus = cVoucheramountStatus;
    }

    public String getcVoucheramountDomain() {
        return cVoucheramountDomain;
    }

    public void setcVoucheramountDomain(String cVoucheramountDomain) {
        this.cVoucheramountDomain = cVoucheramountDomain;
    }

    public String getcVoucheramountModifiedby() {
        return cVoucheramountModifiedby;
    }

    public void setcVoucheramountModifiedby(String cVoucheramountModifiedby) {
        this.cVoucheramountModifiedby = cVoucheramountModifiedby;
    }

    public Date getcVoucheramountModifiedon() {
        return cVoucheramountModifiedon;
    }

    public void setcVoucheramountModifiedon(Date cVoucheramountModifiedon) {
        this.cVoucheramountModifiedon = cVoucheramountModifiedon;
    }

    public String getcVoucheramountCreatedby() {
        return cVoucheramountCreatedby;
    }

    public void setcVoucheramountCreatedby(String cVoucheramountCreatedby) {
        this.cVoucheramountCreatedby = cVoucheramountCreatedby;
    }

    public Date getcVoucheramountCreatedon() {
        return cVoucheramountCreatedon;
    }

    public void setcVoucheramountCreatedon(Date cVoucheramountCreatedon) {
        this.cVoucheramountCreatedon = cVoucheramountCreatedon;
    }
    
    

}
