/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.comservice;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_serviceprovider", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"c_serviceprv_name"})})
public class Serviceprovider implements Serializable {

    @Column(name = "c_serviceprv_id", table = "arts_t_serviceprovider", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_serviceprv_name", table = "arts_t_serviceprovider", nullable = false, length = 100)
    @Basic
    private String cServiceprvName;

    @Column(name = "c_serviceprv_domain", table = "arts_t_serviceprovider", nullable = false, length = 36)
    @Basic
    private String cServiceprvDomain;

    @Column(name = "c_serviceprv_status", table = "arts_t_serviceprovider", nullable = false)
    @Basic
    private Character cServiceprvStatus;

    @Column(name = "c_serviceprv_modifiedby", table = "arts_t_serviceprovider", nullable = false, length = 36)
    @Basic
    private String cServiceprvModifiedby;

    @Column(name = "c_serviceprv_modifiedon", table = "arts_t_serviceprovider", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cServiceprvModifiedon;

    @Column(name = "c_serviceprv_address", table = "arts_t_serviceprovider", nullable = false, length = 500)
    @Basic
    private String cServiceprvAddress;

    @Column(name = "c_serviceprv_phonenum", table = "arts_t_serviceprovider", nullable = false, length = 20)
    @Basic
    private String cServiceprvPhonenum;

    @Column(name = "c_serviceprv_cp", table = "arts_t_serviceprovider", nullable = false, length = 100)
    @Basic
    private String cServiceprvCp;

    @Column(name = "c_serviceprovider_createdby", table = "arts_t_serviceprovider", nullable = false, length = 36)
    @Basic
    private String cServiceproviderCreatedby;

    @Column(name = "c_serviceprovider_createdon", table = "arts_t_serviceprovider", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cServiceproviderCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcServiceprvName() {
        return cServiceprvName;
    }

    public void setcServiceprvName(String cServiceprvName) {
        this.cServiceprvName = cServiceprvName;
    }

    public String getcServiceprvDomain() {
        return cServiceprvDomain;
    }

    public void setcServiceprvDomain(String cServiceprvDomain) {
        this.cServiceprvDomain = cServiceprvDomain;
    }

    public Character getcServiceprvStatus() {
        return cServiceprvStatus;
    }

    public void setcServiceprvStatus(Character cServiceprvStatus) {
        this.cServiceprvStatus = cServiceprvStatus;
    }

    public String getcServiceprvModifiedby() {
        return cServiceprvModifiedby;
    }

    public void setcServiceprvModifiedby(String cServiceprvModifiedby) {
        this.cServiceprvModifiedby = cServiceprvModifiedby;
    }

    public Date getcServiceprvModifiedon() {
        return cServiceprvModifiedon;
    }

    public void setcServiceprvModifiedon(Date cServiceprvModifiedon) {
        this.cServiceprvModifiedon = cServiceprvModifiedon;
    }

    public String getcServiceprvAddress() {
        return cServiceprvAddress;
    }

    public void setcServiceprvAddress(String cServiceprvAddress) {
        this.cServiceprvAddress = cServiceprvAddress;
    }

    public String getcServiceprvPhonenum() {
        return cServiceprvPhonenum;
    }

    public void setcServiceprvPhonenum(String cServiceprvPhonenum) {
        this.cServiceprvPhonenum = cServiceprvPhonenum;
    }

    public String getcServiceprvCp() {
        return cServiceprvCp;
    }

    public void setcServiceprvCp(String cServiceprvCp) {
        this.cServiceprvCp = cServiceprvCp;
    }

    public String getcServiceproviderCreatedby() {
        return cServiceproviderCreatedby;
    }

    public void setcServiceproviderCreatedby(String cServiceproviderCreatedby) {
        this.cServiceproviderCreatedby = cServiceproviderCreatedby;
    }

    public Date getcServiceproviderCreatedon() {
        return cServiceproviderCreatedon;
    }

    public void setcServiceproviderCreatedon(Date cServiceproviderCreatedon) {
        this.cServiceproviderCreatedon = cServiceproviderCreatedon;
    }

    

}
