/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.messages;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_announcement")
public class Announcement implements Serializable {

    @Column(name = "c_announcement_id", table = "arts_t_announcement", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_announcement_date", table = "arts_t_announcement", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAnnouncementDate;

    @Column(name = "c_announcement_title", table = "arts_t_announcement", nullable = false, length = 500)
    @Basic
    private String cAnnouncementTitle;

    @Column(name = "c_announcement_content", table = "arts_t_announcement", length = 2147483647)
    @Lob
    @Basic
    private String cAnnouncementContent;

    @Column(name = "c_user_id", table = "arts_t_announcement", nullable = false, length = 36)
    @Basic
    private String cUserId;

    @Column(name = "c_announcement_status", table = "arts_t_announcement", nullable = false)
    @Basic
    private Character cAnnouncementStatus;

    @Column(name = "c_announcement_domain", table = "arts_t_announcement", nullable = false, length = 36)
    @Basic
    private String cAnnouncementDomain;

    @Column(name = "c_announcement_modifiedby", table = "arts_t_announcement", nullable = false, length = 36)
    @Basic
    private String cAnnouncementModifiedby;

    @Column(name = "c_announcement_modifiedon", table = "arts_t_announcement", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAnnouncementModifiedon;

    @Column(name = "c_announcement_createdby", table = "arts_t_announcement", nullable = false, length = 36)
    @Basic
    private String cAnnouncementCreatedby;

    @Column(name = "c_announcement_createdon", table = "arts_t_announcement", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cAnnouncementCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcAnnouncementDate() {
        return cAnnouncementDate;
    }

    public void setcAnnouncementDate(Date cAnnouncementDate) {
        this.cAnnouncementDate = cAnnouncementDate;
    }

    public String getcAnnouncementTitle() {
        return cAnnouncementTitle;
    }

    public void setcAnnouncementTitle(String cAnnouncementTitle) {
        this.cAnnouncementTitle = cAnnouncementTitle;
    }

    public String getcAnnouncementContent() {
        return cAnnouncementContent;
    }

    public void setcAnnouncementContent(String cAnnouncementContent) {
        this.cAnnouncementContent = cAnnouncementContent;
    }

    public String getcUserId() {
        return cUserId;
    }

    public void setcUserId(String cUserId) {
        this.cUserId = cUserId;
    }

    public Character getcAnnouncementStatus() {
        return cAnnouncementStatus;
    }

    public void setcAnnouncementStatus(Character cAnnouncementStatus) {
        this.cAnnouncementStatus = cAnnouncementStatus;
    }

    public String getcAnnouncementDomain() {
        return cAnnouncementDomain;
    }

    public void setcAnnouncementDomain(String cAnnouncementDomain) {
        this.cAnnouncementDomain = cAnnouncementDomain;
    }

    public String getcAnnouncementModifiedby() {
        return cAnnouncementModifiedby;
    }

    public void setcAnnouncementModifiedby(String cAnnouncementModifiedby) {
        this.cAnnouncementModifiedby = cAnnouncementModifiedby;
    }

    public Date getcAnnouncementModifiedon() {
        return cAnnouncementModifiedon;
    }

    public void setcAnnouncementModifiedon(Date cAnnouncementModifiedon) {
        this.cAnnouncementModifiedon = cAnnouncementModifiedon;
    }

    public String getcAnnouncementCreatedby() {
        return cAnnouncementCreatedby;
    }

    public void setcAnnouncementCreatedby(String cAnnouncementCreatedby) {
        this.cAnnouncementCreatedby = cAnnouncementCreatedby;
    }

    public Date getcAnnouncementCreatedon() {
        return cAnnouncementCreatedon;
    }

    public void setcAnnouncementCreatedon(Date cAnnouncementCreatedon) {
        this.cAnnouncementCreatedon = cAnnouncementCreatedon;
    }

    

}
