/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.sap;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_sapschedule")
public class Sapschedule {

    @Column(name = "c_sapschedule_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_sapschedule_startdate", table = "arts_t_sapschedule", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSapscheduleStartdate;

    @Column(name = "c_sapschedule_enddate", table = "arts_t_sapschedule", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSapscheduleEnddate;

    @Column(name = "c_wagonclass_id", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_schedule_id", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cScheduleId;

    @Column(name = "c_sapschedule_pc", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cSapschedulePc;

    @Column(name = "c_sapschedule_status", table = "arts_t_sapschedule", nullable = false)
    @Basic
    private Character cSapscheduleStatus;

    @Column(name = "c_sapschedule_domain", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cSapscheduleDomain;

    @Column(name = "c_sapschedule_modifiedby", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cSapscheduleModifiedby;

    @Column(name = "c_sapschedule_modifiedon", table = "arts_t_sapschedule", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSapscheduleModifiedon;

    @Column(name = "c_sapschedule_createdby", table = "arts_t_sapschedule", nullable = false, length = 36)
    @Basic
    private String cSapscheduleCreatedby;

    @Column(name = "c_sapschedule_createdon", table = "arts_t_sapschedule", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cSapscheduleCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getcSapscheduleStartdate() {
        return cSapscheduleStartdate;
    }

    public void setcSapscheduleStartdate(Date cSapscheduleStartdate) {
        this.cSapscheduleStartdate = cSapscheduleStartdate;
    }

    public Date getcSapscheduleEnddate() {
        return cSapscheduleEnddate;
    }

    public void setcSapscheduleEnddate(Date cSapscheduleEnddate) {
        this.cSapscheduleEnddate = cSapscheduleEnddate;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public String getcScheduleId() {
        return cScheduleId;
    }

    public void setcScheduleId(String cScheduleId) {
        this.cScheduleId = cScheduleId;
    }

    public String getcSapschedulePc() {
        return cSapschedulePc;
    }

    public void setcSapschedulePc(String cSapschedulePc) {
        this.cSapschedulePc = cSapschedulePc;
    }

    public Character getcSapscheduleStatus() {
        return cSapscheduleStatus;
    }

    public void setcSapscheduleStatus(Character cSapscheduleStatus) {
        this.cSapscheduleStatus = cSapscheduleStatus;
    }

    public String getcSapscheduleDomain() {
        return cSapscheduleDomain;
    }

    public void setcSapscheduleDomain(String cSapscheduleDomain) {
        this.cSapscheduleDomain = cSapscheduleDomain;
    }

    public String getcSapscheduleModifiedby() {
        return cSapscheduleModifiedby;
    }

    public void setcSapscheduleModifiedby(String cSapscheduleModifiedby) {
        this.cSapscheduleModifiedby = cSapscheduleModifiedby;
    }

    public Date getcSapscheduleModifiedon() {
        return cSapscheduleModifiedon;
    }

    public void setcSapscheduleModifiedon(Date cSapscheduleModifiedon) {
        this.cSapscheduleModifiedon = cSapscheduleModifiedon;
    }

    public String getcSapscheduleCreatedby() {
        return cSapscheduleCreatedby;
    }

    public void setcSapscheduleCreatedby(String cSapscheduleCreatedby) {
        this.cSapscheduleCreatedby = cSapscheduleCreatedby;
    }

    public Date getcSapscheduleCreatedon() {
        return cSapscheduleCreatedon;
    }

    public void setcSapscheduleCreatedon(Date cSapscheduleCreatedon) {
        this.cSapscheduleCreatedon = cSapscheduleCreatedon;
    }

    

}
