/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.closing;

import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_closingibook")
public class Closingibook {

    @Column(name = "c_closingibook_id")
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_closingibook_docnum", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cClosingibookDocnum;

    @Column(name = "c_stasiun_idorg", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cStasiunIdorg;

    @Column(name = "c_closingibook_noka", table = "arts_t_closingibook", nullable = false, length = 50)
    @Basic
    private String cClosingibookNoka;

    @Column(name = "c_wagonclass_id", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_closingibook_date", table = "arts_t_closingibook", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingibookDate;

    @Column(name = "c_trip_id", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_closingibook_psgnum", table = "arts_t_closingibook", nullable = false)
    @Basic
    private BigInteger cClosingibookPsgnum;

    @Column(name = "c_closingibook_amount", table = "arts_t_closingibook", nullable = false)
    @Basic
    private BigInteger cClosingibookAmount;

    @Column(name = "c_closingibook_modifiedon", table = "arts_t_closingibook", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingibookModifiedon;

    @Column(name = "c_closingibook_postingstat", table = "arts_t_closingibook", nullable = false)
    @Basic
    private Character cClosingibookPostingstat;

    @Column(name = "c_closingibook_arrivedate", table = "arts_t_closingibook")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingibookArrivedate;

    @Column(name = "c_closingibook_status", table = "arts_t_closingibook", nullable = false)
    @Basic
    private Character cClosingibookStatus;

    @Column(name = "c_closingibook_domain", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cClosingibookDomain;

    @Column(name = "c_closingibook_modifiedby", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cClosingibookModifiedby;

    @Column(name = "c_closingibook_createdby", table = "arts_t_closingibook", nullable = false, length = 36)
    @Basic
    private String cClosingibookCreatedby;

    @Column(name = "c_closingibook_createdon", table = "arts_t_closingibook", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingibookCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcClosingibookDocnum() {
        return cClosingibookDocnum;
    }

    public void setcClosingibookDocnum(String cClosingibookDocnum) {
        this.cClosingibookDocnum = cClosingibookDocnum;
    }

    public String getcStasiunIdorg() {
        return cStasiunIdorg;
    }

    public void setcStasiunIdorg(String cStasiunIdorg) {
        this.cStasiunIdorg = cStasiunIdorg;
    }

    public String getcClosingibookNoka() {
        return cClosingibookNoka;
    }

    public void setcClosingibookNoka(String cClosingibookNoka) {
        this.cClosingibookNoka = cClosingibookNoka;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public Date getcClosingibookDate() {
        return cClosingibookDate;
    }

    public void setcClosingibookDate(Date cClosingibookDate) {
        this.cClosingibookDate = cClosingibookDate;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public BigInteger getcClosingibookPsgnum() {
        return cClosingibookPsgnum;
    }

    public void setcClosingibookPsgnum(BigInteger cClosingibookPsgnum) {
        this.cClosingibookPsgnum = cClosingibookPsgnum;
    }

    public BigInteger getcClosingibookAmount() {
        return cClosingibookAmount;
    }

    public void setcClosingibookAmount(BigInteger cClosingibookAmount) {
        this.cClosingibookAmount = cClosingibookAmount;
    }

    public Date getcClosingibookModifiedon() {
        return cClosingibookModifiedon;
    }

    public void setcClosingibookModifiedon(Date cClosingibookModifiedon) {
        this.cClosingibookModifiedon = cClosingibookModifiedon;
    }

    public Character getcClosingibookPostingstat() {
        return cClosingibookPostingstat;
    }

    public void setcClosingibookPostingstat(Character cClosingibookPostingstat) {
        this.cClosingibookPostingstat = cClosingibookPostingstat;
    }

    public Date getcClosingibookArrivedate() {
        return cClosingibookArrivedate;
    }

    public void setcClosingibookArrivedate(Date cClosingibookArrivedate) {
        this.cClosingibookArrivedate = cClosingibookArrivedate;
    }

    public Character getcClosingibookStatus() {
        return cClosingibookStatus;
    }

    public void setcClosingibookStatus(Character cClosingibookStatus) {
        this.cClosingibookStatus = cClosingibookStatus;
    }

    public String getcClosingibookDomain() {
        return cClosingibookDomain;
    }

    public void setcClosingibookDomain(String cClosingibookDomain) {
        this.cClosingibookDomain = cClosingibookDomain;
    }

    public String getcClosingibookModifiedby() {
        return cClosingibookModifiedby;
    }

    public void setcClosingibookModifiedby(String cClosingibookModifiedby) {
        this.cClosingibookModifiedby = cClosingibookModifiedby;
    }

    public String getcClosingibookCreatedby() {
        return cClosingibookCreatedby;
    }

    public void setcClosingibookCreatedby(String cClosingibookCreatedby) {
        this.cClosingibookCreatedby = cClosingibookCreatedby;
    }

    public Date getcClosingibookCreatedon() {
        return cClosingibookCreatedon;
    }

    public void setcClosingibookCreatedon(Date cClosingibookCreatedon) {
        this.cClosingibookCreatedon = cClosingibookCreatedon;
    }

    
}
