/**
 * This file was generated by the JPA Modeler
 */
package co.id.artslv.lib.closing;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * @author root
 */
@Entity
@Table(name = "arts_t_closingagent")
public class Closingagent implements Serializable {

    @Column(name = "c_closingagent_id", table = "arts_t_closingagent", nullable = false, length = 36)
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private String id;

    @Column(name = "c_closingagent_docnum", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cClosingagentDocnum;

    @Column(name = "c_agentdet_id", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cAgentdetId;

    @Column(name = "c_stasiun_idorg", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cStasiunIdorg;

    @Column(name = "c_closingagent_noka", table = "arts_t_closingagent", nullable = false, length = 50)
    @Basic
    private String cClosingagentNoka;

    @Column(name = "c_wagonclass_id", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cWagonclassId;

    @Column(name = "c_closingagent_date", table = "arts_t_closingagent", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingagentDate;

    @Column(name = "c_trip_id", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cTripId;

    @Column(name = "c_closingagent_psgnum", table = "arts_t_closingagent", nullable = false)
    @Basic
    private BigInteger cClosingagentPsgnum;

    @Column(name = "c_closingagent_amount", table = "arts_t_closingagent", nullable = false)
    @Basic
    private BigInteger cClosingagentAmount;

    @Column(name = "c_closingagent_type", table = "arts_t_closingagent")
    @Basic
    private Character cClosingagentType;

    @Column(name = "c_closingagent_modifiedon", table = "arts_t_closingagent", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingagentModifiedon;

    @Column(name = "c_closingagent_postingstat", table = "arts_t_closingagent", nullable = false)
    @Basic
    private Character cClosingagentPostingstat;

    @Column(name = "c_closingagent_docnumagent", table = "arts_t_closingagent", length = 36)
    @Basic
    private String cClosingagentDocnumagent;

    @Column(name = "c_closingagent_arrivedate", table = "arts_t_closingagent")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingagentArrivedate;

    @Column(name = "c_closingagent_status", table = "arts_t_closingagent", nullable = false)
    @Basic
    private Character cClosingagentStatus;

    @Column(name = "c_closingagent_domain", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cClosingagentDomain;

    @Column(name = "c_closingagent_modifiedby", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cClosingagentModifiedby;

    @Column(name = "c_closingagent_createdby", table = "arts_t_closingagent", nullable = false, length = 36)
    @Basic
    private String cClosingagentCreatedby;

    @Column(name = "c_closingagent_createdon", table = "arts_t_closingagent", nullable = false)
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date cClosingagentCreatedon;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getcClosingagentDocnum() {
        return cClosingagentDocnum;
    }

    public void setcClosingagentDocnum(String cClosingagentDocnum) {
        this.cClosingagentDocnum = cClosingagentDocnum;
    }

    public String getcAgentdetId() {
        return cAgentdetId;
    }

    public void setcAgentdetId(String cAgentdetId) {
        this.cAgentdetId = cAgentdetId;
    }

    public String getcStasiunIdorg() {
        return cStasiunIdorg;
    }

    public void setcStasiunIdorg(String cStasiunIdorg) {
        this.cStasiunIdorg = cStasiunIdorg;
    }

    public String getcClosingagentNoka() {
        return cClosingagentNoka;
    }

    public void setcClosingagentNoka(String cClosingagentNoka) {
        this.cClosingagentNoka = cClosingagentNoka;
    }

    public String getcWagonclassId() {
        return cWagonclassId;
    }

    public void setcWagonclassId(String cWagonclassId) {
        this.cWagonclassId = cWagonclassId;
    }

    public Date getcClosingagentDate() {
        return cClosingagentDate;
    }

    public void setcClosingagentDate(Date cClosingagentDate) {
        this.cClosingagentDate = cClosingagentDate;
    }

    public String getcTripId() {
        return cTripId;
    }

    public void setcTripId(String cTripId) {
        this.cTripId = cTripId;
    }

    public BigInteger getcClosingagentPsgnum() {
        return cClosingagentPsgnum;
    }

    public void setcClosingagentPsgnum(BigInteger cClosingagentPsgnum) {
        this.cClosingagentPsgnum = cClosingagentPsgnum;
    }

    public BigInteger getcClosingagentAmount() {
        return cClosingagentAmount;
    }

    public void setcClosingagentAmount(BigInteger cClosingagentAmount) {
        this.cClosingagentAmount = cClosingagentAmount;
    }

    public Character getcClosingagentType() {
        return cClosingagentType;
    }

    public void setcClosingagentType(Character cClosingagentType) {
        this.cClosingagentType = cClosingagentType;
    }

    public Date getcClosingagentModifiedon() {
        return cClosingagentModifiedon;
    }

    public void setcClosingagentModifiedon(Date cClosingagentModifiedon) {
        this.cClosingagentModifiedon = cClosingagentModifiedon;
    }

    public Character getcClosingagentPostingstat() {
        return cClosingagentPostingstat;
    }

    public void setcClosingagentPostingstat(Character cClosingagentPostingstat) {
        this.cClosingagentPostingstat = cClosingagentPostingstat;
    }

    public String getcClosingagentDocnumagent() {
        return cClosingagentDocnumagent;
    }

    public void setcClosingagentDocnumagent(String cClosingagentDocnumagent) {
        this.cClosingagentDocnumagent = cClosingagentDocnumagent;
    }

    public Date getcClosingagentArrivedate() {
        return cClosingagentArrivedate;
    }

    public void setcClosingagentArrivedate(Date cClosingagentArrivedate) {
        this.cClosingagentArrivedate = cClosingagentArrivedate;
    }

    public Character getcClosingagentStatus() {
        return cClosingagentStatus;
    }

    public void setcClosingagentStatus(Character cClosingagentStatus) {
        this.cClosingagentStatus = cClosingagentStatus;
    }

    public String getcClosingagentDomain() {
        return cClosingagentDomain;
    }

    public void setcClosingagentDomain(String cClosingagentDomain) {
        this.cClosingagentDomain = cClosingagentDomain;
    }

    public String getcClosingagentModifiedby() {
        return cClosingagentModifiedby;
    }

    public void setcClosingagentModifiedby(String cClosingagentModifiedby) {
        this.cClosingagentModifiedby = cClosingagentModifiedby;
    }

    public String getcClosingagentCreatedby() {
        return cClosingagentCreatedby;
    }

    public void setcClosingagentCreatedby(String cClosingagentCreatedby) {
        this.cClosingagentCreatedby = cClosingagentCreatedby;
    }

    public Date getcClosingagentCreatedon() {
        return cClosingagentCreatedon;
    }

    public void setcClosingagentCreatedon(Date cClosingagentCreatedon) {
        this.cClosingagentCreatedon = cClosingagentCreatedon;
    }

    

}
